Repository nuxeo/nuxeo-drive, pull requests merged in 2018-11, with the labels that each got.

#656 NXDRIVE-1407: Display CLI arguments in the fatal error screen
  docs/changes/4.0.1.md
  nxdrive/__main__.py
  nxdrive/commandline.py
Labels: improvement

#655 NXDRIVE-1250: Create the Windows sub-installer for additionnal features
  docs/changes/4.0.1.md
  tools/windows/deploy_jenkins_slave.ps1
  tools/windows/setup-addons.iss
  tools/windows/setup.iss
Labels: new-feature

#661 NXDRIVE-1424: Fix Windows uninstallation documentation
  docs/changes/4.0.1.md
  docs/installer.md
Labels: bugfix, doc

#663 NXDRIVE-1418: Fix the error and conflict notifications' action
  docs/changes/4.0.1.md
  nxdrive/gui/application.py
  nxdrive/notification.py
Labels: bugfix

#664 NXDRIVE-1425: Add 3.1.2 change notes
  docs/changes.md
  docs/changes/3.1.2.md
Labels: doc

#668 NXDRIVE-1427: Update the GNU/Linux installation steps in the README
  README.md
  docs/changes/4.0.1.md
  nxdrive/updater/README.md
Labels: GNU/Linux, bugfix, doc

#669 NXDRIVE-1405: Handle local INI system-wide configuration
  docs/changes/4.0.1.md
  nxdrive/commandline.py
  nxdrive/options.py
  tests/test_commandline.py
  tests/test_options.py
Labels: improvement, new-feature

#666 NXDRIVE-1259: Be more consistent with file/folder renaming
  docs/changes/4.0.1.md
  nxdrive/client/local_client.py
  nxdrive/utils.py
  tests/test_local_client.py
  tests/test_special_characters.py
  tests/test_synchronization.py
  tests/test_updater.py
Labels: bugfix

#672 Automatic update of translations from Crowdin (all)
  nxdrive/data/i18n/i18n-de.json
  nxdrive/data/i18n/i18n-es-ES.json
  nxdrive/data/i18n/i18n-he.json
  nxdrive/data/i18n/i18n-id.json
  nxdrive/data/i18n/i18n-it.json
  nxdrive/data/i18n/i18n-ja.json
  nxdrive/data/i18n/i18n-nl.json
  nxdrive/data/i18n/i18n-sv-SE.json
Labels: translations

#674 NXDRIVE-1434: Fix the "consider-ssl-errors" option implementation
  docs/changes/4.0.1.md
  nxdrive/client/proxy.py
  nxdrive/client/remote_client.py
  nxdrive/commandline.py
  nxdrive/gui/api.py
  nxdrive/gui/application.py
  nxdrive/manager.py
  nxdrive/updater/base.py
  nxdrive/utils.py
Labels: bugfix

#673 NXDRIVE-1213: Prevent ignored files from coming back in error after some time
  docs/changes/4.0.1.md
  nxdrive/data/qml/FileCard.qml
  nxdrive/engine/dao/sqlite.py
  nxdrive/engine/engine.py
  nxdrive/engine/processor.py
  nxdrive/gui/api.py
  tests/test_ignored.py
Labels: bugfix

#676 NXDRIVE-1349: Enable DirectEdit on other blobs than the main one
  docs/changes/4.0.1.md
  nxdrive/client/remote_client.py
  nxdrive/direct_edit.py
  nxdrive/engine/tracker.py
  nxdrive/objects.py
  tests/test_direct_edit.py
  tests/test_permission_hierarchy.py
  tests/test_remote_move_and_rename.py
  tests/test_synchronization.py
Labels: improvement

#678 NXDRIVE-1417: Handle null properties in objects instantation
  docs/changes/4.0.1.md
  ftest/pom.xml
  nxdrive/engine/watcher/remote_watcher.py
  nxdrive/objects.py
Labels: bugfix

#684 NXDRIVE-1433: Handle custom SSL certificates
  docs/changes/4.0.1.md
  docs/changes/4.0.2.md
  docs/configuration.md
  nxdrive/client/proxy.py
  nxdrive/client/remote_client.py
  nxdrive/commandline.py
  nxdrive/gui/api.py
  nxdrive/gui/application.py
  nxdrive/options.py
  nxdrive/updater/base.py
  nxdrive/utils.py
Labels: new-feature

#685 NXDRIVE-1433: Enhance the documentation about parameters formatting
  docs/configuration.md
Labels: doc, improvement

#686 NXDRIVE-1385: Missing translations
  docs/changes/4.0.2.md
  docs/configuration.md
  nxdrive/commandline.py
  nxdrive/data/i18n/i18n.json
  nxdrive/gui/application.py
  nxdrive/gui/systray.py
  nxdrive/gui/view.py
  nxdrive/osi/__init__.py
  nxdrive/osi/darwin/darwin.py
  nxdrive/osi/windows/registry.py
  nxdrive/osi/windows/windows.py
  nxdrive/translator.py
  nxdrive/utils.py
  tests/test_utils.py
  tests/test_windows.py
  tools/osx/drive/NuxeoFinderSync/FinderSync.swift
  tools/windows/setup-admin.iss
  tools/windows/setup-common.iss
  tools/windows/setup.iss
Labels: bugfix

#691 NXDRIVE-404: Fix connection to simple HTTP servers
  docs/changes/4.0.2.md
  nxdrive/exceptions.py
  nxdrive/gui/api.py
  nxdrive/utils.py
Labels: bugfix
