Repository nuxeo/nuxeo-drive, pull requests merged in 2018-08, with the labels that each got.

#550 Upgrade pytest and xattr
  docs/changes.md
  requirements-tests.txt
  requirements.txt
Labels: dependencies

#555 NXDRIVE-1276: Add documentation about Nuxeo Platform support
  docs/changes.md
  docs/support.md
Labels: doc

#557 NXDRIVE-1292: Fix bad file renaming
  nxdrive/gui/api.py
  nxdrive/gui/application.py
  nxdrive/gui/dev/authentication.py
  nxdrive/gui/dev/dialog.py
Labels: bugfix

#567 NXDRIVE-1128: Automatic update of translations from Crowdin (all)
  nxdrive/data/i18n/i18n-de.json
  nxdrive/data/i18n/i18n-es-ES.json
  nxdrive/data/i18n/i18n-fr.json
  nxdrive/data/i18n/i18n-he.json
  nxdrive/data/i18n/i18n-id.json
  nxdrive/data/i18n/i18n-it.json
  nxdrive/data/i18n/i18n-ja.json
  nxdrive/data/i18n/i18n-nl.json
  nxdrive/data/i18n/i18n-sv-SE.json
Labels: translations

#569 NXDRIVE-1310: Missing win32timezone module after packaging on Windows
  ndrive.spec
Labels: Windows, bugfix

#563 NXDRIVE-1295: Fix Sytem Tray Menu behaviors
  docs/technical_changes.md
  nxdrive/data/i18n/i18n.json
  nxdrive/data/qml/Conflicts.qml
  nxdrive/data/qml/FileCard.qml
  nxdrive/data/qml/Main.qml
  nxdrive/data/qml/Settings.qml
  nxdrive/data/qml/SettingsTab.qml
  nxdrive/data/qml/Systray.qml
  nxdrive/data/qml/SystrayStatus.qml
  nxdrive/engine/dao/sqlite.py
  nxdrive/engine/engine.py
  nxdrive/gui/api.py
  nxdrive/gui/application.py
  nxdrive/gui/systray.py
  nxdrive/gui/view.py
  nxdrive/manager.py
  nxdrive/updater/base.py
  nxdrive/updater/darwin.py
  tests/manual/common.py
  tools/osx/deploy_jenkins_slave.sh
Labels: bugfix, improvement

#573 Automatic update of translations from Crowdin (all)
  nxdrive/data/i18n/i18n-de.json
  nxdrive/data/i18n/i18n-es-ES.json
  nxdrive/data/i18n/i18n-fr.json
  nxdrive/data/i18n/i18n-he.json
  nxdrive/data/i18n/i18n-id.json
  nxdrive/data/i18n/i18n-it.json
  nxdrive/data/i18n/i18n-ja.json
  nxdrive/data/i18n/i18n-nl.json
  nxdrive/data/i18n/i18n-sv-SE.json
Labels: translations

#575 NXDRIVE-1301: Fix .app tree to allow codesign on macOS
  tools/osx/deploy_jenkins_slave.sh
  tools/osx/fix_app_qt_folder_names_for_codesign.py
  tools/posix/deploy_jenkins_slave.sh
Labels: bugfix, macOS

#576 NXDRIVE-1319: Missing OpenGL DLLs after packaging on Windows
  ndrive.spec
  nxdrive/manager.py
Labels: Windows, bugfix

#584 Automatic update of translations from Crowdin (en)
  nxdrive/data/i18n/i18n-he.json
Labels: translations

#593 NXDRIVE-1326: Add a feedback link in the "About" tab of Nuxeo Drive
  nxdrive/data/i18n/i18n.json
  nxdrive/data/qml/AboutTab.qml
Labels: improvement

#595 NXDRIVE-1329: Fix random bug in test_synchronize_remote_deletion_whil…
  tests/test_remote_deletion.py
Labels: bugfix
