Repository nuxeo/nuxeo-drive, pull requests merged in 2018-04, with the labels that each got.

#453 NXDRIVE-1173: Fix pip installation on Windows
  docs/changes.md
  tools/jenkins/tests.groovy
  tools/posix/deploy_jenkins_slave.sh
  tools/windows/deploy_jenkins_slave.ps1
Labels: Windows, bugfix

#455 NXDRIVE-1174: Efficient ConfigurationDAO.update_config()
  docs/changes.md
  docs/technical_changes.md
  nuxeo-drive-client/nxdrive/engine/dao/sqlite.py
Labels: improvement

#457 NXDRIVE-1173: Fix and update the PyPi issue link
  tools/jenkins/tests.groovy
  tools/windows/deploy_jenkins_slave.ps1
Labels: Windows, bugfix

#456 NXDRIVE-1175: New language: Hebrew
  docs/changes.md
  docs/support.md
  nuxeo-drive-client/nxdrive/data/i18n/i18n-he.json
  tools/windows/setup.iss
Labels: new-feature, translations

#459 NXDRIVE-1128: Automatic update of translations from Crowdin
  nuxeo-drive-client/nxdrive/data/i18n/i18n-de.json
  nuxeo-drive-client/nxdrive/data/i18n/i18n-es-ES.json
  nuxeo-drive-client/nxdrive/data/i18n/i18n-fr.json
  nuxeo-drive-client/nxdrive/data/i18n/i18n-he.json
  nuxeo-drive-client/nxdrive/data/i18n/i18n-it.json
  nuxeo-drive-client/nxdrive/data/i18n/i18n-ja.json
  nuxeo-drive-client/nxdrive/data/i18n/i18n-nl.json
  nuxeo-drive-client/nxdrive/data/i18n/i18n-sv-SE.json
Labels: translations

#458 NXDRIVE-891: Locked notification displays 'userid' instead of full username
  docs/changes.md
  nuxeo-drive-client/nxdrive/direct_edit.py
Labels: bugfix

#461 NXDRIVE-1025: Filters issue with folders at the same tree level
  docs/changes.md
  docs/technical_changes.md
  nuxeo-drive-client/nxdrive/engine/dao/sqlite.py
  nuxeo-drive-client/nxdrive/engine/engine.py
  nuxeo-drive-client/nxdrive/engine/processor.py
  nuxeo-drive-client/nxdrive/engine/watcher/remote_watcher.py
  nuxeo-drive-client/nxdrive/gui/folders_dialog.py
  nuxeo-drive-client/nxdrive/gui/folders_treeview.py
  nuxeo-drive-client/nxdrive/gui/status_dialog.py
  nuxeo-drive-client/tests/test_model_filters.py
Labels: bugfix

#463 NXDRIVE-1158: Restore the context menu "Edit metadata"
  docs/changes.md
  docs/technical_changes.md
  nuxeo-drive-client/nxdrive/commandline.py
  nuxeo-drive-client/nxdrive/direct_edit.py
  nuxeo-drive-client/nxdrive/engine/dao/sqlite.py
  nuxeo-drive-client/nxdrive/engine/engine.py
  nuxeo-drive-client/nxdrive/manager.py
  nuxeo-drive-client/nxdrive/utils.py
  nuxeo-drive-client/nxdrive/wui/application.py
  tools/linux/resources/nautilus/contextual_menu.py
  tools/osx/drive/NuxeoFinderSync/FinderSync.swift
  tools/windows/setup.iss
Labels: new-feature

#466 NXDRIVE-1179: Lost focus when FinderSync refreshes icons
  nxdrive/manager.py
  nxdrive/osi/darwin/darwin.py
  nxdrive/utils.py
  nxdrive/wui/application.py
  tools/osx/drive/NuxeoFinderSync/FinderSync.swift
  tools/osx/drive/NuxeoFinderSync/NuxeoFinderSync.entitlements
  tools/osx/drive/NuxeoFinderSync/Socket.swift
  tools/osx/drive/drive.xcodeproj/project.pbxproj
Labels: bugfix, macOS

#469 NXDRIVE-1187: Fix the PowerShell download command for Windows packaging
  docs/changes.md
  nxdrive/engine/tracker.py
  tools/windows/deploy_jenkins_slave.ps1
Labels: Windows, bugfix

#471 NXDRIVE-1190: Remove Microsoft Visual C++ Compiler from requirements
  docs/changes.md
  docs/deployment.md
Labels: clean-up

#472 NXDRIVE-1191: Use Java OpenJDK instead of Java Oracle
  docs/changes.md
  tools/jenkins/tests-8.10.groovy
  tools/jenkins/tests.groovy
Labels: bugfix

#474 NXDRIVE-261: Activate code signing on Windows
  docs/changes.md
  docs/deployment.md
  docs/digital_signature.md
  tools/windows/deploy_jenkins_slave.ps1
Labels: Windows, improvement

#473 NXDRIVE-1191: Use Java Oracle on macOS
  tools/jenkins/tests.groovy
Labels: bugfix

#475 NXDRIVE-512: Set Windows executable properties
  .gitignore
  ndrive.spec
  tools/windows/properties_tpl.rc
  tools/windows/setup.iss
Labels: Windows, improvement

#476 NXDRIVE-289: Use light icons on Windows
  docs/changes.md
  nxdrive/data/icons/conflict_light.svg
  nxdrive/data/icons/disabled_light.svg
  nxdrive/data/icons/error_light.svg
  nxdrive/data/icons/idle_light.svg
  nxdrive/data/icons/notification_light.svg
  nxdrive/data/icons/paused_light.svg
  nxdrive/data/icons/syncing_light.svg
  nxdrive/data/icons/update_light.svg
  nxdrive/wui/application.py
Labels: Windows, improvement

#479 NXDRIVE-1128: Automatic update of translations from Crowdin after NXDRIVE-988
  nxdrive/data/i18n/i18n-de.json
  nxdrive/data/i18n/i18n-es-ES.json
  nxdrive/data/i18n/i18n-fr.json
  nxdrive/data/i18n/i18n-he.json
  nxdrive/data/i18n/i18n-id.json
  nxdrive/data/i18n/i18n-it.json
  nxdrive/data/i18n/i18n-ja.json
  nxdrive/data/i18n/i18n-nl.json
  nxdrive/data/i18n/i18n-sv-SE.json
Labels: translations
