Repository nuxeo/nuxeo-drive, pull requests merged in 2018-10, with the labels that each got.

#644 Automatic update of translations from Crowdin (fr)
  nxdrive/data/i18n/i18n-fr.json
  nxdrive/data/i18n/i18n-he.json
Labels: translations

#645 Automatic update of translations from Crowdin (all)
  nxdrive/data/i18n/i18n-de.json
  nxdrive/data/i18n/i18n-es-ES.json
  nxdrive/data/i18n/i18n-fr.json
  nxdrive/data/i18n/i18n-he.json
  nxdrive/data/i18n/i18n-id.json
  nxdrive/data/i18n/i18n-it.json
  nxdrive/data/i18n/i18n-ja.json
  nxdrive/data/i18n/i18n-nl.json
  nxdrive/data/i18n/i18n-sv-SE.json
Labels: translations

#647 NXDRIVE-1395: Select the default UI after upgrade from 3.x
  nxdrive/data/qml/AccountsTab.qml
  nxdrive/engine/engine.py
Labels: bugfix

#648 NXDRIVE-1397: Use individual changelog file for each version
  docs/README.md
  docs/changes.md
  docs/changes/2.4.6.md
  docs/changes/2.4.7.md
  docs/changes/2.4.8.md
  docs/changes/2.5.0.md
  docs/changes/2.5.1.md
  docs/changes/2.5.2.md
  docs/changes/2.5.3.md
  docs/changes/2.5.4.md
  docs/changes/2.5.5.md
  docs/changes/2.5.6.md
  docs/changes/2.5.7.md
  docs/changes/2.5.8.md
  docs/changes/2.5.9.md
  docs/changes/3.0.0.md
  docs/changes/3.0.1.md
  docs/changes/3.0.2.md
  docs/changes/3.0.3.md
  docs/changes/3.0.4.md
  docs/changes/3.0.5.md
  docs/changes/3.0.6.md
  docs/changes/3.1.0.md
  docs/changes/3.1.1.md
  docs/changes/4.0.0.md
Labels: doc, improvement

#649 NXDRIVE-1398: Allow stable updates when using the beta channel
  nxdrive/gui/application.py
  nxdrive/updater/base.py
  nxdrive/updater/utils.py
  tests/test_updater.py
  tools/versions.py
Labels: bugfix

#650 NXDRIVE-1320: Review the communication between Drive and the FinderSync extension
  docs/changes/4.0.0.md
  nxdrive/manager.py
  nxdrive/options.py
  nxdrive/osi/darwin/darwin.py
  tools/osx/drive/NuxeoFinderSync/FileStatus.swift
  tools/osx/drive/NuxeoFinderSync/FinderSync.swift
  tools/osx/drive/drive.xcodeproj/project.pbxproj
Labels: bugfix, improvement

#654 NXDRIVE-1269: Bump version to 4.0.1
  docs/changes.md
  docs/changes/4.0.1.md
  docs/support.md
  nxdrive/__init__.py
Labels: doc
