Repository nuxeo/nuxeo-drive, pull requests merged in 2018-09, with the labels that each got.

#596 NXDRIVE-1327: Fix test_darwin on macOS
  nxdrive/osi/darwin/darwin.py
Labels: bugfix, macOS

#597 NXDRIVE-1333: Fix logging issues with non-latin characters on Windows
  nxdrive/client/local_client.py
  nxdrive/logging_config.py
  nxdrive/utils.py
Labels: Windows, bugfix

#598 Automatic update of translations from Crowdin (all)
  nxdrive/data/i18n/i18n-de.json
  nxdrive/data/i18n/i18n-es-ES.json
  nxdrive/data/i18n/i18n-fr.json
  nxdrive/data/i18n/i18n-he.json
  nxdrive/data/i18n/i18n-id.json
  nxdrive/data/i18n/i18n-it.json
  nxdrive/data/i18n/i18n-ja.json
  nxdrive/data/i18n/i18n-nl.json
  nxdrive/data/i18n/i18n-sv-SE.json
Labels: translations

#599 NXDRIVE-1337: Fix JSON export error when there is a proxy password
  docs/technical_changes.md
  nxdrive/client/proxy.py
  nxdrive/data/qml/ProxyPopup.qml
  nxdrive/gui/api.py
  tests/test_proxy.py
Labels: bugfix

#601 NXDRIVE-1171: Prevent Drive crash on URL open failure
  nxdrive/manager.py
Labels: Windows, bugfix

#600 NXDRIVE-1339: Handle boolean parameters
  docs/changes.md
  nxdrive/commandline.py
Labels: improvement

#609 NXDRIVE-1258: Automatic update of translations from Crowdin (all)
  nxdrive/data/i18n/i18n-de.json
  nxdrive/data/i18n/i18n-es-ES.json
  nxdrive/data/i18n/i18n-fr.json
  nxdrive/data/i18n/i18n-he.json
  nxdrive/data/i18n/i18n-id.json
  nxdrive/data/i18n/i18n-it.json
  nxdrive/data/i18n/i18n-ja.json
  nxdrive/data/i18n/i18n-nl.json
  nxdrive/data/i18n/i18n-sv-SE.json
Labels: translations

#610 NXDRIVE-1316: Check for upstream trigger, ensure exit on abort
  tools/jenkins/tests.groovy
Labels: improvement

#611 NXDRIVE-1171: Clean-up
  docs/changes.md
  docs/technical_changes.md
  nxdrive/commandline.py
  nxdrive/logging_config.py
  nxdrive/options.py
Labels: clean-up

#613 NXDRIVE-1307: Do not use nxdrive protocol from the FinderSync extension
  docs/changes.md
  docs/technical_changes.md
  nxdrive/gui/application.py
  nxdrive/manager.py
  nxdrive/osi/darwin/darwin.py
  nxdrive/utils.py
  tools/osx/deploy_jenkins_slave.sh
  tools/osx/drive/Frameworks/Socket.framework/Headers
  tools/osx/drive/Frameworks/Socket.framework/Modules
  tools/osx/drive/Frameworks/Socket.framework/Resources
  tools/osx/drive/Frameworks/Socket.framework/Socket
  tools/osx/drive/Frameworks/Socket.framework/Versions/A/Headers/Socket-Swift.h
  tools/osx/drive/Frameworks/Socket.framework/Versions/A/Headers/Socket.h
  tools/osx/drive/Frameworks/Socket.framework/Versions/A/Modules/Socket.swiftmodule/x86_64.swiftdoc
  tools/osx/drive/Frameworks/Socket.framework/Versions/A/Modules/Socket.swiftmodule/x86_64.swiftmodule
  tools/osx/drive/Frameworks/Socket.framework/Versions/A/Modules/module.modulemap
  tools/osx/drive/Frameworks/Socket.framework/Versions/A/Resources/BlueSocket.podspec
  tools/osx/drive/Frameworks/Socket.framework/Versions/A/Resources/Info.plist
  tools/osx/drive/Frameworks/Socket.framework/Versions/A/Resources/LICENSE
  tools/osx/drive/Frameworks/Socket.framework/Versions/A/Socket
  tools/osx/drive/Frameworks/Socket.framework/Versions/Current
  tools/osx/drive/NuxeoFinderSync/FinderSync.swift
  tools/osx/drive/NuxeoFinderSync/Socket.swift
  tools/osx/drive/drive.xcodeproj/project.pbxproj
Labels: bugfix

#616 Ugraded pyinstaller, pypac, pytest, pytest-cov and watchdog
  docs/changes.md
  requirements-dev.txt
  requirements-tests.txt
  requirements.txt
Labels: dependencies

#619 NXDRIVE-1195: Automatic update of translations from Crowdin (all)
  nxdrive/data/i18n/i18n-de.json
  nxdrive/data/i18n/i18n-es-ES.json
  nxdrive/data/i18n/i18n-fr.json
  nxdrive/data/i18n/i18n-he.json
  nxdrive/data/i18n/i18n-id.json
  nxdrive/data/i18n/i18n-it.json
  nxdrive/data/i18n/i18n-ja.json
  nxdrive/data/i18n/i18n-nl.json
  nxdrive/data/i18n/i18n-sv-SE.json
Labels: translations

#621 NXDRIVE-1342: Add the changelog entry
  docs/changes.md
Labels: doc

#624 NXDRIVE-1352: Fix the auto-update checker script
  tools/scripts/check_update_process.py
  tools/windows/deploy_jenkins_slave.ps1
Labels: Windows, bugfix, macOS

#626 NXDRIVE-970: Easy the future work by removing application name for th…
  nxdrive/commandline.py
  nxdrive/engine/tracker.py
  nxdrive/gui/api.py
  nxdrive/gui/status_dialog.py
  nxdrive/manager.py
Labels: improvement

#629 NXDRIVE-1370: Use a random table name in PGSQL
  docs/changes.md
  tools/jenkins/tests.groovy
Labels: bugfix

#630 NXDRIVE-1354: Bring Settings window to the top after login in the browser
  nxdrive/engine/tracker.py
  nxdrive/gui/application.py
  nxdrive/gui/folders_dialog.py
Labels: bugfix

#631 NXDRIVE-1356: Fix removed filters not appearing back when unchecked
  docs/technical_changes.md
  nxdrive/client/remote_client.py
  nxdrive/engine/engine.py
  nxdrive/gui/folders_treeview.py
Labels: bugfix
