Repository nuxeo/nuxeo-drive, pull requests merged in 2018-12, with the labels that each got.

#694 NXDRIVE-1385: Registry logging adjustments on Windows
  docs/changes/4.0.2.md
  nxdrive/commandline.py
  nxdrive/constants.py
  nxdrive/osi/windows/registry.py
  nxdrive/osi/windows/windows.py
Labels: Windows, improvement

#695 NXDRIVE-1457: Skip timebox tickets in changelog.py
  docs/changes/4.0.2.md
  tools/changelog.py
Labels: improvement

#696 NXDRIVE-1458: Display "Nuxeo Drive" in Windows notification…
  docs/changes/4.0.2.md
  tools/windows/properties_tpl.rc
Labels: Windows, improvement

#697 NXDRIVE-1347: Ignore unknown versions inversions.yml
  docs/changes/4.0.2.md
  nxdrive/updater/base.py
  nxdrive/updater/utils.py
  tests/test_updater.py
Labels: bugfix

#699 NXDRIVE-1432: Remove automatic logout before login
  docs/changes/4.0.2.md
  nxdrive/gui/api.py
Labels: bugfix

#701 Automatic update of translations from Crowdin (all)
  nxdrive/data/i18n/i18n-de.json
  nxdrive/data/i18n/i18n-es-ES.json
  nxdrive/data/i18n/i18n-fr.json
  nxdrive/data/i18n/i18n-he.json
  nxdrive/data/i18n/i18n-id.json
  nxdrive/data/i18n/i18n-it.json
  nxdrive/data/i18n/i18n-ja.json
  nxdrive/data/i18n/i18n-nl.json
  nxdrive/data/i18n/i18n-sv-SE.json
Labels: translations

#704 NXDRIVE-1460: Better handle the path folder selection in account crea…
  docs/changes/4.0.2.md
  nxdrive/data/qml/NewAccountPopup.qml
  nxdrive/gui/api.py
Labels: Windows, bugfix

#707 NXDRIVE-1439: Fix publish() from release.sh
  tools/release.sh
Labels: bugfix

#708 NXDRIVE-1455: Release 4.0.2
  docs/changes/4.0.2.md
Labels: doc

#709 NXDRIVE-1455: Bump version to 4.0.3
  docs/changes/4.0.3.md
  nxdrive/__init__.py
Labels: doc

#710 Automatic update of translations from Crowdin (all)
  nxdrive/data/i18n/i18n-de.json
  nxdrive/data/i18n/i18n-es-ES.json
  nxdrive/data/i18n/i18n-fr.json
  nxdrive/data/i18n/i18n-it.json
  nxdrive/data/i18n/i18n-ja.json
  nxdrive/data/i18n/i18n-nl.json
  nxdrive/data/i18n/i18n-sv-SE.json
Labels: translations

#711 NXDRIVE-1358: Fix flake8 errors
  nxdrive/engine/watcher/local_watcher.py
Labels: bugfix

#715 NXDRIVE-1463: Do not abort on error in changelog.py
  docs/changes/4.0.3.md
  tools/changelog.py
Labels: bugfix

#716 NXDRIVE-1465: Disable the auto-update switch when auto-update is disa…
  docs/changes/4.0.3.md
  nxdrive/data/qml/GeneralTab.qml
  nxdrive/gui/application.py
  nxdrive/manager.py
Labels: bugfix

#717 NXDRIVE-1477: Fix latest version computation in updater
  docs/changes/4.0.3.md
  nxdrive/updater/utils.py
  tests/test_updater.py
Labels: bugfix

#719 NXDRIVE-1478: Add values interpolation section in the configuration d…
  docs/changes/4.0.3.md
  docs/configuration.md
Labels: doc

#720 NXDRIVE-1471: Do not alter the filename extension guessed from a Note
  docs/changes/4.0.3.md
  nxdrive/objects.py
Labels: bugfix

#723 NXDRIVE-1429: Update pycryptodomex from 3.6.6 to 3.7.2
  docs/changes/4.0.3.md
  requirements.txt
Labels: dependencies

#722 NXDRIVE-1479: Handle Direct Edits with no xpath
  docs/changes/4.0.3.md
  nxdrive/direct_edit.py
  tests/test_direct_edit.py
Labels: bugfix
