Repository nuxeo/nuxeo-drive, pull requests merged in 2018-02, with the labels that each got.

#402 NXDRIVE-1107: Notify user of lost authenticated state during Direct Edit
  docs/changes.md
  docs/technical_changes.md
  nuxeo-drive-client/nxdrive/data/ui5/i18n.js
  nuxeo-drive-client/nxdrive/direct_edit.py
  nuxeo-drive-client/nxdrive/engine/engine.py
  nuxeo-drive-client/nxdrive/engine/queue_manager.py
  nuxeo-drive-client/nxdrive/engine/workers.py
  nuxeo-drive-client/nxdrive/manager.py
  nuxeo-drive-client/nxdrive/options.py
  nuxeo-drive-client/nxdrive/updater.py
  nuxeo-drive-client/nxdrive/utils.py
  nuxeo-drive-client/nxdrive/wui/application.py
  nuxeo-drive-client/nxdrive/wui/dialog.py
  nuxeo-drive-client/nxdrive/wui/modal.py
  nuxeo-drive-client/tests/test_direct_edit.py
  tools/jenkins/beta.groovy
  tools/jenkins/packages.groovy
  tools/jenkins/prod.groovy
  tools/jenkins/tests.groovy
Labels: bugfix

#408 NXDRIVE-1105: Avoid unwanted file deletions on Windows 7
  docs/changes.md
  nuxeo-drive-client/nxdrive/__init__.py
  nuxeo-drive-client/nxdrive/client/local_client.py
  nuxeo-drive-client/nxdrive/data/ui5/i18n.js
  nuxeo-drive-client/nxdrive/engine/engine.py
  nuxeo-drive-client/nxdrive/engine/processor.py
  nuxeo-drive-client/nxdrive/manager.py
  nuxeo-drive-client/nxdrive/notification.py
  nuxeo-drive-client/tests/test_manager_dao.py
  nuxeo-drive-client/tests/test_remote_move_and_rename.py
  nuxeo-drive-client/tests/test_windows.py
Labels: bugfix, clean-up

#410 NXDRIVE-1008: Document deleted server side when unfiltering and opened elsewhere
  docs/changes.md
  nuxeo-drive-client/nxdrive/client/local_client.py
  nuxeo-drive-client/nxdrive/data/ui5/i18n.js
  nuxeo-drive-client/nxdrive/engine/engine.py
  nuxeo-drive-client/nxdrive/engine/processor.py
  nuxeo-drive-client/nxdrive/engine/watcher/local_watcher.py
  nuxeo-drive-client/nxdrive/notification.py
  nuxeo-drive-client/tests/test_local_client.py
  nuxeo-drive-client/tests/test_synchronization.py
  tools/jenkins/tests.groovy
Labels: bugfix

#412 NXDRIVE-1118: Windows API used to trash files cannot deal with long paths
  docs/changes.md
  nuxeo-drive-client/nxdrive/client/local_client.py
  nuxeo-drive-client/nxdrive/engine/processor.py
  nuxeo-drive-client/tests/test_synchronization.py
  nuxeo-drive-client/tests/test_trash.py
  requirements.txt
  tools/integration_tests_setup.py
  tools/jenkins/packages.groovy
Labels: bugfix, dependencies

#414 NXDRIVE-1118: Fix obsolete synced files deletion
  nuxeo-drive-client/nxdrive/engine/processor.py
  nuxeo-drive-client/tests/test_synchronization.py
  tools/jenkins/tests.groovy
Labels: bugfix

#415 NXDRIVE-626: Use Crowdin for label translations
  README.md
  docs/changes.md
  docs/technical_changes.md
  nuxeo-drive-client/nxdrive/data/i18n/i18n-de.json
  nuxeo-drive-client/nxdrive/data/i18n/i18n-es-ES.json
  nuxeo-drive-client/nxdrive/data/i18n/i18n-fr.json
  nuxeo-drive-client/nxdrive/data/i18n/i18n-ja.json
  nuxeo-drive-client/nxdrive/data/i18n/i18n.json
  nuxeo-drive-client/nxdrive/data/ui5/activity.html
  nuxeo-drive-client/nxdrive/data/ui5/conflicts.html
  nuxeo-drive-client/nxdrive/data/ui5/debug.html
  nuxeo-drive-client/nxdrive/data/ui5/i18n.js
  nuxeo-drive-client/nxdrive/data/ui5/js/ndrive.js
  nuxeo-drive-client/nxdrive/data/ui5/modal.html
  nuxeo-drive-client/nxdrive/data/ui5/network_error.html
  nuxeo-drive-client/nxdrive/data/ui5/settings.html
  nuxeo-drive-client/nxdrive/data/ui5/systray.html
  nuxeo-drive-client/nxdrive/wui/application.py
  nuxeo-drive-client/nxdrive/wui/dialog.py
  nuxeo-drive-client/nxdrive/wui/translator.py
  nuxeo-drive-client/tests/common_unit_test.py
  nuxeo-drive-client/tests/resources/i18n.js
  nuxeo-drive-client/tests/resources/i18n/i18n-de-DE.json
  nuxeo-drive-client/tests/resources/i18n/i18n-fr.json
  nuxeo-drive-client/tests/resources/i18n/i18n.json
  nuxeo-drive-client/tests/test_translator.py
  setup.py
Labels: new-feature

#411 NXDRIVE-1121: Set modified date to Nuxeo platform modified date
  docs/changes.md
  nuxeo-drive-client/nxdrive/client/local_client.py
  nuxeo-drive-client/nxdrive/client/remote_file_system_client.py
  nuxeo-drive-client/nxdrive/engine/processor.py
  nuxeo-drive-client/tests/test_local_creations.py
Labels: improvement

#424 NXDRIVE-1128: Automatic update of translations from Crowdin
  nuxeo-drive-client/nxdrive/data/i18n/i18n-de.json
  nuxeo-drive-client/nxdrive/data/i18n/i18n-es-ES.json
  nuxeo-drive-client/nxdrive/data/i18n/i18n-fr.json
  nuxeo-drive-client/nxdrive/data/i18n/i18n-it.json
  nuxeo-drive-client/nxdrive/data/i18n/i18n-ja.json
  nuxeo-drive-client/nxdrive/data/i18n/i18n-nl.json
  nuxeo-drive-client/nxdrive/data/i18n/i18n-sv-SE.json
Labels: translations

#426 NXDRIVE-1144: Installer adjustments
  docs/changes.md
  ndrive.spec
  nuxeo-drive-client/nxdrive/commandline.py
  nuxeo-drive-client/nxdrive/options.py
  nuxeo-drive-client/nxdrive/utils.py
  tools/linux/debian.xml
  tools/release.sh
  tools/windows/deploy_jenkins_slave.ps1
Labels: bugfix
