Repository nuxeo/nuxeo-drive, pull requests merged in 2018-05, with the labels that each got.

#481 NXDRIVE-1137: Add a picture in the Windows installer
  tools/windows/setup.iss
  tools/windows/wizard.bmp
Labels: Windows

#483 NXDRIVE-903: Clean-up
  docs/technical_changes.md
  nxdrive/client/local_client.py
  nxdrive/commandline.py
  nxdrive/engine/dao/sqlite.py
  nxdrive/engine/engine.py
  nxdrive/engine/next/simple_watcher.py
  nxdrive/engine/processor.py
  nxdrive/engine/tracker.py
  nxdrive/engine/watcher/local_watcher.py
  nxdrive/engine/watcher/remote_watcher.py
  nxdrive/wui/application.py
  tests/common.py
  tests/mac_local_client.py
  tests/test_nxdrive_903.py
  tests/win_local_client.py
Labels: clean-up

#498 NXDRIVE-1128: Automatic update of translations from Crowdin (all)
  nxdrive/data/i18n/i18n-de.json
  nxdrive/data/i18n/i18n-es-ES.json
  nxdrive/data/i18n/i18n-fr.json
  nxdrive/data/i18n/i18n-he.json
  nxdrive/data/i18n/i18n-id.json
  nxdrive/data/i18n/i18n-it.json
  nxdrive/data/i18n/i18n-ja.json
  nxdrive/data/i18n/i18n-nl.json
  nxdrive/data/i18n/i18n-sv-SE.json
Labels: translations

#499 NXDRIVE-1068: Move proxy support to a dedicated module
  docs/changes.md
  docs/configuration.md
  docs/technical_changes.md
  nxdrive/client/proxy.py
  nxdrive/client/remote_client.py
  nxdrive/commandline.py
  nxdrive/engine/engine.py
  nxdrive/manager.py
  nxdrive/options.py
  nxdrive/utils.py
  nxdrive/wui/dialog.py
  nxdrive/wui/settings.py
  tests/test_local_move_and_rename.py
  tests/test_local_storage_issue.py
  tests/test_proxy.py
  tests/test_remote_move_and_rename.py
  tests/test_synchronization.py
  tests/test_utils.py
Labels: improvement, new-feature

#496 NXDRIVE-1201: Adapt Drive for new Trash API behavior
  docs/changes.md
  nxdrive/client/remote_client.py
  nxdrive/engine/processor.py
  tests/__init__.py
  tests/test_bulk_remote_changes.py
  tests/test_concurrent_synchronization.py
  tests/test_local_deletion.py
  tests/test_remote_deletion.py
Labels: new-feature
