Repository nuxeo/nuxeo-drive, pull requests merged in 2019-03, with the labels that each got.

#813 NXDRIVE-1221: Fix thread leaks
  LICENSE.txt
  docs/changes/4.1.0.md
  docs/tests.md
  nxdrive/direct_edit.py
  nxdrive/engine/engine.py
  nxdrive/engine/next/processor.py
  nxdrive/engine/processor.py
  nxdrive/engine/watcher/local_watcher.py
  nxdrive/engine/workers.py
  nxdrive/gui/api.py
  nxdrive/manager.py
  tests/functional/test_behavior.py
  tools/cleanup.sh
  tools/linux/resources/debian/compat
  tools/linux/resources/debian/copyright
  tools/linux/resources/debian/docs/ndrive.1
  tools/linux/resources/debian/docs/ndrive.pod
  tools/linux/resources/debian/nuxeo-drive-client.lintian-overrides
  tools/linux/resources/debian/nuxeo-drive-client.manpages
  tools/osx/background.xcf
  tools/osx/dmgbackground.png
  tools/osx/dmgbackground.svg
  tools/osx/generated_DS_Store
Labels: bugfix, clean-up

#815 Revert "Update sentry-sdk from 0.7.3 to 0.7.4"
  docs/changes/4.1.0.md
  requirements.txt
Labels: bug

#818 NXDRIVE-1563: Automatic update of translations from Crowdin
  nxdrive/data/i18n/i18n-de.json
  nxdrive/data/i18n/i18n-es-ES.json
  nxdrive/data/i18n/i18n-fr.json
  nxdrive/data/i18n/i18n-he.json
  nxdrive/data/i18n/i18n-id.json
  nxdrive/data/i18n/i18n-it.json
  nxdrive/data/i18n/i18n-ja.json
  nxdrive/data/i18n/i18n-nl.json
  nxdrive/data/i18n/i18n-sv-SE.json
Labels: translations

#819 NXDRIVE-1577: Fix Photoshop opened endlessly
  nxdrive/osi/darwin/files.py
Labels: bugfix

#817 NXDRIVE-1555: Handle bad remote changes values
  docs/changes/4.1.0.md
  nxdrive/engine/watcher/remote_watcher.py
  tests/old_functional/test_remote_changes.py
Labels: bugfix

#820 Revert "NXDRIVE-1564: Drop support for Nuxeo Platform 7.10"
  docs/changes/4.1.0.md
  docs/support.md
  tools/scripts/check_update_process.py
  tools/versions.py
Labels: doc

#822 NXDRIVE-1542: Unlock tests parallelization!
  docs/changes/4.1.0.md
  requirements.txt
  setup.cfg
  tests/__init__.py
  tests/conftest.py
  tests/functional/__init__.py
  tests/old_functional/__init__.py
  tests/old_functional/common.py
  tests/old_functional/local_client_windows.py
  tests/old_functional/test_bulk_remote_changes.py
  tests/old_functional/test_collection.py
  tests/old_functional/test_concurrent_synchronization.py
  tests/old_functional/test_conflicts.py
  tests/old_functional/test_copy.py
  tests/old_functional/test_direct_edit.py
  tests/old_functional/test_encoding.py
  tests/old_functional/test_group_changes.py
  tests/old_functional/test_ignored.py
  tests/old_functional/test_local_changes_when_offline.py
  tests/old_functional/test_local_client.py
  tests/old_functional/test_local_copy_paste.py
  tests/old_functional/test_local_creations.py
  tests/old_functional/test_local_deletion.py
  tests/old_functional/test_local_filter.py
  tests/old_functional/test_local_move_and_rename.py
  tests/old_functional/test_local_move_folders.py
  tests/old_functional/test_local_paste.py
  tests/old_functional/test_local_share_move_folders.py
  tests/old_functional/test_local_storage_issue.py
  tests/old_functional/test_long_path.py
  tests/old_functional/test_mac_local_client.py
  tests/old_functional/test_multiple_files.py
  tests/old_functional/test_nxdrive_903.py
  tests/old_functional/test_permission_hierarchy.py
  tests/old_functional/test_readonly.py
  tests/old_functional/test_reinit_database.py
  tests/old_functional/test_remote_changes.py
  tests/old_functional/test_remote_client.py
  tests/old_functional/test_remote_deletion.py
  tests/old_functional/test_remote_move_and_rename.py
  tests/old_functional/test_security_updates.py
  tests/old_functional/test_shared_folders.py
  tests/old_functional/test_special_characters.py
  tests/old_functional/test_sync_roots.py
  tests/old_functional/test_synchronization.py
  tests/old_functional/test_synchronization_dedup.py
  tests/old_functional/test_synchronization_suspend.py
  tests/old_functional/test_versioning.py
  tests/old_functional/test_volume.py
  tests/old_functional/test_watchers.py
  tests/unit/test_proxy.py
  tests/unit/test_report.py
  tests/utils.py
  tools/posix/deploy_jenkins_slave.sh
  tools/windows/deploy_jenkins_slave.ps1
Labels: improvement

#823 NXDRIVE-1542: The SENTRY_ENV envar is now mandatory
  docs/changes/4.1.0.md
  tests/functional/__init__.py
Labels: improvement

#825 NXDRIVE-1542: Several little bugfixes
  nxdrive/client/local_client.py
  tests/conftest.py
  tests/functional/test_tracker.py
  tests/old_functional/common.py
  tests/unit/test_utils.py
  tools/jenkins/tests.groovy
  tools/posix/deploy_jenkins_slave.sh
  tools/windows/deploy_jenkins_slave.ps1
Labels: bugfix, doc

#826 NXDRIVE-1559: Use separate prompts for downgrade in cases of incompatibility or wrong channel
  docs/changes/4.1.0.md
  nxdrive/data/i18n/i18n.json
  nxdrive/data/qml/Systray.qml
  nxdrive/gui/application.py
  nxdrive/manager.py
  nxdrive/updater/base.py
  nxdrive/updater/constants.py
  nxdrive/updater/utils.py
  tests/unit/test_updater.py
Labels: improvement

#829 NXDRIVE-1565: Tweak the Nuxeo instance to handle more connections
  ftest/custom/nuxeo.defaults
  tools/jenkins/tests.groovy
Labels: improvement

#830 Automatic update of translations from Crowdin
  nxdrive/data/i18n/i18n-de.json
  nxdrive/data/i18n/i18n-es-ES.json
  nxdrive/data/i18n/i18n-fr.json
  nxdrive/data/i18n/i18n-he.json
  nxdrive/data/i18n/i18n-id.json
  nxdrive/data/i18n/i18n-it.json
  nxdrive/data/i18n/i18n-ja.json
  nxdrive/data/i18n/i18n-nl.json
  nxdrive/data/i18n/i18n-sv-SE.json
Labels: translations

#831 NXDRIVE-1546: Filter out KeyboardInterrupt errors
  docs/changes/4.1.0.md
  tests/__init__.py
  tests/functional/__init__.py
  tests/old_functional/__init__.py
Labels: clean-up

#832 NXDRIVE-1556: Handle DB log config
  nxdrive/manager.py
Labels: bugfix

#828 NXDRIVE-1501: Prompt for confirmation when a user deletes a document locally
  docs/changes/4.1.0.md
  nxdrive/constants.py
  nxdrive/data/i18n/i18n.json
  nxdrive/data/qml/DeletionPopup.qml
  nxdrive/data/qml/GeneralTab.qml
  nxdrive/engine/dao/sqlite.py
  nxdrive/engine/engine.py
  nxdrive/engine/processor.py
  nxdrive/engine/watcher/local_watcher.py
  nxdrive/gui/api.py
  nxdrive/gui/application.py
  nxdrive/manager.py
  nxdrive/options.py
  tests/functional/conftest.py
  tests/old_functional/common.py
Labels: new-feature

#833 NXDRIVE-1589: Fix Adobe applications automatically started by Drive
  nxdrive/osi/darwin/files.py
Labels: bugfix, macOS

#835 NXDRIVE-1501: Automatic update of translations from Crowdin
  nxdrive/data/i18n/i18n-de.json
  nxdrive/data/i18n/i18n-es-ES.json
  nxdrive/data/i18n/i18n-fr.json
  nxdrive/data/i18n/i18n-he.json
  nxdrive/data/i18n/i18n-id.json
  nxdrive/data/i18n/i18n-it.json
  nxdrive/data/i18n/i18n-ja.json
  nxdrive/data/i18n/i18n-nl.json
  nxdrive/data/i18n/i18n-sv-SE.json
Labels: translations

#836 NXDRIVE-1542: Little improvements
  tests/old_functional/common.py
  tests/unit/test_options.py
Labels: improvement

#838 NXDRIVE-1574: DAO has no lock when Drive attempts to restore a db backup
  nxdrive/engine/dao/sqlite.py
  nxdrive/engine/processor.py
  tests/__init__.py
  tests/functional/test_db_backup.py
  tests/old_functional/__init__.py
  tests/old_functional/test_synchronization.py
Labels: bugfix

#839 NXDRIVE-1587: Do not call Manager.stop() when the server is not compa…
  docs/changes/4.1.0.md
  nxdrive/__main__.py
  nxdrive/data/i18n/i18n.json
  nxdrive/data/qml/DeletionPopup.qml
  nxdrive/data/qml/Systray.qml
  nxdrive/data/qml/SystrayMenu.qml
  nxdrive/gui/api.py
  nxdrive/gui/application.py
  nxdrive/manager.py
  nxdrive/updater/base.py
  nxdrive/utils.py
  requirements.txt
Labels: bugfix

#840 NXDRIVE-1595: Fix malformed SSL certificate retrieving
  docs/changes/4.1.0.md
  nxdrive/utils.py
  tests/unit/test_utils.py
Labels: Windows, bugfix

#843 Automatic update of translations from Crowdin (all)
  nxdrive/data/i18n/i18n-de.json
  nxdrive/data/i18n/i18n-es-ES.json
  nxdrive/data/i18n/i18n-fr.json
  nxdrive/data/i18n/i18n-he.json
  nxdrive/data/i18n/i18n-id.json
  nxdrive/data/i18n/i18n-it.json
  nxdrive/data/i18n/i18n-ja.json
  nxdrive/data/i18n/i18n-nl.json
  nxdrive/data/i18n/i18n-sv-SE.json
Labels: translations

#844 NXDRIVE-1588: Fix folders watch on Windows
  docs/changes/4.1.0.md
  nxdrive/osi/windows/extension.py
  nxdrive/osi/windows/windows.py
Labels: Windows, bugfix

#847 NXDRIVE-1594: Update sentences
  nxdrive/data/i18n/i18n.json
Labels: translations

#848 NXDRIVE-1598: Ensure the QLocalSocket is connected before disconnection
  docs/changes/4.1.0.md
  nxdrive/commandline.py
  nxdrive/gui/application.py
  nxdrive/osi/extension.py
Labels: bugfix

#849 NXDRIVE-1467: Build DLLs compatible with Win 7 and 10
  tools/windows/dll/x64/NuxeoDriveConflicted_x64.dll
  tools/windows/dll/x64/NuxeoDriveError_x64.dll
  tools/windows/dll/x64/NuxeoDriveLocked_x64.dll
  tools/windows/dll/x64/NuxeoDriveSynced_x64.dll
  tools/windows/dll/x64/NuxeoDriveSyncing_x64.dll
  tools/windows/dll/x64/NuxeoDriveUnsynced_x64.dll
  tools/windows/dll/x64/NuxeoDriveUtil_x64.dll
  tools/windows/dll/x86/NuxeoDriveConflicted_x86.dll
  tools/windows/dll/x86/NuxeoDriveError_x86.dll
  tools/windows/dll/x86/NuxeoDriveLocked_x86.dll
  tools/windows/dll/x86/NuxeoDriveSynced_x86.dll
  tools/windows/dll/x86/NuxeoDriveSyncing_x86.dll
  tools/windows/dll/x86/NuxeoDriveUnsynced_x86.dll
  tools/windows/dll/x86/NuxeoDriveUtil_x86.dll
Labels: Windows, improvement

#850 NXDRIVE-1501: Fix contentHeight of the popup
  nxdrive/data/qml/DeletionPopup.qml
Labels: bugfix

#853 Automatic update of translations from Crowdin (all)
  nxdrive/data/i18n/i18n-de.json
  nxdrive/data/i18n/i18n-es-ES.json
  nxdrive/data/i18n/i18n-he.json
  nxdrive/data/i18n/i18n-id.json
  nxdrive/data/i18n/i18n-it.json
  nxdrive/data/i18n/i18n-ja.json
  nxdrive/data/i18n/i18n-nl.json
  nxdrive/data/i18n/i18n-sv-SE.json
Labels: translations

#854 NXDRIVE-1573: Upgrade from Python 3.6.7 to 3.6.8
  docs/changes/4.1.1.md
  tools/posix/deploy_jenkins_slave.sh
  tools/windows/deploy_jenkins_slave.ps1
Labels: improvement

#845 NXDRIVE-1557: Display progress bars in the systray menu
  docs/changes/4.1.1.md
  nxdrive/__main__.py
  nxdrive/client/remote_client.py
  nxdrive/data/qml/Systray.qml
  nxdrive/data/qml/SystrayAction.qml
  nxdrive/data/qml/SystrayFile.qml
  nxdrive/direct_edit.py
  nxdrive/engine/activity.py
  nxdrive/engine/processor.py
  nxdrive/gui/api.py
  nxdrive/gui/application.py
  nxdrive/gui/view.py
  nxdrive/manager.py
  requirements.txt
Labels: improvement

#856 NXDRIVE-1607: Improve URLS computation
  docs/changes/4.1.1.md
  nxdrive/utils.py
  tests/unit/test_utils.py
Labels: improvement

#857 NXDRIVE-1608: Fix logging level setters
  docs/changes/4.1.1.md
  nxdrive/commandline.py
  nxdrive/logging_config.py
  nxdrive/manager.py
  nxdrive/options.py
  nxdrive/report.py
Labels: bugfix
