Repository nuxeo/nuxeo-drive, pull requests merged in 2019-01, with the labels that each got.

#738 NXDRIVE-1503: Fix test_collection.py when it fails early
  docs/changes/4.1.0.md
  tests/test_collection.py
Labels: bugfix

#737 NXDRIVE-1469: Display a message on forbidden DriveEdit action
  docs/changes/4.1.0.md
  nxdrive/client/remote_client.py
  nxdrive/data/i18n/i18n.json
  nxdrive/direct_edit.py
  nxdrive/exceptions.py
  nxdrive/notification.py
  tests/__init__.py
  tests/common.py
  tests/test_collection.py
  tests/test_concurrent_synchronization.py
  tests/test_direct_edit.py
  tests/test_group_changes.py
  tests/test_local_deletion.py
  tests/test_local_share_move_folders.py
  tests/test_permission_hierarchy.py
  tests/test_remote_deletion.py
  tests/test_remote_move_and_rename.py
  tests/test_security_updates.py
  tests/test_shared_folders.py
  tests/test_synchronization.py
Labels: improvement

#742 Automatic update of translations from Crowdin (fr)
  nxdrive/data/i18n/i18n-fr.json
Labels: translations

#743 NXDRIVE-1500: Fix type annotations
  nxdrive/__main__.py
Labels: bugfix

#744 NXDRIVE-1492: Access to the local socket is denied
  docs/changes/4.1.0.md
  nxdrive/commandline.py
  nxdrive/gui/application.py
Labels: bugfix

#746 NXDRIVE-1510: Handle PermissionError in get_open_files()
  docs/changes/4.1.0.md
  nxdrive/autolocker.py
  tests/test_autolock.py
Labels: bugfix

#753 NXDRIVE-1469: Automatic update of translations from Crowdin
  nxdrive/data/i18n/i18n-de.json
  nxdrive/data/i18n/i18n-es-ES.json
  nxdrive/data/i18n/i18n-fr.json
  nxdrive/data/i18n/i18n-he.json
  nxdrive/data/i18n/i18n-id.json
  nxdrive/data/i18n/i18n-it.json
  nxdrive/data/i18n/i18n-ja.json
  nxdrive/data/i18n/i18n-nl.json
  nxdrive/data/i18n/i18n-sv-SE.json
Labels: translations

#756 NXDRIVE-1497: Fix alert when a server is not responding
  docs/changes/4.1.0.md
  nxdrive/data/i18n/i18n.json
  nxdrive/gui/api.py
  nxdrive/gui/application.py
  nxdrive/manager.py
  nxdrive/updater/base.py
  nxdrive/updater/constants.py
  nxdrive/updater/utils.py
Labels: bugfix, improvement

#757 NXDRIVE-1497: Update test_updater.py
  tests/test_updater.py
Labels: bugfix

#759 NXDRIVE-1524: Fix EngineDef usage
  nxdrive/engine/dao/sqlite.py
  nxdrive/objects.py
Labels: bugfix

#760 NXDRIVE-1523: Handle paths with more than 143 chars on encrypted FS
  docs/changes/4.1.0.md
  nxdrive/client/local_client.py
  nxdrive/data/i18n/i18n.json
  nxdrive/engine/engine.py
  nxdrive/engine/processor.py
  nxdrive/notification.py
  tests/test_long_path.py
Labels: GNU/Linux, bugfix

#764 NXDRIVE-1529: Review behavior of Windows registry functions
  docs/changes/4.1.0.md
  nxdrive/osi/windows/registry.py
  tests/test_windows.py
Labels: Windows, improvement

#763 NXDRIVE-1519: Allow DirectEditing documents with the Folderish facet
  docs/changes/4.1.0.md
  nxdrive/objects.py
  tests/test_direct_edit.py
Labels: new-feature

#758 NXDRIVE-1522: Introduce DEPs :book:
  docs/changes/4.1.0.md
  docs/dep/0000-00 Template.md
  docs/dep/README.md
Labels: doc

#767 Automatic update of translations from Crowdin (all)
  nxdrive/data/i18n/i18n-de.json
  nxdrive/data/i18n/i18n-es-ES.json
  nxdrive/data/i18n/i18n-fr.json
  nxdrive/data/i18n/i18n-he.json
  nxdrive/data/i18n/i18n-id.json
  nxdrive/data/i18n/i18n-it.json
  nxdrive/data/i18n/i18n-ja.json
  nxdrive/data/i18n/i18n-nl.json
  nxdrive/data/i18n/i18n-sv-SE.json
Labels: translations

#769 NXDRIVE-1519: Fix AttributeError when file:content is set to None
  nxdrive/objects.py
Labels: bugfix

#770 NXDRIVE-1534: Do not consider HTTP timeouts as errors in the Remote W…
  docs/changes/4.1.0.md
  nxdrive/engine/watcher/remote_watcher.py
Labels: improvement
