Repository nuxeo/nuxeo-drive, pull requests merged in 2019-02, with the labels that each got.

#773 NXBT-2753: Use default system maven from brew on macOS
  tools/jenkins/tests-8.10.groovy
  tools/jenkins/tests.groovy
Labels: bugfix

#774 NXDRIVE-1531: Do not declare QApplication.notify()
  nxdrive/gui/application.py
Labels: bugfix

#778 Automatic update of translations from Crowdin (it)
  nxdrive/data/i18n/i18n-it.json
Labels: translations

#779 NXDRIVE-1539: Fix invalid credentials handling when polling for changes
  nxdrive/client/remote_client.py
  nxdrive/engine/watcher/remote_watcher.py
Labels: improvement

#780 NXDRIVE-1493: Add DirectEdit support for the Adobe Creative Suite
  docs/README.md
  docs/behaviors/Adobe Creative Suite.md
  docs/behaviors/README.md
  docs/changes/4.1.0.md
  nxdrive/autolocker.py
  nxdrive/direct_edit.py
  nxdrive/manager.py
  nxdrive/objects.py
  nxdrive/osi/__init__.py
  nxdrive/osi/darwin/darwin.py
  nxdrive/osi/darwin/files.py
  nxdrive/osi/linux/__init__.py
  nxdrive/osi/linux/files.py
  nxdrive/osi/linux/linux.py
  nxdrive/osi/windows/files.py
  nxdrive/osi/windows/windows.py
  nxdrive/utils.py
  requirements.txt
  tests/test_utils.py
Labels: Windows, macOS, new-feature

#781 NXDRIVE-1493: Fix type annotations
  nxdrive/manager.py
  nxdrive/osi/__init__.py
  nxdrive/osi/darwin/darwin.py
  nxdrive/osi/darwin/files.py
  nxdrive/osi/linux/files.py
  nxdrive/osi/linux/linux.py
  nxdrive/osi/windows/files.py
  nxdrive/osi/windows/windows.py
  nxdrive/utils.py
  tests/__init__.py
Labels: bugfix

#784 NXDRIVE-1543: Make LocalClient.exists() return False on any OSError
  docs/changes/4.1.0.md
  nxdrive/client/local_client.py
Labels: bugfix

#787 NXDRIVE-1551: Fix systray display on Windows 10
  docs/changes/4.1.0.md
  nxdrive/gui/application.py
Labels: Windows, bugfix

#786 NXDRIVE-1467: Automatic update of translations from Crowdin
  nxdrive/data/i18n/i18n-de.json
  nxdrive/data/i18n/i18n-es-ES.json
  nxdrive/data/i18n/i18n-fr.json
  nxdrive/data/i18n/i18n-he.json
  nxdrive/data/i18n/i18n-id.json
  nxdrive/data/i18n/i18n-it.json
  nxdrive/data/i18n/i18n-ja.json
  nxdrive/data/i18n/i18n-nl.json
  nxdrive/data/i18n/i18n-sv-SE.json
Labels: translations

#788 NXDRIVE-1484: Backup databases before exiting
  docs/changes/4.1.0.md
  nxdrive/engine/dao/sqlite.py
  nxdrive/engine/dao/utils.py
  nxdrive/engine/engine.py
  nxdrive/manager.py
  nxdrive/poll_workers.py
  tests/functional/test_db_backup.py
Labels: improvement

#790 NXDRIVE-1537: Automatic update of translations from Crowdin
  nxdrive/data/i18n/i18n-de.json
  nxdrive/data/i18n/i18n-es-ES.json
  nxdrive/data/i18n/i18n-fr.json
  nxdrive/data/i18n/i18n-he.json
  nxdrive/data/i18n/i18n-id.json
  nxdrive/data/i18n/i18n-it.json
  nxdrive/data/i18n/i18n-ja.json
  nxdrive/data/i18n/i18n-nl.json
  nxdrive/data/i18n/i18n-sv-SE.json
Labels: translations

#792 NXDRIVE-1390: Fix pytest 3.9 warnings that break tests
  docs/changes/4.1.0.md
  requirements-tests.txt
  tests/pytest_random.py
Labels: bugfix

#793 NXDRIVE-1554: Remove unused QtBluetooth dependency in Windows tests
  tools/windows/deploy_jenkins_slave.ps1
Labels: bugfix

#797 NXDRIVE-1540: Avoid renaming banned files
  docs/changes/4.1.0.md
  nxdrive/engine/watcher/local_watcher.py
Labels: bugfix

#798 NXDRIVE-1560: Use PyQt5-sip 4.19.13
  docs/changes/4.1.0.md
  requirements.txt
Labels: bugfix, dependencies

#801 NXDRIVE-1561: Display the fatal error screen only when necessary
  docs/changes/4.1.0.md
  nxdrive/__main__.py
Labels: bugfix

#802 NXDRIVE-1528: Allow errors window to be resized
  docs/changes/4.1.0.md
  nxdrive/data/i18n/i18n.json
  nxdrive/data/qml/AccountsTab.qml
  nxdrive/data/qml/Conflicts.qml
  nxdrive/data/qml/Main.qml
  nxdrive/data/qml/Settings.qml
  nxdrive/gui/application.py
Labels: improvement

#804 NXDRIVE-1564: Drop support for Nuxeo Platform 7.10
  docs/changes/4.1.0.md
  docs/support.md
  tools/scripts/check_update_process.py
  tools/versions.py
Labels: clean-up

#806 NXDRIVE-1528: Automatic update of translations from Crowdin (all)
  nxdrive/data/i18n/i18n-de.json
  nxdrive/data/i18n/i18n-es-ES.json
  nxdrive/data/i18n/i18n-fr.json
  nxdrive/data/i18n/i18n-he.json
  nxdrive/data/i18n/i18n-id.json
  nxdrive/data/i18n/i18n-it.json
  nxdrive/data/i18n/i18n-ja.json
  nxdrive/data/i18n/i18n-nl.json
  nxdrive/data/i18n/i18n-sv-SE.json
Labels: translations

#807 NXDRIVE-1468: Factorize FS decoration handling cross-platform
  docs/changes/4.1.0.md
  nxdrive/manager.py
  nxdrive/osi/__init__.py
  nxdrive/osi/darwin/darwin.py
  nxdrive/osi/darwin/extension.py
  nxdrive/osi/extension.py
  nxdrive/osi/windows/extension.py
  nxdrive/osi/windows/overlay.py
  nxdrive/osi/windows/windows.py
  tools/osx/drive/NuxeoFinderSync/FinderSync.swift
Labels: improvement

#808 NXDRIVE-1562: Handle MemoryError in get_open_files()
  docs/changes/4.1.0.md
  nxdrive/autolocker.py
Labels: bugfix

#809 NXDRIVE-1568: Fix authentication expired notification
  docs/changes/4.1.0.md
  nxdrive/gui/api.py
  nxdrive/notification.py
  nxdrive/osi/darwin/pyNotificationCenter.py
Labels: bugfix

#811 NXDRIVE-1567: Use UTF-8 as encoding when dumping a database
  docs/changes/4.1.0.md
  nxdrive/commandline.py
  nxdrive/engine/dao/utils.py
Labels: bugfix
