Repository nuxeo/nuxeo-drive, pull requests merged in 2019-06, with the labels that each got.

#957 NXDRIVE-1684: Display the file size in the systray
  docs/changes/4.1.4.md
  nxdrive/data/qml/SystrayFile.qml
  nxdrive/gui/view.py
  nxdrive/objects.py
  nxdrive/utils.py
  tests/unit/test_utils.py
Labels: improvement

#959 NXDRIVE-1671: Only cleanup well-formed folders in DirectEdit directory
  docs/changes/4.1.4.md
  nxdrive/constants.py
  nxdrive/direct_edit.py
  nxdrive/utils.py
  tests/functional/test_direct_edit.py
  tests/old_functional/test_direct_edit.py
  tests/unit/test_utils.py
Labels: bugfix

#960 NXDRIVE-1681: Make server URL and local folder clickable in the Accou…
  docs/changes/4.1.4.md
  nxdrive/data/qml/AccountsTab.qml
Labels: improvement

#961 NXDRIVE-1683: Display a notification when DirectEdit'ing an inexistan…
  docs/changes/4.1.4.md
  nxdrive/data/i18n/i18n.json
  nxdrive/direct_edit.py
  tests/functional/test_direct_edit.py
  tests/old_functional/test_direct_edit.py
Labels: bugfix

#962 NXDRIVE-1695: Fix conflict resolving regression
  docs/changes/4.1.4.md
  nxdrive/gui/application.py
  nxdrive/gui/view.py
Labels: bugfix

#963 NXDRIVE-1673: Use native dialog when Qt is unavailable (for the fatal…
  docs/changes/4.1.4.md
  nxdrive/__main__.py
  nxdrive/fatal_error.py
Labels: bugfix

#964 NXDRIVE-1683: Automatic update of translations from Crowdin
  nxdrive/data/i18n/i18n-de.json
  nxdrive/data/i18n/i18n-es-ES.json
  nxdrive/data/i18n/i18n-fr.json
  nxdrive/data/i18n/i18n-he.json
  nxdrive/data/i18n/i18n-id.json
  nxdrive/data/i18n/i18n-it.json
  nxdrive/data/i18n/i18n-ja.json
  nxdrive/data/i18n/i18n-nl.json
  nxdrive/data/i18n/i18n-sv-SE.json
Labels: translations

#965 NXDRIVE-1671: Fix and expand test_url_resolver()
  tests/functional/test_direct_edit.py
Labels: bugfix

#967 NXBT-2886: Avoid failure on archiving
  tools/jenkins/tests_os.groovy
Labels: bugfix

#940 NXDRIVE-1604: Enable to pause and resume uploads
  docs/changes/4.1.4.md
  docs/dep/2019-01 Generate a unique test environment during the setup.md
  docs/dep/2019-05 Enable pausing and resuming transfers.md
  nxdrive/client/local_client.py
  nxdrive/client/remote_client.py
  nxdrive/constants.py
  nxdrive/data/qml/Systray.qml
  nxdrive/data/qml/SystrayAction.qml
  nxdrive/data/qml/SystrayMenu.qml
  nxdrive/data/qml/SystrayTransfer.qml
  nxdrive/direct_edit.py
  nxdrive/engine/activity.py
  nxdrive/engine/dao/sqlite.py
  nxdrive/engine/engine.py
  nxdrive/engine/processor.py
  nxdrive/engine/tracker.py
  nxdrive/engine/watcher/local_watcher.py
  nxdrive/engine/watcher/remote_watcher.py
  nxdrive/engine/workers.py
  nxdrive/exceptions.py
  nxdrive/gui/api.py
  nxdrive/gui/application.py
  nxdrive/gui/folders_treeview.py
  nxdrive/gui/view.py
  nxdrive/manager.py
  nxdrive/objects.py
  nxdrive/utils.py
  requirements.txt
  tests/old_functional/common.py
  tests/unit/test_utils.py
Labels: new-feature

#966 NXDRIVE-1700: Review get_syncing_count()
  docs/changes/4.1.4.md
  nxdrive/engine/dao/sqlite.py
Labels: improvement

#969 NXDRIVE-1694: Add the SKIP envar to bypass specific actions
  docs/changes/4.1.4.md
  docs/deployment.md
  tools/posix/deploy_jenkins_slave.sh
  tools/windows/deploy_jenkins_slave.ps1
Labels: improvement

#970 NXDRIVE-1688: Do not display the update channel in the release notes …
  docs/changes/4.1.4.md
  nxdrive/data/i18n/i18n.json
  nxdrive/gui/application.py
Labels: improvement

#972 NXDRIVE-1688: Automatic update of translations from Crowdin
  nxdrive/data/i18n/i18n-de.json
  nxdrive/data/i18n/i18n-es-ES.json
  nxdrive/data/i18n/i18n-fr.json
  nxdrive/data/i18n/i18n-he.json
  nxdrive/data/i18n/i18n-id.json
  nxdrive/data/i18n/i18n-it.json
  nxdrive/data/i18n/i18n-ja.json
  nxdrive/data/i18n/i18n-nl.json
  nxdrive/data/i18n/i18n-sv-SE.json
Labels: translations

#973 NXDRIVE-1669: Force write of file to disk
  docs/changes/4.1.4.md
  nxdrive/client/local_client.py
  nxdrive/engine/dao/utils.py
  nxdrive/updater/base.py
Labels: improvement

#975 NXDRIVE-1703: Upgrade sentry-sdk to 0.9.0
  docs/changes/4.1.4.md
  ndrive.spec
  requirements.txt
Labels: improvement

#976 NXDRIVE-1694: Add SKIP=tests to run only code quality checks
  docs/deployment.md
  tools/posix/deploy_jenkins_slave.sh
  tools/windows/deploy_jenkins_slave.ps1
Labels: improvement

#980 NXDRIVE-1642: Fix renaming on Windows
  docs/changes/4.1.4.md
  nxdrive/client/local_client.py
  nxdrive/utils.py
  tests/unit/test_utils.py
Labels: bugfix

#983 NXDRIVE-1642: Remove old test
  tests/old_functional/test_special_characters.py
Labels: bugfix

#984 NXDRIVE-1698: Display the progress bar when resuming an upload
  docs/changes/4.1.4.md
  nxdrive/client/remote_client.py
Labels: bugfix

#985 Upgrade nuxeo from 2.1.0 to 2.1.1
  docs/changes/4.1.4.md
  requirements.txt
Labels: dependencies

#987 NXDRIVE-1691: Make DAO attributes public
  docs/changes/4.1.4.md
  nxdrive/autolocker.py
  nxdrive/client/remote_client.py
  nxdrive/direct_edit.py
  nxdrive/engine/dao/sqlite.py
  nxdrive/engine/engine.py
  nxdrive/engine/processor.py
  nxdrive/engine/queue_manager.py
  nxdrive/engine/watcher/local_watcher.py
  nxdrive/engine/watcher/remote_watcher.py
  nxdrive/engine/workers.py
  nxdrive/gui/api.py
  nxdrive/gui/application.py
  nxdrive/gui/folders_dialog.py
  nxdrive/manager.py
  nxdrive/notification.py
  nxdrive/osi/windows/extension.py
  nxdrive/poll_workers.py
  nxdrive/report.py
  tests/functional/conftest.py
  tests/old_functional/common.py
  tests/old_functional/test_concurrent_synchronization.py
  tests/old_functional/test_conflicts.py
  tests/old_functional/test_ignored.py
  tests/old_functional/test_local_creations.py
  tests/old_functional/test_local_filter.py
  tests/old_functional/test_local_move_and_rename.py
  tests/old_functional/test_local_move_folders.py
  tests/old_functional/test_local_storage_issue.py
  tests/old_functional/test_nxdrive_903.py
  tests/old_functional/test_permission_hierarchy.py
  tests/old_functional/test_readonly.py
  tests/old_functional/test_reinit_database.py
  tests/old_functional/test_remote_move_and_rename.py
  tests/old_functional/test_security_updates.py
  tests/old_functional/test_shared_folders.py
  tests/old_functional/test_synchronization.py
  tests/old_functional/test_synchronization_dedup.py
  tests/old_functional/test_synchronization_suspend.py
  tests/old_functional/test_transfer.py
  tests/old_functional/test_watchers.py
  tests/unit/test_manager_dao.py
Labels: clean-up

#986 NXDRIVE-980: Renaming files server-side to solve duplicate issues results in wrong local files count
  docs/changes/4.1.4.md
  nxdrive/engine/watcher/remote_watcher.py
  tests/old_functional/test_synchronization.py
Labels: bugfix

#991 NXDRIVE-1721: Fix get_timestamp_from_date() signature
  docs/changes/4.1.4.md
  nxdrive/utils.py
  tests/unit/test_utils.py
Labels: bugfix

#994 NXDRIVE-1726: Show Account setting at statup if there is no account
  docs/changes/4.1.4.md
  nxdrive/gui/application.py
Labels: improvement

#997 NXDRIVE-1727: Automatic update of translations from Crowdin
  nxdrive/data/i18n/i18n-de.json
  nxdrive/data/i18n/i18n-es-ES.json
  nxdrive/data/i18n/i18n-fr.json
  nxdrive/data/i18n/i18n-he.json
  nxdrive/data/i18n/i18n-id.json
  nxdrive/data/i18n/i18n-it.json
  nxdrive/data/i18n/i18n-ja.json
  nxdrive/data/i18n/i18n-nl.json
  nxdrive/data/i18n/i18n-sv-SE.json
Labels: translations

#999 NXDRIVE-1705: Add an option to remove local files when removing an account
  docs/changes/4.1.4.md
  nxdrive/data/i18n/i18n.json
  nxdrive/data/qml/AccountsTab.qml
  nxdrive/data/qml/ConfirmPopup.qml
  nxdrive/gui/api.py
  nxdrive/manager.py
  tests/old_functional/common.py
  tests/old_functional/test_readonly.py
Labels: improvement
