Repository nuxeo/nuxeo-drive, pull requests merged in 2019-04, with the labels that each got.

#862 NXDRIVE-1592: Fix the alpha cleanup script
  docs/changes/4.1.1.md
  tools/cleanup.sh
  tools/jenkins/cleanup.groovy
Labels: bugfix

#864 NXDRIVE-1612: [macOS] Improve running applications detection
  docs/changes/4.1.1.md
  nxdrive/osi/darwin/files.py
Labels: bugfix, macOS

#865 NXDRIVE-1614: Improve the Action class implementation
  docs/changes/4.1.1.md
  nxdrive/client/remote_client.py
  nxdrive/engine/activity.py
  nxdrive/gui/api.py
  nxdrive/gui/application.py
  tests/unit/test_action.py
Labels: bugfix, improvement

#861 NXDRIVE-1611: Add chunk upload options
  docs/changes/4.1.1.md
  docs/configuration.md
  nxdrive/client/remote_client.py
  nxdrive/options.py
  requirements.txt
Labels: improvement

#867 NXDRIVE-1593: Use java 11 for tests
  docs/changes/4.1.1.md
  ftest/pom-8.10.xml
  tools/jenkins/tests-8.10.groovy
  tools/jenkins/tests.groovy
Labels: improvement

#868 NXDRIVE-1571: Fix variable referenced before assignment in the Remote…
  docs/changes/4.1.1.md
  nxdrive/engine/watcher/remote_watcher.py
Labels: bugfix

#869 NXDRIVE-1610: Bump version to 4.1.2
  docs/changes.md
  docs/changes/4.0.3.md
  docs/changes/4.1.0.md
  docs/changes/4.1.1.md
  docs/changes/4.1.2.md
  nxdrive/__init__.py
Labels: Release

#870 NXDRIVE-1572: Add a button to select/unselect all roots
  docs/changes/4.1.2.md
  nxdrive/data/i18n/i18n.json
  nxdrive/gui/folders_dialog.py
  nxdrive/gui/folders_treeview.py
Labels: improvement

#871 NXDRIVE-1572: Hide the select/unselect button when no roots
  nxdrive/gui/folders_dialog.py
Labels: bugfix

#873 NXDRIVE-1590: [Windows] Disable FS decorators when testing
  docs/changes/4.1.2.md
  nxdrive/osi/windows/windows.py
  tests/__init__.py
Labels: improvement

#874 NXDRIVE-1620: [Windows] Cannot rename a freshly created file
  docs/changes/4.1.2.md
  nxdrive/client/remote_client.py
  requirements.txt
Labels: bugfix

#875 NXDRIVE-1622: Release 4.1.2
  docs/changes/4.1.2.md
Labels: Release

#876 NXDRIVE-1622: Bump version to 4.1.3
  docs/changes.md
  docs/changes/4.1.3.md
  nxdrive/__init__.py
Labels: Release

#878 NXDRIVE-1572: Automatic update of translations from Crowdin
  nxdrive/data/i18n/i18n-de.json
  nxdrive/data/i18n/i18n-es-ES.json
  nxdrive/data/i18n/i18n-fr.json
  nxdrive/data/i18n/i18n-he.json
  nxdrive/data/i18n/i18n-id.json
  nxdrive/data/i18n/i18n-it.json
  nxdrive/data/i18n/i18n-ja.json
  nxdrive/data/i18n/i18n-nl.json
  nxdrive/data/i18n/i18n-sv-SE.json
Labels: translations

#880 NXDRIVE-1580: When account is added, after filters are chosen, close t…
  docs/changes/4.1.3.md
  nxdrive/gui/api.py
  nxdrive/gui/application.py
Labels: improvement

#881 NXDRIVE-1624: Ensure the lock file integrity is correct
  docs/changes/4.1.3.md
  nxdrive/utils.py
  tests/unit/test_pid_lock_file.py
Labels: bugfix

#882 NXDRIVE-1635: Add "Version Added" in documentation parameters
  docs/changes/4.1.3.md
  docs/configuration.md
Labels: doc

#884 NXDRIVE-1636: Reduce ScrollDescendants calls for each folder
  docs/changes/4.1.3.md
  nxdrive/client/remote_client.py
  nxdrive/constants.py
  nxdrive/engine/watcher/remote_watcher.py
Labels: improvement

#883 NXDRIVE-1637: [macOS] Skip unsaved documents in Photoshop and Illustr…
  docs/changes/4.1.3.md
  nxdrive/osi/darwin/files.py
Labels: bugfix, macOS

#885 NXDRIVE-1277: Review objects state export
  docs/changes/4.1.3.md
  nxdrive/engine/engine.py
  nxdrive/engine/workers.py
  nxdrive/gui/api.py
  nxdrive/notification.py
  nxdrive/objects.py
  nxdrive/utils.py
  tests/functional/test_bind_server.py
  tests/old_functional/test_synchronization.py
  tests/unit/test_notification.py
Labels: improvement

#887 NXDRIVE-1618: Remove inexistant engines from the Manager engines list
  docs/changes/4.1.3.md
  nxdrive/gui/application.py
  nxdrive/manager.py
  tests/functional/test_behavior.py
Labels: bugfix, improvement

#888 NXDRIVE-1616: Prevent double lock when DirectEdit'ing a document
  docs/changes/4.1.3.md
  nxdrive/direct_edit.py
  nxdrive/exceptions.py
  tests/old_functional/test_direct_edit.py
Labels: bugfix

#886 NXDRIVE-1639: Do not allow DirectEdit on older versions of document
  docs/changes/4.1.3.md
  nxdrive/client/remote_client.py
  nxdrive/data/i18n/i18n.json
  nxdrive/direct_edit.py
  nxdrive/gui/application.py
  nxdrive/objects.py
Labels: bugfix

#891 NXDRIVE-1639: Automatic update of translations from Crowdin
  nxdrive/data/i18n/i18n-de.json
  nxdrive/data/i18n/i18n-es-ES.json
  nxdrive/data/i18n/i18n-fr.json
  nxdrive/data/i18n/i18n-he.json
  nxdrive/data/i18n/i18n-id.json
  nxdrive/data/i18n/i18n-it.json
  nxdrive/data/i18n/i18n-ja.json
  nxdrive/data/i18n/i18n-nl.json
  nxdrive/data/i18n/i18n-sv-SE.json
Labels: translations

#890 NXDRIVE-1633: Fix supported partition check
  docs/changes/4.1.3.md
  nxdrive/engine/engine.py
  nxdrive/gui/api.py
  nxdrive/manager.py
  nxdrive/osi/windows/windows.py
Labels: bugfix

#892 NXDRIVE-1605: Display the server name next to the username in the acc…
  docs/changes/4.1.3.md
  nxdrive/data/qml/AccountsComboBox.qml
  nxdrive/gui/view.py
Labels: improvement

#895 NXDRIVE-1639: Add DirectEdit on version test
  tests/old_functional/test_direct_edit.py
Labels: bugfix

#897 NXDRIVE-1641: Fix bind-server CLI without the --password argument
  docs/changes/4.1.3.md
  nxdrive/data/qml/AccountsTab.qml
  nxdrive/engine/engine.py
  nxdrive/gui/application.py
  nxdrive/manager.py
  nxdrive/objects.py
  nxdrive/options.py
  nxdrive/utils.py
Labels: bugfix

#898 NXDRIVE-1646: Fix SSH links in Jenkinsfiles
  docs/changes/4.1.3.md
  tools/jenkins/beta.groovy
  tools/jenkins/cleanup.groovy
Labels: bugfix

#899 NXDRIVE-1650: Lower logging of invalid SSL certificate in use
  docs/changes/4.1.3.md
  nxdrive/gui/api.py
Labels: clean-up

#902 NXDRIVE-1646: Remove 'ssh://' in URLs
  tools/jenkins/beta.groovy
  tools/jenkins/cleanup.groovy
Labels: bugfix

#901 NXDRIVE-1631: Automatic update of translations from Crowdin
  nxdrive/data/i18n/i18n-de.json
  nxdrive/data/i18n/i18n-es-ES.json
  nxdrive/data/i18n/i18n-fr.json
  nxdrive/data/i18n/i18n-he.json
  nxdrive/data/i18n/i18n-id.json
  nxdrive/data/i18n/i18n-it.json
  nxdrive/data/i18n/i18n-ja.json
  nxdrive/data/i18n/i18n-nl.json
  nxdrive/data/i18n/i18n-sv-SE.json
Labels: translations

#903 NXDRIVE-1646: Final patch to make the cleanup effective
  tools/cleanup.sh
Labels: bugfix

#905 NXDRIVE-1646: Update all shebangs to use bash
  tools/cleanup.sh
  tools/deploy.sh
  tools/qa.sh
  tools/release.sh
Labels: bugfix

#906 NXDRIVE-1623: Automatic update of translations from Crowdin
  nxdrive/data/i18n/i18n-de.json
  nxdrive/data/i18n/i18n-es-ES.json
  nxdrive/data/i18n/i18n-fr.json
  nxdrive/data/i18n/i18n-he.json
  nxdrive/data/i18n/i18n-id.json
  nxdrive/data/i18n/i18n-it.json
  nxdrive/data/i18n/i18n-ja.json
  nxdrive/data/i18n/i18n-nl.json
  nxdrive/data/i18n/i18n-sv-SE.json
Labels: translations

#907 NXDRIVE-1654: Improve the support documentation
  docs/changes/4.1.3.md
  docs/support.md
Labels: doc, improvement

#908 NXDRIVE-1362: Reduce the complexity of LocalWatcher._handle_watchdog_…
  docs/changes/4.1.3.md
  nxdrive/client/local_client.py
  nxdrive/engine/watcher/local_watcher.py
Labels: improvement

#909 NXDRIVE-1353: When 'invalid credentials' occurs, display a direct link to log in in the account settings
  docs/changes/4.1.3.md
  nxdrive/data/qml/AccountsTab.qml
  nxdrive/engine/engine.py
  nxdrive/gui/view.py
Labels: improvement

#910 NXDRIVE-1658: Reduce the complexity of abstract models data getter
  nxdrive/data/qml/AccountsTab.qml
  nxdrive/data/qml/Systray.qml
  nxdrive/engine/engine.py
  nxdrive/gui/view.py
Labels: improvement

#911 NXDRIVE-1648: Removed whitespace characters from URLs
  docs/changes/4.1.3.md
  nxdrive/utils.py
  tests/unit/test_utils.py
Labels: bugfix

#912 NXDRIVE-1655: Initialize Remote upon connection
  docs/changes/4.1.3.md
  nxdrive/data/i18n/i18n.json
  nxdrive/data/icons/loader.gif
  nxdrive/data/icons/overlay/win32/ModifiedIcon.ico
  nxdrive/data/icons/overlay/win32/NormalIcon.ico
  nxdrive/engine/engine.py
  nxdrive/gui/folders_dialog.py
  nxdrive/gui/folders_treeview.py
Labels: bugfix

#914 NXDRIVE-1647: Check HTTPS when starting an engine
  docs/changes/4.1.3.md
  nxdrive/engine/engine.py
Labels: bugfix
