Repository nuxeo/nuxeo-drive, pull requests merged in 2019-05, with the labels that each got.

#918 NXDRIVE-1655: Automatic update of translations from Crowdin
  nxdrive/data/i18n/i18n-de.json
  nxdrive/data/i18n/i18n-es-ES.json
  nxdrive/data/i18n/i18n-fr.json
  nxdrive/data/i18n/i18n-he.json
  nxdrive/data/i18n/i18n-id.json
  nxdrive/data/i18n/i18n-it.json
  nxdrive/data/i18n/i18n-ja.json
  nxdrive/data/i18n/i18n-nl.json
  nxdrive/data/i18n/i18n-sv-SE.json
Labels: translations

#920 NXDRIVE-1643: [Windows] Switch and radio button text is truncated with ellipsis with zoom at 175%
  docs/changes/4.1.3.md
  nxdrive/data/qml/NuxeoRadioButton.qml
  nxdrive/data/qml/NuxeoSwitch.qml
Labels: bugfix

#921 NXDRIVE-1661: Version compatibility function doesn't return the right result
  docs/changes/4.1.3.md
  nxdrive/updater/utils.py
Labels: bugfix

#922 NXDRIVE-1662: [macOS] Handle NSRangeException while fetching opened d…
  docs/changes/4.1.3.md
  nxdrive/osi/darwin/files.py
Labels: bugfix, macOS

#923 NXDRIVE-1663: [Windows] Lower logging level of WindowsIntegration._cr…
  docs/changes/4.1.3.md
  nxdrive/osi/windows/windows.py
Labels: Windows, bugfix

#924 NXDRIVE-1664: Add OS and Python versions to Sentry events
  docs/changes/4.1.3.md
  nxdrive/__main__.py
  nxdrive/engine/tracker.py
  nxdrive/utils.py
  tests/__init__.py
  tests/unit/test_utils.py
Labels: improvement

#926 NXDRIVE-1575: Add a link to the update site on the fatal error window
  docs/changes/4.1.3.md
  nxdrive/__main__.py
  nxdrive/data/i18n/i18n.json
Labels: improvement

#925 NXDRIVE-1148: Better handle no space left on the device
  docs/changes/4.1.3.md
  nxdrive/constants.py
  nxdrive/engine/dao/sqlite.py
  nxdrive/engine/processor.py
  nxdrive/gui/application.py
  nxdrive/manager.py
  nxdrive/osi/windows/windows.py
  nxdrive/updater/base.py
  tests/old_functional/test_local_storage_issue.py
Labels: bug

#929 NXDRIVE-1657: Automatic update of translations from Crowdin
  nxdrive/data/i18n/i18n-de.json
  nxdrive/data/i18n/i18n-es-ES.json
  nxdrive/data/i18n/i18n-fr.json
  nxdrive/data/i18n/i18n-he.json
  nxdrive/data/i18n/i18n-id.json
  nxdrive/data/i18n/i18n-it.json
  nxdrive/data/i18n/i18n-ja.json
  nxdrive/data/i18n/i18n-nl.json
  nxdrive/data/i18n/i18n-sv-SE.json
Labels: translations

#930 NXDRIVE-1148: Fix test_synchronize_no_space_left_on_device()
  nxdrive/engine/processor.py
  tests/old_functional/test_local_storage_issue.py
Labels: bugfix

#931 NXDRIVE-1575: Automatic update of translations from Crowdin
  nxdrive/data/i18n/i18n-de.json
  nxdrive/data/i18n/i18n-es-ES.json
  nxdrive/data/i18n/i18n-fr.json
  nxdrive/data/i18n/i18n-he.json
  nxdrive/data/i18n/i18n-id.json
  nxdrive/data/i18n/i18n-it.json
  nxdrive/data/i18n/i18n-ja.json
  nxdrive/data/i18n/i18n-nl.json
  nxdrive/data/i18n/i18n-sv-SE.json
Labels: translations

#932 NXDRIVE-1649: Review connection errors handling and logging
  docs/changes/4.1.3.md
  nxdrive/constants.py
  nxdrive/direct_edit.py
  nxdrive/engine/engine.py
  nxdrive/engine/processor.py
  nxdrive/engine/watcher/remote_watcher.py
  nxdrive/gui/api.py
  nxdrive/manager.py
  nxdrive/updater/base.py
Labels: bugfix

#935 NXDRIVE-1645: Fix bind-server CLI with bad --password value
  docs/changes/4.1.3.md
  nxdrive/client/remote_client.py
  nxdrive/engine/engine.py
  tests/integration/windows/test_cli_sub_command.py
Labels: bugfix

#936 NXDRIVE-1615: Use time.monotonic() in the RemoteWatcher
  nxdrive/engine/engine.py
  nxdrive/engine/watcher/remote_watcher.py
Labels: improvement

#941 NXBT-2866: Make separate test jobs for each OS for Nuxeo Drive
  nxdrive/engine/engine.py
  nxdrive/engine/watcher/remote_watcher.py
  setup.cfg
  tests/unit/test_utils.py
  tools/jenkins/tests.groovy
  tools/jenkins/tests_os.groovy
  tools/qa.sh
Labels: improvement

#943 NXDRIVE-1672: Ensure Application.update_status() is passed an Engine
  docs/changes/4.1.3.md
  nxdrive/gui/application.py
Labels: bugfix

#944 NXDRIVE-1675: Catch MemoryError in FileInfo.get_digest()
  docs/changes/4.1.3.md
  nxdrive/client/local_client.py
Labels: bugfix

#946 NXDRIVE-1251: Use the token everywhere
  docs/changes/4.1.3.md
  nxdrive/engine/engine.py
  tests/conftest.py
Labels: clean-up

#948 NXDRIVE-1676: Copy/overwrite db backup files instead of dumping/reading them
  docs/changes/4.1.3.md
  nxdrive/engine/dao/utils.py
Labels: bugfix

#951 NXDRIVE-1626: Release 4.1.3
  docs/changes/4.1.3.md
Labels: Release

#952 NXDRIVE-1626: Bump version to 4.1.4
  docs/changes.md
  docs/changes/4.1.4.md
  nxdrive/__init__.py
Labels: Release

#953 NXDRIVE-1660: Cannot rename root at the top level folder
  docs/changes/4.1.4.md
  nxdrive/client/remote_client.py
Labels: bugfix

#954 NXDRIVE-695: File is not deleted on the server when the parent folder is renamed, while offline
  nxdrive/engine/blacklist_queue.py
  nxdrive/engine/dao/sqlite.py
  nxdrive/engine/engine.py
  nxdrive/engine/watcher/local_watcher.py
  nxdrive/engine/watcher/remote_watcher.py
  tests/old_functional/test_synchronization_suspend.py
  tests/unit/test_blacklist_queue.py
Labels: Windows, bugfix, macOS

#955 NXDRIVE-695: Add the changelog entry
  docs/changes/4.1.4.md
Labels: doc
