Repository nuxeo/nuxeo-drive, pull requests merged in 2020-10, with the labels that each got.

#2061 NXDRIVE-2311: Add an option to control doc types where Direct Transfe…
  docs/changes/4.4.6.md
  docs/configuration.md
  nxdrive/gui/folders_model.py
  nxdrive/options.py
Labels: new-feature

#2068 NXDRIVE-2318: Sync the documentation between that repository and doc.…
  docs/changes/4.4.6.md
  docs/configuration.md
Labels: doc, improvement

#2070 NXDRIVE-2323: Add LOG_EVERYTHING envar to ... log everything
  docs/changes/4.4.6.md
  nxdrive/logging_config.py
  tools/skiplist.py
Labels: improvement

#2071 NXDRIVE-2322: Do not retry a HTTP call that failed on 500 error
  docs/changes/4.4.6.md
  nxdrive/client/remote_client.py
Labels: bugfix

#2072 NXDRIVE-2324: Fix the transfer progression reset if it was paused at …
  docs/changes/4.4.6.md
  nxdrive/client/uploader/__init__.py
  nxdrive/engine/dao/sqlite.py
  nxdrive/objects.py
Labels: bugfix

#2075 NXDRIVE-2325: Save the upload state when it is completed on the server
  docs/changes/4.4.6.md
  nxdrive/client/uploader/__init__.py
Labels: bugfix, improvement

#2079 NXDRIVE-2326: Fix test test_get_metadata_infos()
  docs/changes/4.4.6.md
  tests/old_functional/test_context_menu.py
Labels: bugfix, tests

#2084 NXDRIVE-2331: Check for ignored patterns against lowercased names
  docs/changes/4.4.6.md
  nxdrive/utils.py
  tests/unit/test_utils.py
  tools/deps/requirements-tests.txt
Labels: bugfix

#2086 NXDRIVE-2336: Fix mypy issues following the update to version 0.790
  docs/changes/4.4.6.md
  mypy.ini
  nxdrive/osi/windows/registry.py
Labels: bugfix

#2089 NXDRIVE-2339: Tell test_proxy.py to use a temporary folder instead of…
  .gitignore
  docs/changes/4.4.6.md
  tests/unit/test_proxy.py
Labels: bugfix, clean-up, tests

#2090 NXDRIVE-2338: Enable performance monitoring on Sentry
  docs/changes/4.4.6.md
  nxdrive/__main__.py
Labels: new-feature

#2092 NXDRIVE-2325: Refactor the upload flow
  docs/changes/4.4.6.md
  nxdrive/client/uploader/__init__.py
  nxdrive/engine/dao/sqlite.py
  nxdrive/objects.py
  tools/skiplist.py
Labels: bugfix, improvement

#2094 NXDRIVE-2342: Fix an implicit int -> float conversion deprecation war…
  docs/changes/4.4.6.md
  nxdrive/gui/application.py
Labels: bugfix

#2098 NXDRIVE-2345: Fix test_site_update_url()
  docs/changes/4.4.6.md
  tests/unit/test_options.py
Labels: bugfix, tests

#2100 NXDRIVE-2342: Fix an implicit int -> float conversion deprecation wa…
  nxdrive/updater/base.py
Labels: bugfix

#2099 NXDRIVE-2309: Fix migration to version 16
  nxdrive/engine/dao/sqlite.py
  tests/resources/databases/engine_migration_16.db
  tests/unit/test_engine_dao.py
Labels: bugfix

#2105 NXDRIVE-2344: Move most of LocalClient tests from functional to unit
  tests/functional/test_local_client.py
  tests/unit/test_local_client.py
Labels: improvement, tests

#2106 NXDRIVE-2347: Fix packaging following the sentry-sdk upgrade to 0.19.0
  docs/changes/4.4.6.md
  nxdrive/__main__.py
Labels: Release, bugfix

#2107 NXDRIVE-2346: Link to the current OS installer in the fatal error window
  docs/changes/4.4.6.md
  nxdrive/fatal_error.py
Labels: bugfix

#2108 NXDRIVE-2348: Fix test_updater.py
  docs/changes/4.4.6.md
  nxdrive/updater/base.py
  tests/functional/test_updater.py
Labels: bugfix, tests

#2109 NXDRIVE-2337: Use Options.max_errors for the retry count
  docs/changes/4.4.6.md
  nxdrive/direct_edit.py
  nxdrive/engine/queue_manager.py
  tests/old_functional/test_direct_edit.py
Labels: improvement

#2110 NXDRIVE-2349: Fix a QML margin in the account addition
  docs/changes/4.4.6.md
  nxdrive/data/qml/NewAccountPopup.qml
Labels: QML, bugfix

#2113 NXDRIVE-1718: Add checksums for typed-ast on Python 3.8
  tools/deps/requirements-tests.txt
Labels: QA/CI, bugfix

#2114 NXDRIVE-2353: Fix the window centering for multi-screen setup
  docs/changes/4.4.6.md
  nxdrive/gui/application.py
Labels: bugfix

#2111 NXDRIVE-2309: Update view for migrated sessions
  docs/changes/4.4.6.md
  nxdrive/data/i18n/i18n.json
  nxdrive/data/qml/SessionItem.qml
  nxdrive/engine/dao/sqlite.py
  nxdrive/gui/view.py
  nxdrive/objects.py
  tests/unit/test_engine_dao.py
Labels: QML, improvement

#2123 NXDRIVE-2359: Improve question message boxes rendering
  docs/changes/4.4.6.md
  nxdrive/data/i18n/i18n.json
  nxdrive/gui/api.py
  nxdrive/gui/application.py
Labels: improvement

#2127 NXDRIVE-2360: [GNU/Linux] Do not spawn a process for doing a simple c…
  docs/changes/4.4.6.md
  nxdrive/updater/linux.py
  tools/scripts/check_update_process.py
Labels: GNU/Linux, improvement

#2131 NXDRIVE-2361: Language aware diff headers
  .gitattributes
  docs/changes/4.4.6.md
Labels: improvement

#2133 NXDRIVE-2359: Use the icon argument in Application._root_moved()
  nxdrive/gui/application.py
Labels: clean-up

#2135 NXDRIVE-2309: [Direct Transfer] Show original planned files count in Completed sessions tab
  docs/changes/4.4.6.md
  nxdrive/engine/dao/sqlite.py
  nxdrive/engine/engine.py
  nxdrive/gui/application.py
  nxdrive/gui/view.py
  nxdrive/objects.py
  tests/old_functional/test_direct_transfer.py
  tests/unit/test_engine_dao.py
Labels: improvement

#2137 NXDRIVE-2309: Fix the session status not updated when hot changing th…
  nxdrive/data/qml/SessionItem.qml
Labels: QML, bugfix

#2138 NXDRIVE-2309: [Direct Transfer] Optimize pause_session() SQL request
  nxdrive/engine/dao/sqlite.py
Labels: improvement

#2139 NXDRIVE-2309: [Direct Transfer] Reworked the tab names
  nxdrive/data/i18n/i18n.json
  nxdrive/data/qml/DirectTransfer.qml
Labels: QML, improvement

#2142 NXDRIVE-2368: Bump the chunk_limit upper limit from 20 MiB to 5120 Mi…
  docs/changes/4.4.6.md
  docs/configuration.md
  nxdrive/options.py
  tests/unit/test_options.py
Labels: improvement

#2149 NXDRIVE-2341: [Direct Transfer] Non-chunked uploads must be put in pause when the session is paused
  docs/changes/4.4.6.md
  nxdrive/client/uploader/__init__.py
  nxdrive/client/uploader/direct_transfer.py
  nxdrive/engine/processor.py
  tests/old_functional/test_direct_transfer.py
Labels: bugfix

#2155 NXDRIVE-2370: Allow dependabot to check GitHub actions monthly
  .github/dependabot.yml
  docs/changes/4.4.6.md
Labels: QA/CI, improvement

#2159 NXDRIVE-2370: Use custom labels for PRs
  .github/dependabot.yml
Labels: QA/CI, improvement

#2151 NXDRIVE-2309: [Direct Transfer] Optimize resume_session() and cancel_session() SQL requests
  docs/changes/4.4.6.md
  nxdrive/engine/dao/sqlite.py
  nxdrive/engine/engine.py
  tests/old_functional/test_direct_transfer.py
Labels: improvement
