Repository nuxeo/nuxeo-drive, pull requests merged in 2020-11, with the labels that each got.

#2162 NXDRIVE-2111: Use GitHub Actions to run integration tests
  .github/workflows/integration_tests.yml
  docs/changes/4.4.6.md
  tools/posix/deploy_ci_agent.sh
  tools/windows/deploy_ci_agent.ps1
Labels: Windows, new-feature, tests

#2163 NXDRIVE-2071: Remove functional tests from the old QA runs
  tools/posix/deploy_ci_agent.sh
  tools/windows/deploy_ci_agent.ps1
Labels: QA/CI, clean-up

#2164 NXDRIVE-2377: Force database commit before application exit
  docs/changes/4.4.6.md
  nxdrive/engine/dao/sqlite.py
  nxdrive/report.py
Labels: improvement

#2165 NXDRIVE-2309: Fix a SQL syntax error
  nxdrive/engine/dao/sqlite.py
Labels: bugfix

#2160 NXDRIVE-2309: [Direct Transfer] Fix multiple non-chunked uploads pause and cancel
  docs/changes/4.4.6.md
  nxdrive/client/uploader/__init__.py
  nxdrive/client/uploader/direct_transfer.py
  nxdrive/data/qml/SessionItem.qml
  nxdrive/engine/dao/sqlite.py
  nxdrive/engine/processor.py
  nxdrive/exceptions.py
Labels: bugfix

#2173 NXDRIVE-2385: Ignore Arabic translations until fully ready
  docs/changes/4.4.6.md
  nxdrive/translator.py
  tests/unit/test_translator.py
Labels: improvement

#2171 NXDRIVE-2380: Clean-up mimetype code
  docs/changes/4.4.6.md
  nxdrive/client/remote_client.py
  nxdrive/client/uploader/__init__.py
  nxdrive/client/uploader/direct_transfer.py
  nxdrive/client/uploader/sync.py
  nxdrive/direct_edit.py
  nxdrive/engine/watcher/remote_watcher.py
  nxdrive/objects.py
  tests/old_functional/__init__.py
  tests/old_functional/test_remote_client.py
Labels: improvement

#2175 NXDRIVE-2387: Migrate some old functional tests to functional
  .github/workflows/functional_tests.yml
  tests/functional/test_context_menu.py
  tests/old_functional/test_context_menu.py
  tox.ini
Labels: improvement, tests

#2177 NXDRIVE-2389: Update Qt Quick Controls version for PyQt 5.15
  docs/changes/4.4.6.md
  nxdrive/data/qml/AboutTab.qml
  nxdrive/data/qml/AccountsComboBox.qml
  nxdrive/data/qml/AccountsTab.qml
  nxdrive/data/qml/Alert.qml
  nxdrive/data/qml/ChannelPopup.qml
  nxdrive/data/qml/ConfirmPopup.qml
  nxdrive/data/qml/Conflicts.qml
  nxdrive/data/qml/DeletionPopup.qml
  nxdrive/data/qml/DirectTransfer.qml
  nxdrive/data/qml/FeaturesTab.qml
  nxdrive/data/qml/FileCard.qml
  nxdrive/data/qml/GPL.txt
  nxdrive/data/qml/GeneralTab.qml
  nxdrive/data/qml/HorizontalSeparator.qml
  nxdrive/data/qml/HoverRectangle.qml
  nxdrive/data/qml/IconLabel.qml
  nxdrive/data/qml/IconLink.qml
  nxdrive/data/qml/Link.qml
  nxdrive/data/qml/LogLevelPopup.qml
  nxdrive/data/qml/Main.qml
  nxdrive/data/qml/NewAccountPopup.qml
  nxdrive/data/qml/NuxeoButton.qml
  nxdrive/data/qml/NuxeoCheckBox.qml
  nxdrive/data/qml/NuxeoComboBox.qml
  nxdrive/data/qml/NuxeoInput.qml
  nxdrive/data/qml/NuxeoPopup.qml
  nxdrive/data/qml/NuxeoProgressBar.qml
  nxdrive/data/qml/NuxeoRadioButton.qml
  nxdrive/data/qml/NuxeoSwitch.qml
  nxdrive/data/qml/NuxeoToolTip.qml
  nxdrive/data/qml/PauseButton.qml
  nxdrive/data/qml/ProxyPopup.qml
  nxdrive/data/qml/RectangleTooltip.qml
  nxdrive/data/qml/ScaledText.qml
  nxdrive/data/qml/SelectableText.qml
  nxdrive/data/qml/SessionItem.qml
  nxdrive/data/qml/Settings.qml
  nxdrive/data/qml/SettingsTab.qml
  nxdrive/data/qml/ShadowRectangle.qml
  nxdrive/data/qml/Systray.qml
  nxdrive/data/qml/SystrayFile.qml
  nxdrive/data/qml/SystrayMenu.qml
  nxdrive/data/qml/SystrayMenuItem.qml
  nxdrive/data/qml/SystrayStatus.qml
  nxdrive/data/qml/SystrayTransfer.qml
  nxdrive/data/qml/TransferItem.qml
Labels: QML, improvement

#2178 NXDRIVE-2390: Improve the final package clean-up script
  docs/changes/4.4.6.md
  tools/cleanup_application_tree.py
Labels: improvement, macOS

#2179 NXDRIVE-2391: [macOS] Add required entitlement for Apple events
  docs/changes/4.4.6.md
  tools/osx/entitlements.plist
Labels: improvement, macOS

#2180 NXDRIVE-2270: [macOS] Big Sur support
  docs/changes/4.4.6.md
  nxdrive/__main__.py
Labels: bugfix, macOS

#2176 NXDRIVE-2379: Review how the GUI is repainted to fix a crash
  docs/changes/4.4.6.md
  nxdrive/constants.py
  nxdrive/data/qml/DirectTransfer.qml
  nxdrive/data/qml/SessionItem.qml
  nxdrive/data/qml/TransferItem.qml
  nxdrive/gui/api.py
  nxdrive/gui/application.py
  nxdrive/gui/view.py
  tools/skiplist.py
Labels: QML, bugfix

#2183 NXDRIVE-2387: Migrate some tests from test_remote_changes.py
  tests/functional/test_remote_changes.py
  tests/old_functional/test_remote_changes.py
Labels: improvement, tests

#2184 NXDRIVE-2395: [Windows] Upgrade Inno Setup from 6.0.5 to 6.1.2
  .travis.yml
  docs/changes/4.4.6.md
  docs/support.md
  tools/windows/setup-addons.iss
  tools/windows/setup-common.iss
Labels: Windows, improvement

#2185 NXDRIVE-2395: Update the documentation
  docs/deployment.md
Labels: doc

#2186 NXDRIVE-2396: Switch to the new Dependabot config file
  .github/dependabot.yml
  dependabot/config.yml
  docs/changes/4.4.6.md
Labels: QA/CI

#2193 NXDRIVE-2397: Small improvement for non-chunked uploads
  docs/changes/4.4.6.md
  nxdrive/client/uploader/__init__.py
Labels: improvement

#2195 NXDRIVE-2398: Upgrade PyInstaller to 4.1
  docs/changes/4.4.6.md
  ndrive.spec
  tools/deps/pyinstaller-41237b1.zip
  tools/deps/requirements-dev.txt
  tools/posix/deploy_ci_agent.sh
Labels: Release, bugfix, improvement

#2194 NXDRIVE-2312: Upgrade Python from 3.7.9 to 3.8.6
  .github/workflows/dead_code.yml
  .github/workflows/functional_tests.yml
  .github/workflows/integration_tests.yml
  .github/workflows/lint.yml
  .github/workflows/spell.yml
  .github/workflows/style.yml
  .github/workflows/translations.yml
  .github/workflows/types.yml
  .github/workflows/unit_tests.yml
  docs/changes/4.4.6.md
  docs/deployment.md
  docs/gnu_linux.md
  docs/support.md
  nxdrive/__main__.py
  nxdrive/utils.py
  tests/__init__.py
  tools/deps/requirements-tests.txt
  tools/linux/travis.sh
  tools/posix/deploy_ci_agent.sh
  tools/windows/deploy_ci_agent.ps1
Labels: QA/CI, improvement

#2196 NXDRIVE-1724: Use the missing_ok keyword argument for unlink()
  docs/changes/4.4.6.md
  nxdrive/client/local/base.py
  nxdrive/client/local/darwin.py
  nxdrive/client/local/windows.py
  nxdrive/direct_edit.py
  nxdrive/engine/dao/sqlite.py
  nxdrive/engine/dao/utils.py
  nxdrive/engine/engine.py
  nxdrive/osi/windows/windows.py
  nxdrive/utils.py
  tests/functional/test_db_backup.py
  tests/unit/test_commandline.py
  tests/unit/test_pid_lock_file.py
Labels: improvement

#2199 NXDRIVE-2396: More frequent checks for GitHub Actions
  .github/dependabot.yml
Labels: QA/CI

#2205 NXDRIVE-2401: Upgrade the Docker build workflow to the new action ver…
  .github/workflows/docker_build.yml
  docs/changes/4.4.6.md
Labels: GNU/Linux, QA/CI, bugfix

#2224 NXDRIVE-2380: [Direct Edit] Fix a regression when the provided digest…
  nxdrive/objects.py
  tests/old_functional/test_direct_edit.py
Labels: bugfix

#2225 NXDRIVE-2313: Update the version number
  docs/changes.md
  docs/changes/4.5.0.md
  docs/configuration.md
  nxdrive/__init__.py
Labels: doc

#2234 NXDRIVE-2384: [Direct Edit] Remove usage of the deprecated applyVersi…
  docs/changes/4.5.0.md
  nxdrive/direct_edit.py
Labels: clean-up

#2235 NXDRIVE-2313: Update the version number in support.md
  docs/support.md
Labels: doc

#2239 NXDRIVE-2412: Clicking on pause and resume make it restart from the b…
  nxdrive/client/uploader/__init__.py
Labels: bugfix

#2240 NXDRIVE-2416: Update the Direct Transfer feature decription
  docs/changes/4.5.0.md
  nxdrive/data/i18n/i18n.json
Labels: improvement

#2244 NXDRIVE-2396: Allow more PRs
  .github/dependabot.yml
Labels: QA/CI, improvement
