Repository nuxeo/nuxeo-drive, pull requests merged in 2020-04, with the labels that each got.

#1522 NXDRIVE-1640: Refactor simple QMessageBoxes
  docs/changes/4.4.2.md
  nxdrive/gui/application.py
Labels: improvement

#1525 NXDRIVE-2079: Flatten MetaOptions.set()
  nxdrive/options.py
Labels: clean-up

#1526 NXDRIVE-2079: Add behaviors flags
  docs/changes/4.4.2.md
  docs/configuration.md
  docs/dep/2020-03 Features flags.md
  nxdrive/behavior.py
  nxdrive/engine/processor.py
  nxdrive/gui/application.py
  nxdrive/poll_workers.py
  tests/functional/test_server_options.py
  tests/old_functional/test_behavior.py
Labels: new-feature

#1527 NXDRIVE-2079: Add features flags
  docs/changes/4.4.2.md
  docs/dep/2020-03 Features flags.md
  nxdrive/client/remote_client.py
  nxdrive/commandline.py
  nxdrive/data/i18n/i18n.json
  nxdrive/data/qml/GeneralTab.qml
  nxdrive/data/qml/IconLabel.qml
  nxdrive/data/qml/Systray.qml
  nxdrive/direct_edit.py
  nxdrive/feature.py
  nxdrive/gui/application.py
  nxdrive/manager.py
  nxdrive/options.py
  nxdrive/poll_workers.py
  nxdrive/updater/base.py
  nxdrive/updater/utils.py
  tests/functional/test_server_options.py
  tests/functional/test_updater.py
  tests/unit/test_commandline.py
  tests/unit/test_options.py
Labels: new-feature

#1528 NXDRIVE-2079: Update the documentation
  docs/configuration.md
  nxdrive/feature.py
Labels: new-feature

#1529 NXDRIVE-2082: [Direct Transfer] Disable the feature until it is stable
  docs/changes/4.4.2.md
  nxdrive/feature.py
  nxdrive/options.py
  tests/functional/test_server_options.py
Labels: bugfix

#1532 NXDRIVE-2104: [GNU/Linux] Fix the docker image name to use for packaging
  docs/changes/4.4.2.md
  tools/jenkins/packages.groovy
Labels: GNU/Linux, bugfix

#1534 NXDRIVE-374: Fix error handling
  nxdrive/client/local/linux.py
  nxdrive/osi/linux/linux.py
Labels: bugfix

#1537 NXP-28626: follow changes
  docs/changes/4.4.2.md
  ftest/pom.xml
Labels: clean-up

#1542 Automatic update of translations from Crowdin
  nxdrive/data/i18n/i18n-de.json
  nxdrive/data/i18n/i18n-es-ES.json
  nxdrive/data/i18n/i18n-fr.json
  nxdrive/data/i18n/i18n-he.json
  nxdrive/data/i18n/i18n-id.json
  nxdrive/data/i18n/i18n-it.json
  nxdrive/data/i18n/i18n-ja.json
  nxdrive/data/i18n/i18n-nl.json
  nxdrive/data/i18n/i18n-sv-SE.json
Labels: translations

#1536 NXDRIVE-2079: Special case handling when testing the auto-updater
  nxdrive/manager.py
Labels: Windows, bugfix, macOS

#1543 Automatic update of translations from Crowdin
  nxdrive/data/i18n/i18n-es-ES.json
  nxdrive/data/i18n/i18n-fr.json
  nxdrive/data/i18n/i18n-it.json
  nxdrive/data/i18n/i18n-ja.json
Labels: bugfix, translations

#1538 NXDRIVE-382: Invalid conflict resolution when choosing the Local file, if the Remote file has been renamed before
  docs/changes/4.4.2.md
  nxdrive/engine/processor.py
  tests/old_functional/test_conflicts.py
Labels: bugfix

#1546 NXDRIVE-2064: Split GitHub workflows
  .github/workflows/dead_code.yml
  .github/workflows/lint.yml
  .github/workflows/pythonapp.yml
  .github/workflows/spell.yml
  .github/workflows/style.yml
  .github/workflows/translations.yml
  .github/workflows/types.yml
  .github/workflows/unit_tests.yml
  tests/__init__.py
  tools/deps/requirements-tox.txt
  tox.ini
Labels: QA/CI, improvement, tests

#1555 NXDRIVE-2064: Simplify the branch name guessing to bypass most errors
  tests/__init__.py
Labels: QA/CI, bugfix

#1556 NXDRIVE-2091: Fix analytics tracker creation
  nxdrive/manager.py
  tests/functional/test_tracker.py
Labels: bugfix

#1557 NXDRIVE-2106: Bypass the rm_rf pytest warning on Windows
  docs/changes/4.4.2.md
  tests/conftest.py
Labels: Windows, bugfix, tests

#1559 NXDRIVE-2108: [macOS] Fix notarization following the week-end of 2020…
  tools/osx/notarize.py
Labels: bugfix, macOS

#1562 NXDRIVE-1690: [GNU/Linux] File is not deleted on the server when the …
  docs/changes/4.4.2.md
  tests/old_functional/test_synchronization_suspend.py
Labels: bugfix, tests

#1563 NXDRIVE-2109: Properly skip OS based tests when run from another OS
  docs/changes/4.4.2.md
  tests/integration/windows/test_cli.py
  tests/integration/windows/test_cli_sub_command.py
  tests/integration/windows/utils.py
Labels: bugfix, tests

#1574 NXDRIVE-2115: Fix flake8 issues following the update to pyflakes 2.2.0
  docs/changes/4.4.2.md
  nxdrive/client/remote_client.py
  nxdrive/engine/dao/sqlite.py
  nxdrive/engine/processor.py
  nxdrive/engine/watcher/local_watcher.py
  nxdrive/gui/folders_model.py
  nxdrive/osi/windows/windows.py
  nxdrive/updater/darwin.py
  nxdrive/utils.py
  tests/integration/windows/test_cli_sub_command.py
  tests/integration/windows/utils.py
  tests/old_functional/test_synchronization_dedup.py
  tests/unit/test_utils.py
  tests/unit/test_windows_registry.py
  tools/scripts/check_update_process.py
Labels: bugfix

#1576 NXDRIVE-2118: Make the delay option effective when set from the serve…
  docs/changes/4.4.2.md
  nxdrive/engine/engine.py
  nxdrive/engine/watcher/remote_watcher.py
  tests/functional/conftest.py
  tests/functional/test_server_options.py
Labels: bugfix

#1579 NXDRIVE-1961: Release 4.4.2
  docs/changes.md
  docs/changes/4.4.2.md
  docs/support.md
Labels: Release

#1580 NXDRIVE-1961: Bump the version to 4.4.3
  docs/changes.md
  docs/changes/4.4.3.md
  nxdrive/__init__.py
Labels: Release

#1581 Upgraded PyObjC from 6.1 to 6.2
  tools/deps/requirements.txt
Labels: dependencies, macOS

#1582 Upgraded PyObjC from 6.1 to 6.2 (doc)
  docs/changes/4.4.3.md
Labels: dependencies, doc

#1583 NXDRIVE-1786: Fix functional test test_corrupted_download
  nxdrive/direct_edit.py
  tests/functional/test_direct_edit.py
Labels: bugfix

#1591 NXDRIVE-2124: Uniformize the name: Direct Edit
  docs/behaviors/Adobe Creative Suite.md
  docs/behaviors/README.md
  docs/changes/4.4.3.md
  docs/dep/2019-05 Enable pausing and resuming transfers.md
  docs/support.md
  nxdrive/autolocker.py
  nxdrive/data/i18n/i18n.json
  nxdrive/data/qml/SystrayTransfer.qml
  nxdrive/direct_edit.py
  nxdrive/exceptions.py
  nxdrive/manager.py
  nxdrive/notification.py
  nxdrive/objects.py
  tests/functional/test_direct_edit.py
  tests/old_functional/test_direct_edit.py
Labels: clean-up, translations

#1592 Automatic update of translations from Crowdin
  nxdrive/data/i18n/i18n-de.json
  nxdrive/data/i18n/i18n-es-ES.json
  nxdrive/data/i18n/i18n-fr.json
  nxdrive/data/i18n/i18n-he.json
  nxdrive/data/i18n/i18n-id.json
  nxdrive/data/i18n/i18n-it.json
  nxdrive/data/i18n/i18n-ja.json
  nxdrive/data/i18n/i18n-nl.json
  nxdrive/data/i18n/i18n-sv-SE.json
Labels: translations

#1594 NXDRIVE-1786: Remove the temporary file between attemps
  nxdrive/direct_edit.py
  tests/old_functional/test_direct_edit.py
Labels: bugfix

#1604 NXDRIVE-2130: Add Direct Edit and Direct Transfer sections in the cha…
  docs/changes/4.4.3.md
Labels: doc, improvement

#1612 NXDRIVE-2139: Make the custom user agent effective
  docs/changes/4.4.3.md
  nxdrive/client/proxy.py
  nxdrive/constants.py
  nxdrive/engine/tracker.py
  nxdrive/manager.py
  nxdrive/updater/base.py
  nxdrive/utils.py
  tools/changelog.py
  tools/scripts/check_update_process.py
Labels: bugfix
