Repository nuxeo/nuxeo-drive, pull requests merged in 2020-06, with the labels that each got.

#1679 NXDRIVE-2138: Add settings for features
  docs/changes/4.4.4.md
  nxdrive/commandline.py
  nxdrive/data/i18n/i18n.json
  nxdrive/data/qml/FeaturesTab.qml
  nxdrive/data/qml/NuxeoSwitch.qml
  nxdrive/data/qml/Settings.qml
  nxdrive/feature.py
  nxdrive/gui/api.py
  nxdrive/gui/application.py
  nxdrive/manager.py
  nxdrive/options.py
  nxdrive/utils.py
  tests/unit/test_utils.py
  tools/whitelist.py
Labels: new-feature

#1725 NXDRIVE-2174: Use versions check functions from the Python client
  docs/changes/4.4.4.md
  nxdrive/client/remote_client.py
  nxdrive/options.py
  nxdrive/updater/base.py
  nxdrive/updater/utils.py
  nxdrive/utils.py
  tests/old_functional/__init__.py
  tests/old_functional/test_bulk_remote_changes.py
  tests/old_functional/test_remote_deletion.py
  tests/unit/test_utils.py
Labels: clean-up

#1669 NXDRIVE-2129: [Direct Edit] Orphaned documents should first be remotely unlocked before being cleaned up
  docs/changes/4.4.4.md
  nxdrive/direct_edit.py
  tests/functional/test_direct_edit.py
Labels: bugfix

#1726 NXDRIVE-2179: Remove TwoUsersTest.report_path
  tests/old_functional/common.py
Labels: bugfix, tests

#1729 NXDRIVE-2179: Remove TwoUsersTest.current_test
  tests/old_functional/common.py
Labels: bugfix, tests

#1730 NXDRIVE-2189: Move non-Python test files to specific folders
  docs/changes/4.4.4.md
  tests/old_functional/test_direct_transfer.py
  tests/old_functional/test_local_copy_paste.py
  tests/old_functional/test_local_creations.py
  tests/old_functional/test_remote_client.py
  tests/old_functional/test_remote_deletion.py
  tests/old_functional/test_remote_move_and_rename.py
  tests/old_functional/test_special_files.py
  tests/old_functional/test_watchers.py
  tests/resources/databases/corrupted_database.db
  tests/resources/databases/engine_migration.db
  tests/resources/databases/engine_migration_10.db
  tests/resources/databases/engine_migration_8.db
  tests/resources/databases/engine_migration_duplicate.db
  tests/resources/databases/manager_migration.db
  tests/resources/databases/test_engine.db
  tests/resources/files/cat.jpg
  tests/resources/files/keynote.key
  tests/resources/files/testFile.pdf
  tests/resources/files/こんにちは.jpg
  tests/resources/files/東京スカイツリー.jpg
  tests/unit/conftest.py
  tests/unit/test_engine_dao.py
  tests/unit/test_model_filters.py
  tests/unit/test_translator.py
Labels: improvement, tests

#1737 NXDRIVE-2175: Update the action to fix PR creation
  .github/workflows/crowdin.yml
Labels: QA/CI, bugfix

#1739 NXDRIVE-2018: Change order of elements returned by get_tree_list()
  docs/changes/4.4.4.md
  nxdrive/engine/engine.py
  nxdrive/utils.py
  tests/old_functional/test_direct_transfer.py
  tests/unit/test_utils.py
Labels: improvement

#1740 NXDRIVE-2190: Refactor Remote client uploads
  docs/changes/4.4.4.md
  nxdrive/client/remote_client.py
  nxdrive/client/uploader/__init__.py
  nxdrive/client/uploader/direct_transfer.py
  nxdrive/client/uploader/sync.py
  nxdrive/engine/processor.py
  tests/old_functional/common.py
  tests/old_functional/test_direct_transfer.py
Labels: improvement

#1765 NXDRIVE-2199: Use the FileManager importer in tests
  docs/changes/4.4.4.md
  nxdrive/client/remote_client.py
  tests/old_functional/__init__.py
  tests/old_functional/common.py
  tests/old_functional/test_collection.py
  tests/old_functional/test_direct_edit.py
  tests/old_functional/test_local_client.py
  tests/old_functional/test_local_creations.py
  tests/old_functional/test_permission_hierarchy.py
  tests/old_functional/test_readonly.py
  tests/old_functional/test_reinit_database.py
  tests/old_functional/test_remote_client.py
  tests/old_functional/test_remote_deletion.py
  tests/old_functional/test_remote_move_and_rename.py
  tests/old_functional/test_shared_folders.py
  tests/old_functional/test_synchronization.py
  tests/old_functional/test_versioning.py
  tests/old_functional/test_volume.py
  tests/old_functional/test_watchers.py
  tests/resources/files/testFile.doc
  tests/resources/files/testFile.odt
  tests/unit/test_utils.py
Labels: improvement

#1771 NXDRIVE-2190: Fix test_transfer.py
  tests/old_functional/test_transfer.py
Labels: bugfix, tests

#1775 NXDRIVE-2203: Use Python 3 in release scripts
  docs/changes/4.4.4.md
  tools/cleanup.sh
  tools/deploy.sh
  tools/release.sh
Labels: QA/CI, bugfix

#1776 NXDRIVE-2203: Install missing requests module
  docs/changes/4.4.4.md
  tools/changelog.py
  tools/release.sh
Labels: QA/CI, bugfix

#1777 NXDRIVE-2204: Add notifications when release jobs fail
  docs/changes/4.4.4.md
  tools/jenkins/beta.groovy
Labels: QA/CI, new-feature

#1784 NXDRIVE-2201: Restore the 4 hours kill timeout for test_volume.py
  tests/old_functional/common.py
Labels: bugfix, tests

#1785 NXDRIVE-2211: Use DOCTYPE_FOLDERISH for creating the workspace in tests
  docs/changes/4.4.4.md
  tests/old_functional/common.py
Labels: bugfix, tests

#1790 NXDRIVE-2213: [Windows] Shut down warnings about QtBluetooth files re…
  docs/changes/4.4.4.md
  tools/windows/deploy_jenkins_slave.ps1
Labels: QA/CI, Windows, improvement

#1791 NXDRIVE-2212: [Windows] Fix pytest_cache folder removal
  docs/changes/4.4.4.md
  tools/windows/deploy_jenkins_slave.ps1
Labels: Windows, bugfix, tests

#1796 NXDRIVE-2215: Force push on tag creation when doing an alpha release
  docs/changes/4.4.4.md
  tools/release.sh
Labels: Release, bug

#1800 NXDRIVE-2208: [Direct Transfer] Enable to cancel one or more transfer
  docs/changes/4.4.4.md
  nxdrive/client/remote_client.py
  nxdrive/data/i18n/i18n.json
  nxdrive/data/qml/TransferItem.qml
  nxdrive/engine/engine.py
  nxdrive/gui/application.py
  tests/old_functional/test_direct_transfer.py
  tools/whitelist.py
Labels: new-feature
