Repository nuxeo/nuxeo-drive, pull requests merged in 2020-12, with the labels that each got.

#2263 NXDRIVE-2140: Handle unknown digests from the remote watcher
  nxdrive/client/remote_client.py
  nxdrive/engine/watcher/remote_watcher.py
Labels: bugfix

#2264 NXDRIVE-2434: [macOS] Fix 'NSError' object has no attribute 'utf8Valu…
  docs/changes/4.5.0.md
  tests/old_functional/local_client_darwin.py
Labels: bugfix, macOS, tests

#2265 NXDRIVE-2432: [Direct Transfer] Only display chunked transfers into the Monitoring tab
  docs/changes/4.5.0.md
  nxdrive/constants.py
  nxdrive/data/i18n/i18n.json
  nxdrive/data/qml/DirectTransfer.qml
  nxdrive/data/qml/Main.qml
  nxdrive/data/qml/TransferItem.qml
  nxdrive/engine/dao/sqlite.py
  nxdrive/engine/engine.py
  nxdrive/gui/api.py
  nxdrive/gui/application.py
Labels: QML, improvement

#2271 NXDRIVE-2432: Review the displayed text
  nxdrive/data/i18n/i18n.json
  nxdrive/data/qml/DirectTransfer.qml
Labels: QML, improvement

#2274 NXDRIVE-2435: Improve the PAC file reading resiliency
  tests/unit/test_proxy.py
Labels: improvement, tests

#2277 NXDRIVE-2360: Fix os.chmod() to conserve other permissions
  nxdrive/updater/linux.py
  tools/scripts/check_update_process.py
Labels: GNU/Linux, bugfix

#2283 NXDRIVE-2429: [Direct Transfer] Fix possible transfer cancellation mi…
  docs/changes/4.5.0.md
  tests/conftest.py
Labels: bugfix

#2284 NXDRIVE-2429: Remove the changelog entry
  docs/changes/4.5.0.md
Labels: doc

#2285 NXDRIVE-2439: Add more metrics to understand several keypoints
  docs/changes/4.5.0.md
  nxdrive/engine/engine.py
  nxdrive/engine/processor.py
  nxdrive/engine/tracker.py
  nxdrive/engine/watcher/local_watcher.py
  nxdrive/engine/watcher/remote_watcher.py
  nxdrive/engine/workers.py
  nxdrive/manager.py
Labels: improvement

#2272 [Direct Transfer] Remove pause button on the monitoring tab
  docs/changes/4.5.0.md
  nxdrive/client/uploader/__init__.py
  nxdrive/data/qml/SessionItem.qml
  nxdrive/data/qml/TransferItem.qml
  nxdrive/engine/dao/sqlite.py
  nxdrive/engine/engine.py
  nxdrive/engine/processor.py
  nxdrive/gui/application.py
Labels: QML, improvement

#2289 NXDRIVE-2430: Fix isPaused from SystrayMenuItem.engineToggle
  nxdrive/data/qml/SystrayMenu.qml
Labels: bugfix

#2291 NXDRIVE-2363: [macOS] Fix auto-update issues
  nxdrive/osi/darwin/darwin.py
  nxdrive/updater/darwin.py
  nxdrive/updater/linux.py
  nxdrive/updater/windows.py
Labels: bugfix, macOS

#2292 NXDRIVE-2439: Skip account.count metrics when there is no account
  nxdrive/manager.py
Labels: clean-up

#2294 NXDRIVE-2433: Ignore data from shadow items on transfers refresh
  nxdrive/gui/application.py
Labels: bugfix

#2295 NXDRIVE-2433: Fix handling of transfer that must be suspended at exit
  nxdrive/client/uploader/__init__.py
Labels: bugfix

#2296 NXDRIVE-2433: Fix cancel button become disabled after transfer removal
  docs/changes/4.5.0.md
  nxdrive/data/qml/TransferItem.qml
  nxdrive/engine/dao/sqlite.py
  nxdrive/gui/application.py
  nxdrive/gui/view.py
Labels: QML, bugfix

#2297 NXDRIVE-2309: Improve the session pause behavior
  nxdrive/engine/dao/sqlite.py
  nxdrive/engine/processor.py
Labels: bugfix

#2307 NXDRIVE-2309: [Direct Transfer] Only repush items session when resumi…
  nxdrive/engine/dao/sqlite.py
Labels: bugfix

#2308 NXDRIVE-2309: [Direct Transfer] Improve session counts computing on c…
  docs/changes/4.5.0.md
  nxdrive/engine/dao/sqlite.py
  nxdrive/engine/engine.py
  nxdrive/engine/processor.py
  nxdrive/gui/application.py
Labels: bugfix

#2309 NXDRIVE-2452: Add release dates in versions.yml
  docs/changes/4.5.0.md
  tools/versions.py
Labels: Release, improvement

#2311 NXDRIVE-2313: Release 4.5.0
  docs/changes.md
  docs/changes/4.5.0.md
Labels: Release

#2312 NXDRIVE-2313: Bump the version to 4.5.1
  docs/changes.md
  docs/changes/4.5.1.md
  nxdrive/__init__.py
Labels: Release

#2226 NXDRIVE-2394: [Direct Transfer] Handle multiple transfers on same file
  docs/changes/4.5.1.md
  nxdrive/client/uploader/__init__.py
  nxdrive/client/uploader/direct_transfer.py
  nxdrive/engine/activity.py
  nxdrive/engine/dao/sqlite.py
  nxdrive/engine/processor.py
  nxdrive/gui/view.py
  tests/old_functional/test_direct_transfer.py
Labels: bugfix

#2318 NXDRIVE-1768: Several fixes
  nxdrive/autolocker.py
  nxdrive/client/local/base.py
  nxdrive/client/proxy.py
  nxdrive/client/remote_client.py
  nxdrive/client/uploader/__init__.py
  nxdrive/client/uploader/direct_transfer.py
  nxdrive/direct_edit.py
  nxdrive/engine/dao/sqlite.py
  nxdrive/engine/engine.py
  nxdrive/engine/processor.py
  nxdrive/engine/queue_manager.py
  nxdrive/engine/tracker.py
  nxdrive/engine/watcher/local_watcher.py
  nxdrive/engine/watcher/remote_watcher.py
  nxdrive/engine/workers.py
  nxdrive/gui/api.py
  nxdrive/gui/application.py
  nxdrive/gui/systray.py
  nxdrive/logging_config.py
  nxdrive/manager.py
  nxdrive/osi/darwin/darwin.py
  nxdrive/osi/darwin/extension.py
  nxdrive/osi/extension.py
  nxdrive/osi/windows/extension.py
  nxdrive/osi/windows/windows.py
  nxdrive/poll_workers.py
  nxdrive/updater/base.py
  tests/old_functional/__init__.py
  tests/old_functional/test_direct_edit.py
  tests/old_functional/test_ignored.py
  tests/old_functional/test_remote_deletion.py
  tests/old_functional/test_remote_move_and_rename.py
  tests/unit/test_proxy.py
Labels: bugfix, clean-up

#2319 NXDRIVE-2456: Remove deprecated usage of --strict pytest argument
  docs/changes/4.5.1.md
  setup.cfg
Labels: bugfix, tests

#2320 NXDRIVE-1768: Fix tests
  tests/old_functional/test_local_move_and_rename.py
  tests/old_functional/test_transfer.py
Labels: bugfix, tests

#2328 NXDRIVE-1768: Fix commandline.py
  nxdrive/commandline.py
Labels: bugfix

#2332 NXDRIVE-2444: Move qt_constants.py to qt/constants.py
  docs/changes/4.5.1.md
  nxdrive/commandline.py
  nxdrive/fatal_error.py
  nxdrive/gui/api.py
  nxdrive/gui/application.py
  nxdrive/gui/folders_dialog.py
  nxdrive/gui/folders_loader.py
  nxdrive/gui/folders_model.py
  nxdrive/gui/folders_treeview.py
  nxdrive/gui/systray.py
  nxdrive/gui/view.py
  nxdrive/osi/extension.py
  nxdrive/qt/__init__.py
  nxdrive/qt/constants.py
  tests/unit/test_extension_listener.py
Labels: improvement

#2333 NXDRIVE-2459: Move PyQt imports to one file
  docs/changes/4.5.1.md
  nxdrive/__main__.py
  nxdrive/autolocker.py
  nxdrive/client/remote_client.py
  nxdrive/client/uploader/__init__.py
  nxdrive/commandline.py
  nxdrive/console.py
  nxdrive/direct_edit.py
  nxdrive/engine/activity.py
  nxdrive/engine/dao/sqlite.py
  nxdrive/engine/engine.py
  nxdrive/engine/processor.py
  nxdrive/engine/queue_manager.py
  nxdrive/engine/tracker.py
  nxdrive/engine/watcher/local_watcher.py
  nxdrive/engine/watcher/remote_watcher.py
  nxdrive/engine/workers.py
  nxdrive/fatal_error.py
  nxdrive/gui/api.py
  nxdrive/gui/application.py
  nxdrive/gui/folders_dialog.py
  nxdrive/gui/folders_loader.py
  nxdrive/gui/folders_model.py
  nxdrive/gui/folders_treeview.py
  nxdrive/gui/systray.py
  nxdrive/gui/view.py
  nxdrive/manager.py
  nxdrive/notification.py
  nxdrive/osi/__init__.py
  nxdrive/osi/extension.py
  nxdrive/osi/windows/windows.py
  nxdrive/poll_workers.py
  nxdrive/qt/constants.py
  nxdrive/qt/imports.py
  nxdrive/translator.py
  nxdrive/updater/base.py
  tests/conftest.py
  tests/old_functional/common.py
  tests/unit/test_extension_listener.py
Labels: clean-up

#2334 NXDRIVE-1768: Fix call to show_settings() in systray.py
  nxdrive/gui/systray.py
Labels: bugfix

#2335 NXDRIVE-1768: Fix icons set reloading
  nxdrive/gui/application.py
Labels: bugfix

#2336 NXDRIVE-2444: Fix notification icons
  nxdrive/gui/application.py
  nxdrive/qt/constants.py
Labels: bugfix
