Repository nuxeo/nuxeo-drive, pull requests merged in 2020-07, with the labels that each got.

#1802 NXDRIVE-1926: Improve the Direct Transfer window
  nxdrive/data/i18n/i18n.json
  nxdrive/data/qml/DirectTransfer.qml
  nxdrive/data/qml/Main.qml
  nxdrive/data/qml/TransferItem.qml
  nxdrive/gui/application.py
Labels: bugfix, improvement

#1807 NXDRIVE-1926: Improve performances by removing an unused QVariant
  nxdrive/data/qml/TransferItem.qml
Labels: clean-up, improvement

#1808 NXDRIVE-2219: Display a remote folder icon for each transfer
  docs/changes/4.4.4.md
  nxdrive/client/uploader/__init__.py
  nxdrive/client/uploader/direct_transfer.py
  nxdrive/data/i18n/i18n.json
  nxdrive/data/qml/DirectTransfer.qml
  nxdrive/data/qml/Main.qml
  nxdrive/data/qml/TransferItem.qml
  nxdrive/engine/dao/sqlite.py
  nxdrive/engine/engine.py
  nxdrive/engine/processor.py
  nxdrive/gui/api.py
  nxdrive/gui/application.py
  nxdrive/gui/view.py
  nxdrive/objects.py
  nxdrive/state.py
  tests/old_functional/test_direct_transfer.py
  tools/whitelist.py
Labels: bugfix, improvement

#1810 NXDRIVE-2220: Asynchronous planification of uploads
  docs/changes/4.4.4.md
  nxdrive/engine/engine.py
  nxdrive/engine/workers.py
  nxdrive/gui/folders_dialog.py
Labels: improvement

#1813 NXDRIVE-2223: Select Web UI by default in Settings
  docs/changes/4.4.4.md
  nxdrive/engine/engine.py
  nxdrive/poll_workers.py
Labels: improvement

#1812 NXDRIVE-2221: Improve performances to prevent GUI freezes
  docs/changes/4.4.4.md
  nxdrive/client/remote_client.py
  nxdrive/client/uploader/__init__.py
  nxdrive/client/uploader/direct_transfer.py
  nxdrive/data/qml/DirectTransfer.qml
  nxdrive/data/qml/Main.qml
  nxdrive/data/qml/SystrayTransfer.qml
  nxdrive/data/qml/TransferItem.qml
  nxdrive/engine/activity.py
  nxdrive/engine/dao/sqlite.py
  nxdrive/engine/engine.py
  nxdrive/engine/processor.py
  nxdrive/gui/api.py
  nxdrive/gui/application.py
  nxdrive/gui/view.py
  nxdrive/objects.py
  nxdrive/utils.py
  tests/old_functional/test_direct_transfer.py
  tests/unit/test_action.py
  tests/unit/test_utils.py
Labels: bugfix, improvement

#1817 NXDRIVE-2221: Fix the spinner display
  nxdrive/data/qml/DirectTransfer.qml
Labels: bugfix

#1818 NXDRIVE-2222: Fix display of progress bars when pausing a transfer
  nxdrive/client/uploader/__init__.py
Labels: bugfix

#1821 NXDRIVE-2203: Use Python 3 in release clean-up script
  tools/cleanup.sh
Labels: bugfix

#1819 NXDRIVE-2227: Fix Translations formatting
  docs/changes/4.4.4.md
  nxdrive/data/i18n/i18n.json
Labels: translations

#1824 NXDRIVE-2231: [Direct Transfer] Improve the NXQL duplicate check
  docs/changes/4.4.4.md
  nxdrive/client/remote_client.py
  nxdrive/client/uploader/__init__.py
  nxdrive/client/uploader/direct_transfer.py
  tests/old_functional/__init__.py
Labels: improvement

#1826 NXDRIVE-2232: Add an option to control the database batch size
  docs/changes/4.4.4.md
  docs/configuration.md
  nxdrive/engine/engine.py
  nxdrive/options.py
Labels: new-feature

#1833 NXDRIVE-2065: Remove headers and params
  nxdrive/client/uploader/direct_transfer.py
Labels: improvement

#1834 NXDRIVE-2232: Restore the value sent to the signal to force a count r…
  nxdrive/engine/engine.py
Labels: bugfix

#1835 NXDRIVE-2232: Better signal management
  nxdrive/engine/engine.py
Labels: improvement

#1836 NXDRIVE-2233: [Direct Transfer] Remove void transfers on HTTP 404 error
  nxdrive/engine/workers.py
  tests/old_functional/test_direct_transfer.py
Labels: bugfix

#1837 NXDRIVE-2231: Partly revert the patch
  docs/changes/4.4.4.md
  nxdrive/client/remote_client.py
  nxdrive/client/uploader/direct_transfer.py
  tests/old_functional/__init__.py
Labels: bugfix

#1838 NXDRIVE-2235: Temporary disable duplicate prevention
  docs/changes/4.4.4.md
  nxdrive/client/uploader/direct_transfer.py
Labels: bug

#1840 NXDRIVE-2237: Update the Nuxeo snapshot to 11.2
  docs/changes/4.4.4.md
  ftest/pom.xml
Labels: tests

#1841 NXDRIVE-2173: Release 4.4.4
  docs/changes.md
  docs/changes/4.4.4.md
Labels: Release

#1842 NXDRIVE-2173: Bump the version to 4.4.5
  docs/changes.md
  docs/changes/4.4.5.md
  nxdrive/__init__.py
Labels: Release

#1805 NXDRIVE-2193: Stop trying to guess the server URL
  docs/changes/4.4.5.md
  nxdrive/data/qml/NewAccountPopup.qml
  nxdrive/gui/api.py
  nxdrive/utils.py
  tests/functional/test_utils.py
  tests/unit/test_utils.py
Labels: improvement

#1845 NXDRIVE-2234: [Direct Transfer] Add a new graphical option to choose …
  docs/changes/4.4.5.md
  nxdrive/client/uploader/direct_transfer.py
  nxdrive/data/i18n/i18n.json
  nxdrive/engine/dao/sqlite.py
  nxdrive/engine/engine.py
  nxdrive/engine/processor.py
  nxdrive/exceptions.py
  nxdrive/gui/application.py
  nxdrive/gui/folders_dialog.py
  nxdrive/objects.py
  tests/old_functional/common.py
  tests/old_functional/test_direct_transfer.py
  tests/unit/test_engine_dao.py
Labels: new-feature

#1850 NXDRIVE-2186: Do not remove staled transfers at startup if the applic…
  docs/changes/4.4.5.md
  nxdrive/commandline.py
  nxdrive/engine/engine.py
  nxdrive/state.py
  tests/old_functional/test_transfer.py
Labels: bugfix

#1855 NXDRIVE-2234: Update the documentation URL
  nxdrive/gui/folders_dialog.py
Labels: doc

#1857 NXDRIVE-2241: Review Popup Release Notes
  docs/changes/4.4.5.md
  nxdrive/data/i18n/i18n.json
  nxdrive/gui/application.py
  tools/deps/requirements-tests.txt
  tools/deps/requirements.txt
Labels: improvement

#1859 NXDRIVE-2144: [Direct Edit] Prevent unintentional upload of files
  docs/changes/4.4.5.md
  nxdrive/direct_edit.py
  tests/functional/test_direct_edit.py
Labels: bugfix

#1863 NXDRIVE-2234: Use "Create" as default choice for the duplicates behavior
  nxdrive/data/i18n/i18n.json
  nxdrive/engine/engine.py
  nxdrive/gui/folders_dialog.py
Labels: improvement

#1862 NXDRIVE-2247: Rename "Direct Transfer" context menu to "Upload content"
  docs/changes/4.4.5.md
  nxdrive/data/i18n/i18n.json
Labels: translations

#1866 NXDRIVE-2248: Fix the Features documentation
  docs/changes/4.4.5.md
  nxdrive/feature.py
Labels: bugfix, doc

#1867 NXDRIVE-2249: Update the Crowdin action and use PR labels
  .github/workflows/crowdin.yml
  docs/changes/4.4.5.md
Labels: QA/CI, improvement

#1865 NXDRIVE-2225: Remove the server URL below the account name in the systray
  docs/changes/4.4.5.md
  nxdrive/data/i18n/i18n.json
  nxdrive/data/qml/Systray.qml
  nxdrive/engine/engine.py
  nxdrive/gui/api.py
  tests/functional/test_direct_edit.py
  tools/whitelist.py
Labels: improvement

#1870 NXDRIVE-2225: Update Nuxeo action icon tooltip
  nxdrive/data/i18n/i18n.json
  nxdrive/data/qml/Systray.qml
Labels: QML, improvement

#1872 NXDRIVE-2245: Use safe_long_path() in old functional tests
  docs/changes/4.4.5.md
  nxdrive/client/local/base.py
  nxdrive/manager.py
  tests/old_functional/common.py
Labels: bugfix, tests

#1877 NXDRIVE-2210: Save new credentials on token renewal
  docs/changes/4.4.5.md
  nxdrive/client/uploader/__init__.py
Labels: bugfix

#1878 NXDRIVE-2247: Apply changes in the FinderSync code too
  nxdrive/osi/darwin/darwin.py
  tools/osx/drive/NuxeoFinderSync/FinderSync.swift
  tools/osx/drive/NuxeoFinderSync/Info.plist
Labels: improvement, macOS

#1880 NXDRIVE-2234: Remove useless signal
  nxdrive/gui/folders_dialog.py
Labels: clean-up

#1881 NXDRIVE-2254: Always send primary metrics (app and OS versions)
  docs/changes/4.4.5.md
  nxdrive/engine/tracker.py
  nxdrive/gui/api.py
  nxdrive/gui/application.py
  nxdrive/manager.py
  tests/functional/test_tracker.py
Labels: improvement

#1892 NXDRIVE-2259: Move the Docker image build to GitHub Actions
  .github/workflows/docker_build.yml
  docs/changes/4.4.5.md
  tools/linux/Dockerfile
  tools/linux/entrypoint.sh
Labels: QA/CI, new-feature

#1893 NXDRIVE-2259: Fix the workflow file
  .github/workflows/docker_build.yml
Labels: QA/CI, bugfix

#1894 NXDRIVE-2259: Fix the registry
  .github/workflows/docker_build.yml
Labels: QA/CI, bugfix

#1895 NXDRIVE-2259: Fix
  .github/workflows/docker_build.yml
Labels: QA/CI, bugfix

#1896 NXDRIVE-2259: Still fixing registry and repository ...
  .github/workflows/docker_build.yml
Labels: QA/CI, bugfix

#1897 NXDRIVE-2259: This is the good one (hopefully)
  .github/workflows/docker_build.yml
Labels: QA/CI, bugfix

#1899 NXDRIVE-2245: Fix an AttributeError in common.py
  tests/old_functional/common.py
Labels: bugfix, tests

#1900 NXDRIVE-2263: Fix new errors found by vulture 1.6
  docs/changes/4.4.5.md
  nxdrive/data/i18n/i18n.json
  nxdrive/translator.py
  tools/whitelist.py
Labels: bugfix, clean-up, tests

#1904 NXDRIVE-2269: New language: Polish (pl)
  docs/changes/4.4.5.md
  docs/support.md
  tests/unit/test_translator.py
  tools/windows/setup-common.iss
Labels: new-feature, translations

#1906 NXDRIVE-2259: Move the alpha cleaner job to GitHub Actions
  .github/workflows/alpha_cleanup.yml
  docs/changes/4.4.5.md
  tools/cleanup.sh
  tools/jenkins/cleanup.groovy
Labels: QA/CI, new-feature
