Repository nuxeo/nuxeo-drive, pull requests merged in 2020-08, with the labels that each got.

#1912 NXDRIVE-2272: Save username changes when updating credentials (fixes …
  docs/changes/4.4.5.md
  nxdrive/engine/engine.py
  nxdrive/gui/api.py
Labels: bugfix

#1876 NXDRIVE-2019: Enable folder uploads
  .gitignore
  docs/changes/4.4.5.md
  nxdrive/client/uploader/direct_transfer.py
  nxdrive/engine/dao/sqlite.py
  nxdrive/engine/engine.py
  nxdrive/engine/processor.py
  nxdrive/engine/queue_manager.py
  nxdrive/gui/folders_dialog.py
  tests/old_functional/test_direct_transfer.py
Labels: new-feature

#1913 NXDRIVE-2267: [Direct Transfer] Do not open the file selection box on click in the systray
  docs/changes/4.4.5.md
  nxdrive/gui/folders_dialog.py
Labels: improvement

#1882 NXDRIVE-2210: Move the packaging process to Travis-CI
  .travis.yml
  docs/changes/4.4.5.md
  docs/deployment.md
  tools/bump-alpha-version.sh
  tools/changelog.py
  tools/check-spell.sh
  tools/cleanup.sh
  tools/deploy.sh
  tools/env.sh
  tools/jenkins/packages.groovy
  tools/linux/appimage/appdir-lint.sh
  tools/linux/deploy_jenkins_slave.sh
  tools/linux/travis.sh
  tools/osx/deploy_jenkins_slave.sh
  tools/osx/notarize.py
  tools/osx/travis.sh
  tools/posix/deploy_jenkins_slave.sh
  tools/release.sh
  tools/upload.sh
  tools/versions.py
  tools/windows/deploy_jenkins_slave.ps1
  tools/windows/travis.sh
Labels: GNU/Linux, QA/CI, Windows, macOS, new-feature

#1917 NXDRIVE-2089: [Windows] Upgrade Inno Setup from 6.0.2 to 6.0.5
  .travis.yml
  docs/changes/4.4.5.md
  docs/deployment.md
Labels: QA/CI, Windows, improvement

#1918 NXDRIVE-2264: Upgrade Python from 3.7.7 to 3.7.8
  .github/workflows/dead_code.yml
  .github/workflows/lint.yml
  .github/workflows/spell.yml
  .github/workflows/style.yml
  .github/workflows/translations.yml
  .github/workflows/types.yml
  .github/workflows/unit_tests.yml
  docs/changes/4.4.5.md
  docs/deployment.md
  docs/support.md
  tools/linux/travis.sh
  tools/posix/deploy_jenkins_slave.sh
  tools/windows/deploy_jenkins_slave.ps1
  tools/windows/scripts/envvars.bat
Labels: QA/CI, improvement

#1916 NXDRIVE-2266: [Direct Transfer] Should ignore same file patterns as the sync engine
  docs/changes/4.4.5.md
  nxdrive/engine/engine.py
  tests/old_functional/test_direct_transfer.py
Labels: bugfix

#1919 NXDRIVE-2241: Skip the release notes popup on alpha versions
  nxdrive/gui/application.py
Labels: improvement

#1921 NXDRIVE-2268: Best efforts to center a window on the screen
  docs/changes/4.4.5.md
  nxdrive/gui/application.py
Labels: bug

#1922 NXDRIVE-2274: [Direct Transfer] When cancelling a folder selection, t…
  nxdrive/gui/folders_dialog.py
Labels: bugfix

#1923 NXDRIVE-2266: Fix file patterns filtering
  docs/changes/4.4.5.md
  nxdrive/engine/engine.py
  nxdrive/gui/folders_dialog.py
  nxdrive/utils.py
  tests/old_functional/test_direct_transfer.py
  tests/unit/test_utils.py
Labels: bugfix

#1924 NXDRIVE-2275: [Direct Transfer] New transfer from context menu does n…
  nxdrive/gui/application.py
  nxdrive/gui/folders_dialog.py
  nxdrive/utils.py
Labels: bugfix

#1925 NXDRIVE-2135: Check for proxy instantiation success when using a PAC
  docs/changes/4.4.5.md
  nxdrive/client/proxy.py
  nxdrive/manager.py
Labels: bugfix

#1927 NXDRIVE-2230: Date/time display should be OS aware
  docs/changes/4.4.5.md
  nxdrive/__main__.py
Labels: bugfix

#1920 NXDRIVE-2147: [Direct Edit] Add a maximum retry count for items in the upload queue
  docs/changes/4.4.5.md
  nxdrive/data/i18n/i18n.json
  nxdrive/direct_edit.py
  nxdrive/engine/blacklist_queue.py
  tests/old_functional/test_direct_edit.py
Labels: bugfix

#1951 NXDRIVE-2277: [Direct Edit] Fix changes not uploaded anymore when sav…
  nxdrive/utils.py
Labels: Windows, bugfix

#1952 NXDRIVE-2280: Use the --no-cache-dir argument when installing require…
  docs/changes/4.4.5.md
  tools/posix/deploy_jenkins_slave.sh
  tools/windows/deploy_jenkins_slave.ps1
Labels: improvement

#1953 NXDRIVE-2281: Upgrade Python from 3.7.8 to 3.7.9
  .github/workflows/dead_code.yml
  .github/workflows/lint.yml
  .github/workflows/spell.yml
  .github/workflows/style.yml
  .github/workflows/translations.yml
  .github/workflows/types.yml
  .github/workflows/unit_tests.yml
  docs/changes/4.4.5.md
  docs/deployment.md
  docs/support.md
  tools/linux/travis.sh
  tools/posix/deploy_jenkins_slave.sh
  tools/windows/deploy_jenkins_slave.ps1
Labels: improvement

#1954 NXDRIVE-2259: Prevent uploading versions.yml when there are no changes
  tools/cleanup.sh
Labels: QA/CI, improvement

#1955 NXDRIVE-2110: Fix the release process for beta
  tools/release.sh
Labels: QA/CI, bugfix

#1957 NXDRIVE-2253: Minor configuration change following tox upgrade to 3.18.0
  docs/changes/4.4.5.md
  tox.ini
Labels: clean-up, tests

#1958 NXDRIVE-2252: Check and rewrite non-inclusive code and documentation
  docs/changes/4.4.5.md
  docs/deployment.md
  docs/gnu_linux.md
  docs/icon_overlay.md
  nxdrive/direct_edit.py
  nxdrive/engine/blocklist_queue.py
  nxdrive/engine/engine.py
  nxdrive/engine/queue_manager.py
  nxdrive/fatal_error.py
  nxdrive/gui/systray.py
  setup.cfg
  tests/benchmarks/test_safe_filename.py
  tests/integration/README.md
  tests/integration/windows/_test_installer.py
  tests/old_functional/test_concurrent_synchronization.py
  tests/old_functional/test_local_client.py
  tests/old_functional/test_local_move_and_rename.py
  tests/old_functional/test_local_storage_issue.py
  tests/old_functional/test_synchronization.py
  tests/old_functional/test_transfer.py
  tests/unit/test_blacklist_queue.py
  tools/changelog.py
  tools/check-spell.sh
  tools/integration_tests_setup.py
  tools/jenkins/test_volume.groovy
  tools/jenkins/test_volume_specific.groovy
  tools/jenkins/tests.groovy
  tools/jenkins/tests_os.groovy
  tools/linux/Dockerfile
  tools/linux/appimage/appdir-lint.sh
  tools/linux/appimage/excludelist
  tools/linux/deploy_ci_agent.sh
  tools/linux/entrypoint.sh
  tools/linux/travis.sh
  tools/osx/README.md
  tools/osx/deploy_ci_agent.sh
  tools/osx/generate-dmg-ds-store.sh
  tools/osx/travis.sh
  tools/posix/deploy_ci_agent.sh
  tools/scripts/check_update_process.py
  tools/scripts/common_failures.py
  tools/skiplist.py
  tools/spell.allowlist
  tools/spell.skip
  tools/windows/deploy_ci_agent.ps1
  tools/windows/scripts/build.bat
  tools/windows/scripts/launch.bat
  tools/windows/scripts/setup.bat
  tools/windows/scripts/tests-specific.bat
  tools/windows/scripts/tests.bat
  tools/windows/travis.sh
  tox.ini
Labels: clean-up

#1959 NXDRIVE-2180: Really fix the QML error when Direct Transfer'ring lot …
  nxdrive/data/qml/TransferItem.qml
Labels: QML, bugfix

#1960 NXDRIVE-2234: Update the documentation URL
  nxdrive/gui/folders_dialog.py
Labels: doc, improvement

#1961 NXDRIVE-2019: Do not fetch the database lazily to prevent deadlocks
  docs/changes/4.4.5.md
  nxdrive/engine/dao/sqlite.py
Labels: bugfix

#1962 NXDRIVE-2254: Fix the method checking if the user allowed to send ana…
  docs/changes/4.4.5.md
  nxdrive/engine/tracker.py
  tests/functional/test_tracker.py
Labels: bugfix

#1965 NXDRIVE-2285: Fix formatting issues following the upgrade to Black 20…
  .pre-commit-config.yaml
  docs/changes/4.4.5.md
  nxdrive/client/local/darwin.py
  nxdrive/client/uploader/direct_transfer.py
  nxdrive/feature.py
  nxdrive/gui/api.py
  nxdrive/manager.py
  nxdrive/osi/darwin/pyNotificationCenter.py
  nxdrive/osi/linux/linux.py
  tests/__init__.py
  tests/functional/test_behavior.py
  tests/functional/test_updater.py
  tests/integration/windows/test_cli_sub_command.py
  tests/old_functional/__init__.py
  tests/old_functional/test_bulk_remote_changes.py
  tests/old_functional/test_direct_transfer.py
  tests/old_functional/test_local_client.py
  tests/old_functional/test_long_path.py
  tests/old_functional/test_readonly.py
  tests/utils.py
  tools/check_translations.py
Labels: improvement

#1964 NXDRIVE-2019: Improve database queries
  docs/changes/4.4.5.md
  nxdrive/engine/dao/sqlite.py
  nxdrive/gui/api.py
Labels: improvement

#1966 NXDRIVE-2180: Fix more QML errors
  nxdrive/data/qml/FileCard.qml
  nxdrive/data/qml/SystrayFile.qml
  nxdrive/data/qml/SystrayTransfer.qml
Labels: QML, bugfix

#1967 NXDRIVE-2236: Should work with non-standard or empty digests
  docs/changes/4.4.5.md
  nxdrive/client/remote_client.py
  nxdrive/direct_edit.py
  nxdrive/objects.py
  tests/old_functional/test_direct_edit.py
Labels: bugfix

#1969 NXDRIVE-2135: Lower the logging level of validate_proxy()
  nxdrive/client/proxy.py
Labels: improvement

#1974 NXDRIVE-2083: Use more dict.copy() to prevent exceptions
  nxdrive/direct_edit.py
  nxdrive/engine/tracker.py
  nxdrive/gui/application.py
  nxdrive/manager.py
  nxdrive/notification.py
  nxdrive/report.py
  tests/functional/conftest.py
  tests/old_functional/__init__.py
Labels: bugfix

#1975 NXDRIVE-2147: Fixed test_direct_edit_max_error() on Windows
  tests/old_functional/test_direct_edit.py
Labels: bugfix
