Repository nuxeo/nuxeo-drive, pull requests merged in 2020-02, with the labels that each got.

#1337 NXDRIVE-2008: Add missing codespell dependency
  requirements-tests.txt
  tools/codespell_skip.txt
Labels: bugfix

#1338 NXDRIVE-2027: Allow Direct Edit on custom blob metadata values
  docs/changes/4.4.2.md
  nxdrive/direct_edit.py
  nxdrive/objects.py
  tests/functional/test_direct_edit.py
Labels: new-feature

#1339 Upgraded nuxeo from 2.4.2 to 2.4.3
  docs/changes/4.4.2.md
  nxdrive/client/remote_client.py
  requirements.txt
Labels: dependencies, improvement

#1350 NXDRIVE-2008: Codespell adjustments
  tools/codespell_skip.txt
  tools/codespell_whitelist.txt
  tools/posix/deploy_jenkins_slave.sh
  tools/spell.skip
  tools/spell.whitelist
Labels: improvement

#1351 NXDRIVE-2027: Allow to Direct Edit any custom metadata values
  nxdrive/objects.py
  tests/functional/test_direct_edit.py
  tests/unit/test_objects.py
Labels: improvement

#1349 NXDRIVE-1831: Set the root local folder icon on Linux
  docs/changes/4.4.2.md
  nxdrive/client/local/linux.py
  nxdrive/data/icons/emblem.svg
  nxdrive/engine/engine.py
Labels: GNU/Linux, new-feature

#1346 NXDRIVE-1996: Add script to check translations files
  docs/changes/4.4.2.md
  docs/deployment.md
  nxdrive/data/i18n/i18n.json
  tools/check_translations.py
  tools/posix/deploy_jenkins_slave.sh
Labels: new-feature, tests

#1356 Automatic update of translations from Crowdin
  nxdrive/data/i18n/i18n-de.json
  nxdrive/data/i18n/i18n-es-ES.json
  nxdrive/data/i18n/i18n-fr.json
  nxdrive/data/i18n/i18n-he.json
  nxdrive/data/i18n/i18n-id.json
  nxdrive/data/i18n/i18n-it.json
  nxdrive/data/i18n/i18n-ja.json
  nxdrive/data/i18n/i18n-nl.json
  nxdrive/data/i18n/i18n-sv-SE.json
Labels: translations

#1357 Automatic update of translations from Crowdin
  nxdrive/data/i18n/i18n-de.json
  nxdrive/data/i18n/i18n-es-ES.json
  nxdrive/data/i18n/i18n-he.json
  nxdrive/data/i18n/i18n-it.json
  nxdrive/data/i18n/i18n-ja.json
  nxdrive/data/i18n/i18n-nl.json
  nxdrive/data/i18n/i18n-sv-SE.json
Labels: translations

#1355 NXDRIVE-2052: Optimize CPU consumption (and laptop batteries)
  docs/changes/4.4.2.md
  nxdrive/engine/watcher/local_watcher.py
  nxdrive/engine/workers.py
Labels: improvement

#1361 NXDRIVE-2047: Unlock updates on the centralized channel when auto-upd…
  docs/changes/4.4.2.md
  nxdrive/engine/workers.py
  nxdrive/manager.py
  nxdrive/updater/README.md
  nxdrive/updater/__init__.py
  nxdrive/updater/base.py
  nxdrive/updater/constants.py
  nxdrive/updater/utils.py
  tests/functional/test_updater.py
Labels: improvement

#1362 NXDRIVE-2055: Process queued Qt events on CTRL+C
  docs/changes/4.4.2.md
  nxdrive/__main__.py
Labels: bugfix

#1363 Revert "Bump idna from 2.8 to 2.9 (#1360)"
  docs/changes/4.4.2.md
  requirements.txt
Labels: bugfix, dependencies

#1375 NXDRIVE-2041: [macOS] Notarize the application
  tools/osx/deploy_jenkins_slave.sh
  tools/osx/notarize.py
Labels: bugfix, macOS

#1383 NXDRIVE-2061: Reduce the final package size
  tools/cleanup_application_tree.py
Labels: clean-up

#1370 NXDRIVE-2056: [GNU/Linux] PyInstaller 3.6 broke AppImage builds
  docs/changes/4.4.2.md
  requirements-dev.txt
  tools/deps/pyinstaller-41237b1.zip
  tools/posix/deploy_jenkins_slave.sh
Labels: GNU/Linux, bugfix

#1387 NXDRIVE-2054: Ask for a new batch in case of failed S3 upload resuming
  docs/changes/4.4.2.md
  nxdrive/client/remote_client.py
  nxdrive/engine/engine.py
Labels: bug

#1364 NXDRIVE-2042: Display the disk free space at different places
  docs/changes/4.4.2.md
  nxdrive/constants.py
  nxdrive/data/i18n/i18n.json
  nxdrive/data/qml/AccountsTab.qml
  nxdrive/data/qml/NewAccountPopup.qml
  nxdrive/data/qml/NuxeoToolTip.qml
  nxdrive/data/qml/RectangleTooltip.qml
  nxdrive/gui/api.py
  nxdrive/gui/application.py
Labels: improvement

#1392 NXDRIVE-2062: Use mac-drive-2 for macOs releases
  tools/jenkins/packages.groovy
Labels: improvement

#1393 NXDRIVE-1893: Remove hardcoded "Nuxeo Drive" strings
  docs/changes/4.4.2.md
  nxdrive/data/i18n/i18n.json
  nxdrive/data/qml/Main.qml
  nxdrive/data/qml/Systray.qml
  nxdrive/direct_edit.py
  nxdrive/gui/api.py
  nxdrive/gui/application.py
  nxdrive/notification.py
Labels: clean-up, translations

#1396 Automatic update of translations from Crowdin
  nxdrive/data/i18n/i18n-de.json
  nxdrive/data/i18n/i18n-es-ES.json
  nxdrive/data/i18n/i18n-fr.json
  nxdrive/data/i18n/i18n-he.json
  nxdrive/data/i18n/i18n-id.json
  nxdrive/data/i18n/i18n-it.json
  nxdrive/data/i18n/i18n-ja.json
  nxdrive/data/i18n/i18n-nl.json
  nxdrive/data/i18n/i18n-sv-SE.json
Labels: translations

#1397 NXDRIVE-2068: Use any macOS agent for releases
  docs/changes/4.4.2.md
  tools/jenkins/packages.groovy
Labels: QA/CI

#1400 NXDRIVE-2047: Fix functional/test_updater.py
  nxdrive/manager.py
Labels: bugfix

#1403 Automatic update of translations from Crowdin
  nxdrive/data/i18n/i18n-fr.json
  nxdrive/data/i18n/i18n-it.json
Labels: translations

#1406 NXDRIVE-2063: Move tests logic to tox
  .gitignore
  DEVELOPERS.md
  dependabot/config.yml
  docs/changes/4.4.2.md
  docs/deployment.md
  nxdrive/utils.py
  requirements-tests.txt
  setup.cfg
  tests/README.md
  tests/__init__.py
  tests/benchmarks/__init__.py
  tests/benchmarks/empty.ini
  tests/benchmarks/test_safe_filename.py
  tests/functional/test_utils.py
  tests/unit/test_extension_listener.py
  tests/unit/test_utils.py
  tools/check-spell.sh
  tools/deps/requirements-bench.txt
  tools/deps/requirements-cleanup.txt
  tools/deps/requirements-dev.txt
  tools/deps/requirements-integration.txt
  tools/deps/requirements-lint.txt
  tools/deps/requirements-pip.txt
  tools/deps/requirements-spell.txt
  tools/deps/requirements-style.txt
  tools/deps/requirements-tests.txt
  tools/deps/requirements-types.txt
  tools/deps/requirements.txt
  tools/posix/deploy_jenkins_slave.sh
  tools/windows/deploy_jenkins_slave.ps1
  tox.ini
Labels: new-feature, tests

#1409 NXDRIVE-2004: Allow to customize document types in tests
  docs/changes/4.4.2.md
  tests/README.md
  tests/env.py
  tests/old_functional/__init__.py
  tools/jenkins/test_volume_specific.groovy
Labels: improvement, tests

#1411 NXDRIVE-2063: Fix SENTRY_ENV for master
  tests/__init__.py
Labels: bugfix

#1412 NXDRIVE-2063: Fix SENTRY_ENV retrieval command
  tests/__init__.py
Labels: bugfix

#1413 NXDRIVE-2063: Remove pre-commit usage
  tools/posix/deploy_jenkins_slave.sh
Labels: bugfix
