Repository nuxeo/nuxeo-drive, pull requests merged in 2020-03, with the labels that each got.

#1419 Automatic update of translations from Crowdin (nl)
  nxdrive/data/i18n/i18n-nl.json
Labels: translations

#1423 NXDRIVE-2005: Fix more isort issues
  nxdrive/client/proxy.py
  nxdrive/gui/folders_model.py
  tests/benchmarks/test_safe_filename.py
  tests/functional/conftest.py
  tests/functional/test_remote_client.py
  tests/integration/windows/test_cli_sub_command.py
  tests/old_functional/common.py
  tests/old_functional/test_direct_edit.py
  tests/old_functional/test_local_creations.py
  tests/old_functional/test_local_move_and_rename.py
  tests/old_functional/test_permission_hierarchy.py
  tests/old_functional/test_readonly.py
  tests/old_functional/test_synchronization.py
  tests/old_functional/test_transfer.py
  tests/unit/test_objects.py
  tests/unit/test_options.py
Labels: bugfix

#1427 [DEP] NXDRIVE-2078: Behaviors and features flags
  docs/changes/4.4.2.md
  docs/dep/2020-03 Features flags.md
Labels: doc

#1444 Automatic update of translations from Crowdin
  nxdrive/data/i18n/i18n-it.json
  nxdrive/data/i18n/i18n-nl.json
Labels: translations

#1456 Automatic update of translations from Crowdin
  nxdrive/data/i18n/i18n-de.json
  nxdrive/data/i18n/i18n-es-ES.json
  nxdrive/data/i18n/i18n-it.json
  nxdrive/data/i18n/i18n-nl.json
  nxdrive/data/i18n/i18n-sv-SE.json
Labels: translations

#1457 NXDRIVE-2086: Fix mypy issues following the update to mypy 0.770
  docs/changes/4.4.2.md
  nxdrive/client/local/base.py
  nxdrive/client/remote_client.py
  nxdrive/engine/dao/utils.py
  nxdrive/osi/darwin/darwin.py
  nxdrive/osi/linux/linux.py
  nxdrive/updater/darwin.py
  nxdrive/utils.py
Labels: bugfix

#1463 NXDRIVE-2088: Make the synchronization_enabled option effective local…
  docs/changes/4.4.2.md
  nxdrive/manager.py
Labels: bugfix

#1464 NXDRIVE-1901: Fix regression introduced in 4.2.0 about invalid Transf…
  docs/changes/4.4.2.md
  nxdrive/engine/dao/sqlite.py
Labels: bugfix

#1465 NXDRIVE-1866: Check spurious ThreadInterrupt in the conflict resolver
  docs/changes/4.4.2.md
  nxdrive/engine/engine.py
Labels: bugfix

#1468 NXDRIVE-2090: Ask for application restart on specific server config c…
  docs/changes/4.4.2.md
  nxdrive/gui/application.py
  nxdrive/manager.py
  nxdrive/poll_workers.py
  nxdrive/updater/base.py
Labels: improvement

#1445 NXDRIVE-374: [GNU/Linux] Use file system decorations
  docs/changes/4.4.2.md
  docs/icon_overlay.md
  nxdrive/data/icons/overlay/linux/badge_conflicted.svg
  nxdrive/data/icons/overlay/linux/badge_error.svg
  nxdrive/data/icons/overlay/linux/badge_locked.svg
  nxdrive/data/icons/overlay/linux/badge_synced.svg
  nxdrive/data/icons/overlay/linux/badge_syncing.svg
  nxdrive/data/icons/overlay/linux/badge_unsynced.svg
  nxdrive/data/icons/overlay/nautilus/emblem-drive_conflict.icon
  nxdrive/data/icons/overlay/nautilus/emblem-drive_conflict.png
  nxdrive/data/icons/overlay/nautilus/emblem-drive_locked.icon
  nxdrive/data/icons/overlay/nautilus/emblem-drive_locked.png
  nxdrive/data/icons/overlay/nautilus/emblem-drive_not_sync.icon
  nxdrive/data/icons/overlay/nautilus/emblem-drive_not_sync.png
  nxdrive/data/icons/overlay/nautilus/emblem-drive_offline.icon
  nxdrive/data/icons/overlay/nautilus/emblem-drive_offline.png
  nxdrive/data/icons/overlay/nautilus/emblem-drive_pending.icon
  nxdrive/data/icons/overlay/nautilus/emblem-drive_pending.png
  nxdrive/data/icons/overlay/nautilus/emblem-drive_sync.icon
  nxdrive/data/icons/overlay/nautilus/emblem-drive_sync.png
  nxdrive/engine/watcher/local_watcher.py
  nxdrive/osi/extension.py
  nxdrive/osi/linux/linux.py
Labels: GNU/Linux, new-feature

#1476 NXDRIVE-2091: Wait for the server configuration before starting features
  docs/changes/4.4.2.md
  nxdrive/autolocker.py
  nxdrive/direct_edit.py
  nxdrive/engine/engine.py
  nxdrive/manager.py
  nxdrive/notification.py
  nxdrive/poll_workers.py
  tests/old_functional/__init__.py
  tests/unit/test_autolock.py
Labels: improvement

#1477 NXDRIVE-1866: The conflict resolver should not fail when the Engine i…
  nxdrive/engine/engine.py
  tests/functional/test_engine.py
Labels: bugfix

#1481 NXDRIVE-1869: Handle pair state resolved-modified as conflicted
  docs/changes/4.4.2.md
  nxdrive/engine/dao/sqlite.py
Labels: bugfix

#1472 NXDRIVE-2075: [Windows] Use the long path prefix for Engine.download_dir
  docs/changes/4.4.2.md
  nxdrive/client/remote_client.py
  nxdrive/engine/dao/sqlite.py
  nxdrive/engine/engine.py
  nxdrive/gui/view.py
  nxdrive/objects.py
  tests/resources/test_engine_migration_8.db
  tests/unit/test_engine_dao.py
Labels: Windows, bugfix

#1483 NXDRIVE-2092: Make the JUnit merge script universal
  docs/changes/4.4.2.md
  tools/jenkins/junit/merge.py
  tools/posix/deploy_jenkins_slave.sh
  tools/windows/deploy_jenkins_slave.ps1
Labels: improvement, tests

#1487 NXDRIVE-2096: Add __version__ to ease change tracking
  tools/jenkins/junit/merge.py
Labels: improvement

#1488 NXDRIVE-2100: Clean-up code smells found by Sourcery
  docs/changes/4.4.2.md
  nxdrive/__main__.py
  nxdrive/client/remote_client.py
  nxdrive/direct_edit.py
  nxdrive/engine/dao/sqlite.py
  nxdrive/engine/dao/utils.py
  nxdrive/engine/engine.py
  nxdrive/engine/processor.py
  nxdrive/engine/queue_manager.py
  nxdrive/engine/watcher/local_watcher.py
  nxdrive/engine/workers.py
  nxdrive/fatal_error.py
  nxdrive/gui/application.py
  nxdrive/gui/folders_model.py
  nxdrive/gui/folders_treeview.py
  nxdrive/manager.py
  nxdrive/objects.py
  nxdrive/options.py
  nxdrive/osi/darwin/files.py
  nxdrive/osi/extension.py
  nxdrive/osi/windows/windows.py
  nxdrive/updater/base.py
  nxdrive/updater/utils.py
  tests/pytest_random.py
  tools/changelog.py
  tools/cleanup_application_tree.py
  tools/osx/icon_extractor.py
  tools/osx/notarize.py
  tools/scripts/check_update_process.py
Labels: improvement

#1521 Automatic update of translations from Crowdin
  nxdrive/data/i18n/i18n-de.json
  nxdrive/data/i18n/i18n-ja.json
Labels: translations
