Repository nuxeo/nuxeo-drive, pull requests merged in 2020-05, with the labels that each got.

#1636 NXDRIVE-2132: Do not allow Direct Edit on proxies
  docs/changes/4.4.3.md
  nxdrive/data/i18n/i18n.json
  nxdrive/direct_edit.py
  nxdrive/objects.py
  tests/old_functional/__init__.py
  tests/old_functional/test_direct_edit.py
Labels: bugfix

#1644 NXDRIVE-2127: Reduce crashes without informations
  tests/old_functional/common.py
Labels: bugfix, tests

#1655 Automatic update of translations from Crowdin
  nxdrive/data/i18n/i18n-de.json
  nxdrive/data/i18n/i18n-es-ES.json
  nxdrive/data/i18n/i18n-fr.json
  nxdrive/data/i18n/i18n-he.json
  nxdrive/data/i18n/i18n-id.json
  nxdrive/data/i18n/i18n-it.json
  nxdrive/data/i18n/i18n-ja.json
  nxdrive/data/i18n/i18n-nl.json
  nxdrive/data/i18n/i18n-sv-SE.json
Labels: translations

#1658 Add missing importlib-metadata and zipp modules following markdown up…
  docs/changes/4.4.3.md
  tools/deps/requirements-lint.txt
  tools/deps/requirements.txt
Labels: dependencies, tests

#1661 /NXDRIVE-2016: Upgrade Python from 3.7.4 to 3.7.7
  docs/changes/4.4.3.md
  docs/deployment.md
  docs/support.md
  tools/jenkins/packages.groovy
  tools/posix/deploy_jenkins_slave.sh
  tools/windows/deploy_jenkins_slave.ps1
  tools/windows/scripts/envvars.bat
Labels: QA/CI, bugfix, improvement

#1662 NXDRIVE-2016: Protect the Docker image 3.7.7
  tools/jenkins/docker_build.groovy
Labels: QA/CI

#1659 NXDRIVE-1848: Remove dependency on rfc3987 for URL parsing
  docs/changes/4.4.3.md
  nxdrive/utils.py
  tests/unit/test_utils.py
  tools/deps/requirements.txt
Labels: clean-up, improvement

#1656 NXDRIVE-2133: [macOS] Skip errors on file creation time modification
  docs/changes/4.4.3.md
  nxdrive/client/local/darwin.py
Labels: bugfix, macOS

#1654 NXDRIVE-2150: Change the disk space usage border color
  docs/changes/4.4.3.md
  nxdrive/data/qml/AccountsTab.qml
Labels: improvement

#1657 NXDRIVE-2146: Do not package Qt5RemoteObjects DLL and shared library
  docs/changes/4.4.3.md
  tools/cleanup_application_tree.py
Labels: clean-up

#1672 NXDRIVE-2169: [Windows] psutil is crashing the application
  docs/changes/4.4.3.md
  tools/deps/requirements.txt
Labels: bugfix, dependencies

#1674 NXDRIVE-2169: Enforce Python 32-bit on the CI
  .github/workflows/dead_code.yml
  .github/workflows/lint.yml
  .github/workflows/spell.yml
  .github/workflows/style.yml
  .github/workflows/translations.yml
  .github/workflows/types.yml
  .github/workflows/unit_tests.yml
Labels: QA/CI, bugfix

#1675 NXDRIVE-2137: Bump the version to 4.4.4
  docs/changes.md
  docs/changes/4.4.3.md
  docs/changes/4.4.4.md
  nxdrive/__init__.py
Labels: Release

#1676 NXDRIVE-2169: Enforce Python 32-bit on the CI (it is Windows only)
  .github/workflows/dead_code.yml
  .github/workflows/lint.yml
  .github/workflows/spell.yml
  .github/workflows/style.yml
  .github/workflows/translations.yml
  .github/workflows/types.yml
  .github/workflows/unit_tests.yml
Labels: QA/CI, bugfix

#1686 NXDRIVE-2132: Automatic update of translations from Crowdin
  nxdrive/data/i18n/i18n-de.json
  nxdrive/data/i18n/i18n-es-ES.json
  nxdrive/data/i18n/i18n-fr.json
  nxdrive/data/i18n/i18n-it.json
  nxdrive/data/i18n/i18n-ja.json
  nxdrive/data/i18n/i18n-nl.json
  nxdrive/data/i18n/i18n-sv-SE.json
Labels: translations

#1687 NXDRIVE-2158: Review the warning message on conflict popup
  docs/changes/4.4.4.md
  nxdrive/data/i18n/i18n.json
Labels: improvement

#1689 NXDRIVE-2170: Fix new errors found by codespell 1.17.0
  docs/changes/4.4.4.md
  nxdrive/engine/dao/sqlite.py
  nxdrive/exceptions.py
  tests/old_functional/test_encoding.py
  tools/changelog.py
  tools/spell.whitelist
  tools/whitelist.py
Labels: bugfix

#1691 NXDRIVE-2160: Lower logging level of "Error while stopping FinderSync"
  docs/changes/4.4.4.md
  nxdrive/osi/darwin/darwin.py
Labels: improvement

#1693 NXDRIVE-2162: Enforce disk space retrieval robustness
  docs/changes/4.4.4.md
  nxdrive/data/qml/NewAccountPopup.qml
  nxdrive/gui/api.py
  nxdrive/utils.py
Labels: bugfix

#1697 NXDRIVE-2171: Disable the cache on Windows (still not possible)
  .github/workflows/unit_tests.yml
Labels: QA/CI, Windows, bugfix

#1688 NXDRIVE-2155: Improvements on the main popup
  docs/changes/4.4.4.md
  nxdrive/data/i18n/i18n.json
  nxdrive/gui/folders_dialog.py
Labels: improvement

#1700 NXDRIVE-2158: Automatic update of translations from Crowdin
  nxdrive/data/i18n/i18n-he.json
  nxdrive/data/i18n/i18n-id.json
Labels: translations

#1701 NXDRIVE-2155: Automatic update of translations from Crowdin
  nxdrive/data/i18n/i18n-de.json
  nxdrive/data/i18n/i18n-es-ES.json
  nxdrive/data/i18n/i18n-fr.json
  nxdrive/data/i18n/i18n-he.json
  nxdrive/data/i18n/i18n-id.json
  nxdrive/data/i18n/i18n-it.json
  nxdrive/data/i18n/i18n-ja.json
  nxdrive/data/i18n/i18n-nl.json
  nxdrive/data/i18n/i18n-sv-SE.json
Labels: translations

#1704 NXDRIVE-2175: Fix test_translator.py
  tests/unit/test_translator.py
Labels: bugfix, tests
