Repository nuxeo/nuxeo-drive, pull requests merged in 2020-09, with the labels that each got.

#1978 NXDRIVE-2294: Improve logging of the transfer speed
  docs/changes/4.4.5.md
  nxdrive/client/remote_client.py
Labels: improvement

#1979 NXDRIVE-2252: Small logging improvement for temporary blocked items
  nxdrive/engine/blocklist_queue.py
Labels: improvement

#1980 NXDRIVE-2245: [Windows] Fix test_orphan_should_unlock()
  docs/changes/4.4.5.md
  tests/old_functional/test_direct_edit.py
Labels: clean-up

#1981 NXDRIVE-2255: [Direct Transfer] Update the transfer list according to…
  docs/changes/4.4.5.md
  nxdrive/client/uploader/__init__.py
  nxdrive/engine/activity.py
  nxdrive/gui/api.py
  nxdrive/gui/view.py
Labels: QML, bugfix

#1984 NXDRIVE-2019: Skip tests when the new API is not available
  tests/old_functional/test_direct_transfer.py
Labels: improvement, tests

#1986 NXDRIVE-1888: Improve database queries to anihile any deadlock
  docs/changes/4.4.5.md
  nxdrive/engine/dao/sqlite.py
Labels: improvement

#1987 NXDRIVE-2259: Fix grep argument
  tools/cleanup.sh
Labels: QA/CI, bugfix

#1944 NXDRIVE-2276: [Direct Transfer] Introduce the notion of sessions
  docs/changes/4.4.5.md
  nxdrive/engine/dao/sqlite.py
  nxdrive/engine/engine.py
  nxdrive/engine/processor.py
  nxdrive/objects.py
  tests/old_functional/test_direct_transfer.py
  tests/resources/databases/engine_migration_15.db
  tests/unit/test_engine_dao.py
Labels: new-feature

#1988 NXDRIVE-2300: [Direct Transfer] Update the sync counter in real-time
  docs/changes/4.4.5.md
  nxdrive/data/qml/DirectTransfer.qml
  nxdrive/data/qml/Main.qml
  nxdrive/data/qml/TransferItem.qml
  nxdrive/engine/engine.py
  nxdrive/gui/application.py
Labels: QML, improvement

#1989 NXDRIVE-2156: [Direct Transfer] Add a notification once transfer session is complete
  docs/changes/4.4.5.md
  nxdrive/data/i18n/i18n.json
  nxdrive/engine/engine.py
  nxdrive/engine/processor.py
  nxdrive/notification.py
Labels: improvement

#1992 NXDRIVE-2301: [Direct Transfer] Handle a transfer cancel during sessions
  docs/changes/4.4.5.md
  nxdrive/engine/dao/sqlite.py
  nxdrive/engine/engine.py
  nxdrive/engine/processor.py
  tests/old_functional/test_direct_transfer.py
Labels: improvement

#1993 NXDRIVE-2156: [Direct Transfer] Cleanup useless notification
  docs/changes/4.4.5.md
  nxdrive/engine/engine.py
  nxdrive/engine/processor.py
  nxdrive/notification.py
Labels: clean-up

#1994 NXDRIVE-2156: Add tests for Direct Transfer sessions notifications
  tests/old_functional/common.py
  tests/old_functional/test_direct_transfer.py
Labels: improvement, tests

#1997 NXDRIVE-2298: Improve large file upload resiliency
  docs/changes/4.4.5.md
  nxdrive/client/uploader/__init__.py
  nxdrive/client/uploader/direct_transfer.py
  tools/skiplist.py
Labels: improvement

#1999 NXDRIVE-2302: Use an adapter to store path-like objects in the database
  docs/changes/4.4.5.md
  nxdrive/engine/dao/sqlite.py
  tests/unit/test_engine_dao.py
Labels: improvement

#1998 NXDRIVE-2301: [Direct Transfer] Fix cancel_upload on Windows
  nxdrive/engine/engine.py
  tests/old_functional/test_direct_transfer.py
Labels: bugfix, tests

#2000 NXDRIVE-1888: Ignore SQLite WAL journal mode files from the repository
  .gitignore
Labels: clean-up

#2001 NXDRIVE-2276: Cleanup useless str cast
  nxdrive/engine/dao/sqlite.py
Labels: clean-up

#2002 NXDRIVE-2268: Fix a regression where the file would be uploaded again
  nxdrive/client/uploader/direct_transfer.py
  nxdrive/engine/processor.py
Labels: bugfix

#2004 NXDRIVE-2019: [Direct Transfer] Fix tests
  tests/old_functional/test_direct_transfer.py
Labels: bugfix, tests

#2005 NXDRIVE-2302: Fix SQlite path adapter
  nxdrive/engine/dao/sqlite.py
Labels: bugfix

#2006 NXDRIVE-2303: Fix useless reports generated in tests
  docs/changes/4.4.5.md
  tests/old_functional/common.py
  tests/old_functional/test_context_menu.py
  tests/old_functional/test_direct_edit.py
  tests/old_functional/test_direct_transfer.py
  tests/old_functional/test_permission_hierarchy.py
  tests/old_functional/test_volume.py
Labels: bugfix, tests

#2010 NXDRIVE-2194: Force refetch of the server's config on Direct Edit com…
  docs/changes/4.4.5.md
  nxdrive/data/i18n/i18n.json
  nxdrive/gui/application.py
  nxdrive/manager.py
Labels: bugfix

#2012 NXDRIVE-2307: Add the disabled_file_integrity_check option to disable…
  docs/changes/4.4.5.md
  docs/configuration.md
  nxdrive/client/remote_client.py
  nxdrive/options.py
  tests/old_functional/test_direct_edit.py
Labels: new-feature

#2014 NXDRIVE-2304: [Direct Transfer] Do not allow to upload in documents w…
  docs/changes/4.4.5.md
  nxdrive/gui/folders_model.py
Labels: bugfix

#2009 NXDRIVE-2289: [Direct Transfer] Remember the last selected local folder
  docs/changes/4.4.5.md
  nxdrive/engine/engine.py
  nxdrive/gui/folders_dialog.py
  tests/old_functional/test_direct_transfer.py
Labels: improvement

#2015 NXDRIVE-2242: Release 4.4.5
  docs/changes.md
  docs/changes/4.4.5.md
Labels: Release

#2016 NXDRIVE-2243: Bump the version to 4.4.6
  docs/changes.md
  docs/changes/4.4.6.md
  nxdrive/__init__.py
Labels: Release

#2027 NXDRIVE-2305: Do not display the filters window on new account if the synchronization is disabled
  docs/changes/4.4.6.md
  nxdrive/gui/api.py
Labels: QML, improvement

#2050 NXDRIVE-2314: Remove more files from the final package
  docs/changes/4.4.6.md
  tools/cleanup_application_tree.py
  tools/posix/deploy_ci_agent.sh
  tools/windows/deploy_ci_agent.ps1
Labels: Release, improvement

#2051 NXDRIVE-2314: Remove even more files from the final package
  tools/cleanup_application_tree.py
Labels: Release, improvement

#2052 NXDRIVE-2315: Do not show the progress bar on module installation
  docs/changes/4.4.6.md
  tools/posix/deploy_ci_agent.sh
  tools/windows/deploy_ci_agent.ps1
Labels: QA/CI, improvement

#2024 NXDRIVE-2076: Change the cursor on click on new account connect button
  docs/changes/4.4.6.md
  nxdrive/gui/application.py
Labels: QML, improvement

#2028 NXDRIVE-2306: Do not validate again settings when the value did not change
  docs/changes/4.4.6.md
  nxdrive/data/qml/ChannelPopup.qml
  nxdrive/data/qml/DeletionPopup.qml
  nxdrive/data/qml/LogLevelPopup.qml
  nxdrive/data/qml/ProxyPopup.qml
Labels: QML, improvement
