Repository nuxeo/nuxeo-drive, pull requests merged in 2021-02, with the labels that each got.

#2436 NXDRIVE-2487: Always enable Sentry on alpha versions or when the app …
  docs/changes/5.0.0.md
  nxdrive/gui/application.py
  nxdrive/options.py
Labels: improvement

#2434 NXDRIVE-2351: Align Colors
  docs/changes/5.0.0.md
  nxdrive/data/qml/AboutTab.qml
  nxdrive/data/qml/AccountsTab.qml
  nxdrive/data/qml/Alert.qml
  nxdrive/data/qml/ChannelPopup.qml
  nxdrive/data/qml/ConfirmPopup.qml
  nxdrive/data/qml/Conflicts.qml
  nxdrive/data/qml/DirectTransfer.qml
  nxdrive/data/qml/FeaturesTab.qml
  nxdrive/data/qml/FileCard.qml
  nxdrive/data/qml/GeneralTab.qml
  nxdrive/data/qml/IconLabel.qml
  nxdrive/data/qml/Link.qml
  nxdrive/data/qml/NewAccountPopup.qml
  nxdrive/data/qml/NuxeoButton.qml
  nxdrive/data/qml/NuxeoCheckBox.qml
  nxdrive/data/qml/NuxeoComboBox.qml
  nxdrive/data/qml/NuxeoInput.qml
  nxdrive/data/qml/NuxeoPopup.qml
  nxdrive/data/qml/NuxeoProgressBar.qml
  nxdrive/data/qml/NuxeoRadioButton.qml
  nxdrive/data/qml/NuxeoSwitch.qml
  nxdrive/data/qml/NuxeoToolTip.qml
  nxdrive/data/qml/SessionItem.qml
  nxdrive/data/qml/SettingsTab.qml
  nxdrive/data/qml/Systray.qml
  nxdrive/data/qml/SystrayFile.qml
  nxdrive/data/qml/SystrayMenu.qml
  nxdrive/data/qml/SystrayMenuItem.qml
  nxdrive/data/qml/SystrayStatus.qml
  nxdrive/data/qml/SystrayTransfer.qml
  nxdrive/data/qml/TransferItem.qml
  nxdrive/gui/application.py
Labels: QML

#2437 NXDRIVE-2501: Fix the "Open remote" action on conflicted folderish do…
  docs/changes/5.0.0.md
  nxdrive/data/qml/FileCard.qml
Labels: bugfix

#2444 NXDRIVE-1359: Reduce the complexity of Processor._execute()
  docs/changes/5.0.0.md
  nxdrive/engine/processor.py
Labels: clean-up

#2445 NXDRIVE-2351: Missing bi-color for sync items progress bar
  nxdrive/data/qml/SystrayTransfer.qml
Labels: QML, bugfix

#2447 NXDRIVE-1359: Fix missing raise on Direct Transfer error
  nxdrive/engine/processor.py
Labels: bugfix

#2451 NXDRIVE-2509: Remove old report before starting a test
  docs/changes/5.0.0.md
  tests/old_functional/common.py
Labels: improvement, tests

#2452 NXDRIVE-2513: Always enable DEBUG log level on alpha versions or when…
  docs/changes/5.0.0.md
  nxdrive/commandline.py
  nxdrive/data/qml/LogLevelPopup.qml
  nxdrive/logging_config.py
  nxdrive/manager.py
  nxdrive/options.py
Labels: improvement

#2453 NXDRIVE-2511: Use constants for audit events
  docs/changes/5.0.0.md
  nxdrive/engine/watcher/constants.py
  nxdrive/engine/watcher/remote_watcher.py
  tests/old_functional/test_local_share_move_folders.py
  tests/old_functional/test_remote_changes.py
  tools/skiplist.py
Labels: improvement

#2459 NXDRIVE-2515: Log the previous version when displaying release notes
  docs/changes/5.0.0.md
  nxdrive/gui/application.py
Labels: improvement

#2460 NXDRIVE-2351: Fix left 'orange' color
  nxdrive/data/qml/Systray.qml
Labels: QML, bugfix

#2466 NXDRIVE-2518: Drop support for macOS 10.12 (Sierra)
  docs/changes/5.0.0.md
  docs/support.md
  nxdrive/fatal_error.py
Labels: improvement

#2467 NXDRIVE-2479: Improve S3 class import
  nxdrive/client/uploader/__init__.py
  nxdrive/engine/processor.py
Labels: improvement

#2449 NXDRIVE-2442: Implement mutual TLS authentication
  docs/changes/5.0.0.md
  docs/configuration.md
  nxdrive/client/proxy.py
  nxdrive/client/remote_client.py
  nxdrive/commandline.py
  nxdrive/data/i18n/i18n.json
  nxdrive/engine/engine.py
  nxdrive/exceptions.py
  nxdrive/gui/api.py
  nxdrive/gui/application.py
  nxdrive/manager.py
  nxdrive/options.py
  nxdrive/utils.py
Labels: new-feature

#2475 NXDRIVE-2015: Remove the quick patch made for NXDRIVE-2482
  nxdrive/updater/utils.py
Labels: clean-up

#2476 NXDRIVE-2525: Do not try to list parts when an upload was already com…
  docs/changes/5.0.0.md
  nxdrive/client/uploader/__init__.py
Labels: bugfix

#2477 NXDRIVE-2524: [GNU/Linux] WAL journal mode cause manager database corruption
  docs/changes/5.0.0.md
  nxdrive/engine/dao/sqlite.py
Labels: GNU/Linux, bugfix

#2478 NXDRIVE-2526: Light icon option is not saved anymore
  docs/changes/5.0.0.md
  nxdrive/options.py
Labels: bugfix

#2479 NXDRIVE-2524: Adjust force_commit()
  nxdrive/engine/dao/sqlite.py
Labels: improvement

#2480 NXDRIVE-2523: Install exception handlers to catch crash details, if p…
  nxdrive/__main__.py
  nxdrive/report.py
Labels: improvement

#2484 Revert "NXDRIVE-2523: Install exception handlers to catch crash detai…
  nxdrive/__main__.py
  nxdrive/report.py
Labels: clean-up

#2485 NXDRIVE-2507: Release 5.0.0
  docs/changes/5.0.0.md
  docs/support.md
Labels: Release

#2489 NXDRIVE-2507: Bump the version number to 5.0.1
  docs/changes.md
  docs/changes/5.0.1.md
  nxdrive/__init__.py
Labels: Release

#2461 NXDRIVE-2382: [Direct Transfer] Add CSV export capability for sessions
  docs/changes/5.0.1.md
  nxdrive/client/uploader/direct_transfer.py
  nxdrive/data/i18n/i18n.json
  nxdrive/data/qml/GeneralTab.qml
  nxdrive/data/qml/Link.qml
  nxdrive/data/qml/SessionItem.qml
  nxdrive/engine/dao/sqlite.py
  nxdrive/engine/engine.py
  nxdrive/gui/api.py
  nxdrive/gui/application.py
  nxdrive/gui/view.py
  nxdrive/manager.py
  nxdrive/session_csv.py
  tests/functional/test_engine.py
  tests/unit/test_session_csv.py
  tools/skiplist.py
Labels: new-feature

#2492 NXDRIVE-2529: Upgrade from Python 3.9.1 to 3.9.2
  docs/changes/5.0.1.md
  tools/linux/travis.sh
  tools/posix/deploy_ci_agent.sh
  tools/windows/deploy_ci_agent.ps1
Labels: QA/CI, improvement

#2495 NXDRIVE-2531: Finish refactoring of Processor._execute() for Direct T…
  docs/changes/5.0.1.md
  nxdrive/engine/processor.py
Labels: bugfix

#2500 NXDRIVE-2523: Clean-up how cursor is being fetched in delete_local_st…
  nxdrive/engine/dao/sqlite.py
Labels: clean-up

#2502 NXDRIVE-2537: Enable the Direct Transfer feature by default
  docs/changes/5.0.1.md
  nxdrive/feature.py
  tests/functional/test_server_options.py
Labels: improvement

#2501 NXDRIVE-2382: Prevent multiple asynchronous CSV generation
  docs/changes/5.0.1.md
  nxdrive/data/qml/SessionItem.qml
  nxdrive/engine/dao/sqlite.py
  nxdrive/gui/application.py
  nxdrive/manager.py
Labels: bugfix

#2508 NXDRIVE-2382: Use CSV icon instead of link
  nxdrive/data/qml/SessionItem.qml
  nxdrive/data/qml/icon-font/Icon.js
  nxdrive/data/qml/icon-font/materialdesignicons-webfont.ttf
Labels: QML, improvement
