Repository nuxeo/nuxeo-drive, pull requests merged in 2021-07, with the labels that each got.

#2883 NXDRIVE-2708: Handle removed folder when dequeuing local folder scan
  docs/changes/5.2.3.md
  nxdrive/engine/watcher/local_watcher.py
Labels: bugfix

#2884 NXDRIVE-2708: Resume the synchronization if it was paused
  nxdrive/engine/watcher/local_watcher.py
Labels: bugfix

#2885 NXDRIVE-2709: Handle unauthorized error when adding the top-level syn…
  docs/changes/5.2.3.md
  nxdrive/engine/engine.py
Labels: bugfix

#2886 NXDRIVE-2710: Fix fatal error when guessing the copy-share link of a …
  docs/changes/5.2.3.md
  nxdrive/manager.py
Labels: bugfix

#2887 NXDRIVE-2704: Do not send metrics on postponed actions
  nxdrive/engine/processor.py
  nxdrive/engine/queue_manager.py
Labels: improvement

#2894 NXDRIVE-2229: [Direct Transfer] Use a proper NXQL query to fetch serv…
  docs/changes/5.2.3.md
  nxdrive/gui/folders_model.py
Labels: improvement

#2896 NXDRIVE-2674: [Direct Transfer] Fetch all children of a selected folder
  docs/changes/5.2.3.md
  nxdrive/gui/folders_model.py
Labels: bugfix

#2897 NXDRIVE-2716: Fix the release job not bumping the alpha version
  .github/workflows/release.yml
  docs/changes/5.2.3.md
Labels: QA/CI, bugfix

#2902 NXDRIVE-2716: Fix
  .github/workflows/release.yml
Labels: QA/CI, bugfix

#2903 NXDRIVE-2714: Can't start on macOS when the OS locale is english
  docs/changes/5.2.3.md
  nxdrive/__main__.py
Labels: bugfix

#2904 NXDRIVE-2717: Use idempotent requests
  docs/changes/5.2.3.md
  docs/configuration.md
  nxdrive/client/uploader/__init__.py
  nxdrive/options.py
  tests/old_functional/test_transfer.py
Labels: improvement

#2880 NXDRIVE-2695: Better handling of custom SSL certificates
  docs/changes/5.2.3.md
  nxdrive/client/proxy.py
  nxdrive/engine/engine.py
  nxdrive/gui/api.py
  nxdrive/gui/application.py
  nxdrive/manager.py
  nxdrive/utils.py
  tests/unit/test_utils.py
  tools/deps/requirements-tests.txt
Labels: improvement

#2906 NXDRIVE-2718: Release 5.2.3
  docs/changes.md
  docs/changes/5.2.3.md
Labels: Release

#2907 NXDRIVE-2781: Bump the version to 5.2.4
  docs/changes.md
  docs/changes/5.2.4.md
  nxdrive/__init__.py
Labels: Release

#2908 NXDRIVE-2719: Fix handling of the ca-bundle parameter
  docs/changes/5.2.4.md
  nxdrive/options.py
  nxdrive/utils.py
  tests/unit/test_utils.py
Labels: bugfix

#2909 NXDRIVE-2720: Release 5.2.4
  docs/changes.md
  docs/changes/5.2.4.md
Labels: Release

#2910 NXDRIVE-2720: Bump the version to 5.2.5
  docs/changes.md
  docs/changes/5.2.5.md
  nxdrive/__init__.py
Labels: Release

#2911 NXDRIVE-2721: [Windows] Correctly handle WinError 32
  docs/changes/5.2.5.md
  nxdrive/engine/queue_manager.py
Labels: Windows, bugfix

#2905 NXDRIVE-2699: Document is locked even when told not to do so
  docs/changes/5.2.5.md
  nxdrive/direct_edit.py
  nxdrive/manager.py
  tests/old_functional/test_direct_edit.py
Labels: bugfix

#2913 NXDRIVE-2703: Forward proxy settings to the OAuth2 subclient
  docs/changes/5.2.5.md
  nxdrive/auth/oauth2.py
  nxdrive/gui/api.py
Labels: improvement

#2914 NXDRIVE-2702: Document is never locked when the local folder is a UNC…
  docs/changes/5.2.5.md
  nxdrive/manager.py
  nxdrive/utils.py
Labels: bugfix

#2920 NXDRIVE-2694: Review handling of sync roots
  docs/changes/5.2.5.md
  docs/configuration.md
  nxdrive/client/remote_client.py
  nxdrive/engine/watcher/remote_watcher.py
  nxdrive/options.py
  nxdrive/utils.py
  tests/functional/test_remote_client.py
  tests/unit/test_options.py
  tests/unit/test_utils.py
Labels: improvement

#2940 NXDRIVE-2725: Ignore ca-bundle option when no ssl verification is done
  docs/changes/5.2.5.md
  nxdrive/commandline.py
  nxdrive/gui/api.py
  nxdrive/utils.py
  tests/unit/test_utils.py
Labels: bugfix

#2958 NXDRIVE-2713: Add more padding around Device ID info
  docs/changes/5.2.5.md
  nxdrive/data/qml/AboutTab.qml
  nxdrive/gui/application.py
Labels: QML, improvement
