Repository nuxeo/nuxeo-drive, pull requests merged in 2021-05, with the labels that each got.

#2672 NXDRIVE-826: Fix token renewal
  nxdrive/gui/api.py
Labels: bugfix

#2671 NXDRIVE-2604: Change tabs order on Settings screen
  docs/changes/5.1.2.md
  nxdrive/data/i18n/i18n.json
  nxdrive/data/qml/Settings.qml
  nxdrive/data/qml/SystrayMenu.qml
  nxdrive/gui/application.py
  nxdrive/gui/systray.py
Labels: QML, improvement

#2674 NXDRIVE-2612: Save all features state in the local configuration file
  docs/changes/5.1.2.md
  nxdrive/manager.py
  nxdrive/utils.py
  tests/functional/test_server_options.py
Labels: improvement

#2679 NXDRIVE-2630: [Windows] Cannot use UNC paths for the nxdrive_home par…
  docs/changes/5.1.2.md
  nxdrive/utils.py
Labels: Windows, bugfix

#2680 NXDRIVE-2633: Do not watch the local folder parent
  docs/changes/5.1.2.md
  nxdrive/engine/watcher/local_watcher.py
Labels: bugfix

#2684 NXDRIVE-2635: [Direct Transfer] Do not follow symlinks
  docs/changes/5.1.2.md
  nxdrive/utils.py
  tests/unit/test_utils.py
Labels: bugfix

#2685 NXDRIVE-2636: Handle HTTP 405 (Method Not Allowed) errors
  docs/changes/5.1.2.md
  nxdrive/engine/processor.py
Labels: bugfix

#2688 NXDRIVE-2629: Upgrade from Python 3.9.4 to 3.9.5
  docs/changes/5.1.2.md
  docs/deployment.md
  docs/support.md
  tools/linux/travis.sh
  tools/posix/deploy_ci_agent.sh
  tools/windows/deploy_ci_agent.ps1
Labels: improvement

#2689 NXDRIVE-2627: Add support for OpenID Connect Discovery
  docs/changes/5.1.2.md
  docs/configuration.md
  nxdrive/auth/oauth2.py
  nxdrive/options.py
Labels: new-feature

#2700 NXDRIVE-2632: [Direct Transfer] Add the dt_hide_personal_space option…
  docs/changes/5.1.2.md
  docs/configuration.md
  nxdrive/gui/folders_model.py
  nxdrive/options.py
Labels: new-feature

#2701 NXDRIVE-2403: Allow to specify the OAuth2 scope
  docs/changes/5.1.2.md
  nxdrive/auth/oauth2.py
  nxdrive/options.py
Labels: new-feature

#2697 NXDRIVE-2618: Improve Accounts tab on Settings
  docs/changes/5.1.2.md
  nxdrive/data/i18n/i18n.json
  nxdrive/data/qml/AccountsTab.qml
  nxdrive/data/qml/EngineAccountItem.qml
  nxdrive/data/qml/SynchronizationTab.qml
Labels: QML, improvement

#2713 NXDRIVE-2332: Poll for the batchId on a regular basic to prevent its …
  nxdrive/client/uploader/__init__.py
Labels: improvement

#2704 NXDRIVE-2618: Add some small graphical improvements
  docs/changes/5.1.2.md
  nxdrive/data/i18n/i18n.json
  nxdrive/data/qml/EngineAccountItem.qml
  nxdrive/data/qml/EngineSyncItem.qml
  nxdrive/engine/engine.py
  nxdrive/gui/view.py
Labels: QML, bugfix

#2715 NXDRIVE-2622: Expand vars in path-like options
  nxdrive/options.py
Labels: bugfix

#2716 NXDRIVE-2639: Fix locale settings persistence
  docs/changes/5.1.2.md
  nxdrive/manager.py
Labels: bugfix

#2719 NXDRIVE-2618: Fix accounts links clickable area
  nxdrive/data/qml/AccountsTab.qml
  nxdrive/data/qml/Link.qml
Labels: QML, bugfix

#2721 NXDRIVE-2616: Release 5.2.0
  docs/changes.md
  docs/changes/5.2.0.md
  docs/configuration.md
  nxdrive/__init__.py
  nxdrive/feature.py
  nxdrive/manager.py
  nxdrive/options.py
Labels: Release

#2722 NXDRIVE-2616: Bump the version to 5.2.1
  docs/changes.md
  docs/changes/5.2.0.md
  docs/changes/5.2.1.md
  nxdrive/__init__.py
Labels: Release

#2726 NXDRIVE-2217: Use the PRAGMA user_version to store the database version
  docs/changes/5.2.1.md
  nxdrive/engine/dao/sqlite.py
Labels: improvement

#2727 Fix missing colorama requirement on Windows
  tools/deps/requirements-pip.txt
Labels: Windows, dependencies

#2728 NXDRIVE-2643: Start the Engine right after account addition when the …
  docs/changes/5.2.1.md
  nxdrive/gui/api.py
Labels: bugfix

#2731 NXDRIVE-2644: Check extended attributes support when adding account
  docs/changes/5.2.1.md
  nxdrive/data/i18n/i18n.json
  nxdrive/engine/engine.py
  nxdrive/exceptions.py
  nxdrive/gui/api.py
  nxdrive/manager.py
Labels: bugfix

#2733 NXDRIVE-2645: Gracefully handle processor releasing issues
  docs/changes/5.2.1.md
  nxdrive/engine/dao/sqlite.py
Labels: bugfix

#2737 NXDRIVE-2217: New migration to add the PRAGMA
  docs/changes/5.2.1.md
  nxdrive/engine/dao/sqlite.py
  tests/unit/test_proxy.py
Labels: improvement

#2739 NXDRIVE-2641: Disable local folder checks and creation when the sync …
  docs/changes/5.2.1.md
  nxdrive/engine/dao/sqlite.py
  nxdrive/engine/engine.py
  nxdrive/gui/application.py
  nxdrive/manager.py
  tests/functional/test_behavior.py
  tests/functional/test_context_menu.py
  tests/functional/test_server_options.py
  tests/old_functional/common.py
  tests/old_functional/test_direct_edit.py
Labels: bugfix

#2740 NXDRIVE-2644: Clean-up extended attributes support
  docs/changes/5.2.1.md
  nxdrive/data/i18n/i18n.json
  nxdrive/engine/engine.py
  nxdrive/exceptions.py
  nxdrive/gui/api.py
  nxdrive/manager.py
  nxdrive/osi/__init__.py
  nxdrive/osi/darwin/darwin.py
  nxdrive/osi/windows/windows.py
Labels: clean-up

#2742 NXDRIVE-2650: [Direct Transfer] Fix the CSV export button click area
  docs/changes/5.2.1.md
  nxdrive/data/qml/Link.qml
  nxdrive/data/qml/SessionItem.qml
Labels: QML, bugfix

#2743 NXDRIVE-2651: Disable the local folder systray button when synchroniz…
  docs/changes/5.2.1.md
  nxdrive/data/qml/Systray.qml
Labels: QML, improvement

#2744 NXDRIVE-2649: Release 5.2.1
  docs/changes.md
  docs/changes/5.2.1.md
Labels: Release

#2745 NXDRIVE-2649: Bump the version to 5.2.2
  docs/changes.md
  docs/changes/5.2.2.md
  nxdrive/__init__.py
Labels: Release

#2749 NXDRIVE-2654: Remove the execution.profile custom metric
  docs/changes/5.2.2.md
  nxdrive/client/remote_client.py
  nxdrive/metrics/constants.py
  nxdrive/options.py
  tests/unit/test_options.py
Labels: clean-up

#2753 NXDRIVE-2656: Improve crash file handling
  docs/changes/5.2.2.md
  nxdrive/commandline.py
  nxdrive/fatal_error.py
  tests/unit/test_health_checker.py
Labels: improvement

#2759 NXDRIVE-2657: Fix database is_healthy() check to ensure to close the …
  docs/changes/5.2.2.md
  nxdrive/engine/dao/utils.py
Labels: bugfix

#2754 NXDRIVE-2548: Databases refactoring
  docs/changes/5.2.2.md
  nxdrive/auth/oauth2.py
  nxdrive/client/proxy.py
  nxdrive/client/remote_client.py
  nxdrive/engine/dao/__init__.py
  nxdrive/engine/dao/adapters.py
  nxdrive/engine/dao/base.py
  nxdrive/engine/dao/engine.py
  nxdrive/engine/dao/manager.py
  nxdrive/engine/engine.py
  nxdrive/engine/queue_manager.py
  nxdrive/engine/watcher/local_watcher.py
  nxdrive/engine/watcher/remote_watcher.py
  nxdrive/engine/workers.py
  nxdrive/gui/api.py
  nxdrive/gui/application.py
  nxdrive/manager.py
  nxdrive/report.py
  tests/functional/test_db_backup.py
  tests/old_functional/test_local_move_and_rename.py
  tests/unit/conftest.py
  tests/unit/test_autolock.py
  tests/unit/test_proxy.py
Labels: improvement

#2760 NXDRIVE-2658: [Direct Edit] Handle invalid data returned by the serve…
  docs/changes/5.2.2.md
  nxdrive/data/i18n/i18n.json
  nxdrive/direct_edit.py
  tests/functional/test_direct_edit.py
Labels: bugfix

#2766 NXDRIVE-2661: Set a higher logging level for Options changes
  docs/changes/5.2.2.md
  nxdrive/options.py
Labels: improvement

#2774 NXDRIVE-2640: [Windows] Remote deletions are not locally impacted whe…
  docs/changes/5.2.2.md
  nxdrive/client/local/base.py
  nxdrive/engine/engine.py
  nxdrive/utils.py
  tests/functional/test_engine.py
  tests/unit/test_utils.py
Labels: Windows, bugfix
