Repository nuxeo/nuxeo-drive, pull requests merged in 2021-06, with the labels that each got.

#2775 NXDRIVE-2218: Introduce (database) Migrations objects
  docs/changes/5.2.2.md
  nxdrive/engine/dao/migrations/__init__.py
  nxdrive/engine/dao/migrations/engine/0021_initial_migration.py
  nxdrive/engine/dao/migrations/engine/__init__.py
  nxdrive/engine/dao/migrations/manager/0004_initial_migration.py
  nxdrive/engine/dao/migrations/manager/__init__.py
  nxdrive/engine/dao/migrations/migration.py
  tests/unit/test_engine_dao.py
  tools/skiplist.py
Labels: improvement

#2779 NXDRIVE-2670: Ignore "start on boot" option setter errors
  docs/changes/5.2.2.md
  nxdrive/manager.py
Labels: bugfix

#2780 NXDRIVE-2548: Move dao module to root
  docs/changes/5.2.2.md
  nxdrive/auth/oauth2.py
  nxdrive/client/proxy.py
  nxdrive/client/remote_client.py
  nxdrive/dao/__init__.py
  nxdrive/dao/adapters.py
  nxdrive/dao/base.py
  nxdrive/dao/engine.py
  nxdrive/dao/manager.py
  nxdrive/dao/migrations/__init__.py
  nxdrive/dao/migrations/engine/0021_initial_migration.py
  nxdrive/dao/migrations/engine/__init__.py
  nxdrive/dao/migrations/manager/0004_initial_migration.py
  nxdrive/dao/migrations/manager/__init__.py
  nxdrive/dao/migrations/migration.py
  nxdrive/dao/utils.py
  nxdrive/engine/engine.py
  nxdrive/engine/queue_manager.py
  nxdrive/engine/watcher/local_watcher.py
  nxdrive/engine/watcher/remote_watcher.py
  nxdrive/engine/workers.py
  nxdrive/gui/api.py
  nxdrive/gui/application.py
  nxdrive/manager.py
  nxdrive/report.py
  tests/functional/test_db_backup.py
  tests/old_functional/__init__.py
  tests/old_functional/test_local_move_and_rename.py
  tests/unit/conftest.py
  tests/unit/test_autolock.py
  tests/unit/test_engine_dao.py
  tests/unit/test_proxy.py
Labels: improvement

#2786 NXDRIVE-2321: Fix file name escaping when checking for document exist…
  docs/changes/5.2.2.md
  nxdrive/client/remote_client.py
  nxdrive/client/uploader/__init__.py
  tests/functional/test_remote_client.py
  tests/old_functional/__init__.py
Labels: bugfix

#2787 NXDRIVE-2673: Add custom metrics for the upload provider
  docs/changes/5.2.2.md
  nxdrive/client/uploader/__init__.py
  nxdrive/metrics/constants.py
Labels: improvement

#2796 NXDRIVE-2665: [Direct Transfer] Rename "Options" to "Advanced"
  docs/changes/5.2.2.md
  nxdrive/data/i18n/i18n.json
  nxdrive/gui/folders_dialog.py
Labels: improvement

#2797 NXDRIVE-2675: Show the device ID on the About tab
  docs/changes/5.2.2.md
  nxdrive/data/qml/AboutTab.qml
  nxdrive/gui/application.py
Labels: improvement

#2800 NXDRIVE-2676: Do not retry to send asynchronous metrics on error
  docs/changes/5.2.2.md
  nxdrive/metrics/poll_metrics.py
  tests/unit/test_custom_metrics.py
Labels: bugfix

#2801 NXDRIVE-2677: Add custom metrics about the uploaded file
  docs/changes/5.2.2.md
  nxdrive/client/uploader/direct_transfer.py
  nxdrive/metrics/constants.py
Labels: new-feature

#2802 NXDRIVE-2679: Add custom metrics about session items
  docs/changes/5.2.2.md
  nxdrive/engine/engine.py
  nxdrive/metrics/constants.py
Labels: improvement

#2805 NXDRIVE-2505: Move the release process from Travis-CI to GitHub Actions
  .github/workflows/release.yml
  .travis.yml
  docs/changes/5.2.2.md
  docs/deployment.md
  docs/support.md
  tools/cleanup.sh
  tools/deploy.sh
  tools/env.sh
  tools/linux/Dockerfile
  tools/linux/generate_installer.sh
  tools/osx/deploy_ci_agent.sh
  tools/osx/generate_installer.sh
  tools/posix/deploy_ci_agent.sh
  tools/qa.sh
  tools/release.sh
  tools/upload.sh
  tools/windows/deploy_ci_agent.ps1
  tools/windows/generate_installer.sh
Labels: QA/CI, improvement

#2806 NXDRIVE-2505: Fix workflow conditions
  .github/workflows/release.yml
Labels: QA/CI, bugfix

#2809 NXDRIVE-2681: [Direct Edit] Handle HTTP 502 (Bad Gateway), 503 (Servi…
  docs/changes/5.2.2.md
  nxdrive/direct_edit.py
  tests/old_functional/test_direct_edit.py
Labels: bugfix

#2810 NXDRIVE-2682: Fix mypy issues following the update to mypy 0.901
  docs/changes/5.2.2.md
  nxdrive/dao/base.py
  nxdrive/engine/queue_manager.py
  tools/deps/requirements-tests.txt
Labels: bugfix

#2811 NXDRIVE-2683: Ignore incomplete custom protocol URL token requests
  docs/changes/5.2.2.md
  nxdrive/gui/api.py
Labels: bugfix

#2812 NXDRIVE-2684: [macOS] Fix opened documents retrieval not interating-safe
  docs/changes/5.2.2.md
  nxdrive/osi/darwin/files.py
Labels: bugfix, macOS

#2813 NXDRIVE-2685: [Windows] Create setup dev env BAT script
  docs/changes/5.2.2.md
  tools/windows/scripts/setup-dev-env.bat
Labels: QA/CI, Windows, improvement

#2817 NXDRIVE-1995: Update changelog [skip-ci]
  docs/changes/5.2.2.md
Labels: doc

#2826 NXDRIVE-2505: Hopefully fixed docker stuff on GNU/Linux
  .github/workflows/release.yml
  tools/linux/generate_installer.sh
Labels: GNU/Linux, bugfix

#2827 NXDRIVE-2505: Fixes
  .github/workflows/release.yml
Labels: bugfix

#2828 NXDRIVE-2505: Fixes
  .github/workflows/release.yml
  tools/linux/generate_installer.sh
Labels: bugfix

#2829 NXDRIVE-2505: Fixes
  .github/workflows/alpha_cleanup.yml
  .github/workflows/beta_to_prod.yml
  .github/workflows/release.yml
  tools/linux/generate_installer.sh
  tools/osx/generate_installer.sh
  tools/windows/deploy_ci_agent.ps1
  tools/windows/generate_installer.sh
Labels: bugfix

#2833 NXDRIVE-2688: Add virtual environment facilities to deploy scripts
  docs/changes/5.2.2.md
  docs/deployment.md
  tools/deps/requirements-tests.txt
  tools/posix/deploy_ci_agent.sh
Labels: GNU/Linux, macOS, tests

#2830 NXDRIVE-2505: No need for bash files to generate installers
  .github/workflows/release.yml
  tools/linux/deploy_ci_agent.sh
  tools/linux/generate_installer.sh
  tools/osx/generate_installer.sh
  tools/windows/deploy_ci_agent.ps1
  tools/windows/generate_installer.sh
Labels: bugfix

#2834 NXDRIVE-2687: Fix new errors found by codespell 2.1.0
  docs/changes/5.2.2.md
  nxdrive/utils.py
  tools/spell.allowlist
  tools/spell.skip
  tools/windows/NuxeoDriveShellExtensions/NuxeoDriveUtil/json/json.h
Labels: bugfix

#2835 NXDRIVE-2689: Test test_wrong_server_reply()
  docs/changes/5.2.2.md
  tests/functional/test_remote_changes.py
Labels: bugfix, tests

#2836 NXDRIVE-2654: Remove missed option in the update check script
  tools/scripts/check_update_process.py
Labels: QA/CI, bugfix

#2837 NXDRIVE-2505: Final iteration
  .github/workflows/release.yml
  tools/osx/deploy_ci_agent.sh
  tools/osx/notarize.py
  tools/posix/deploy_ci_agent.sh
  tools/scripts/check_update_process.py
Labels: bugfix

#2838 NXDRIVE-2505: Add status badge on the README
  README.md
Labels: doc, improvement

#2839 NXDRIVE-2505: Fix branch name for the deploy step
  .github/workflows/release.yml
Labels: bugfix

#2843 NXDRIVE-2505: Fix alpha version number bump
  tools/bump-alpha-version.sh
Labels: bugfix

#2844 NXDRIVE-2505: releaseType is an empty string when run via the cronjob
  .github/workflows/release.yml
Labels: Release, bugfix

#2845 NXDRIVE-2691: Use proper job names in GitHub workflows
  .github/dependabot.yml
  .github/workflows/alpha_cleanup.yml
  .github/workflows/beta_to_prod.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/crowdin.yml
  .github/workflows/dead_code.yml
  .github/workflows/docker_build.yml
  .github/workflows/functional_tests.yml
  .github/workflows/integration_tests.yml
  .github/workflows/lint.yml
  .github/workflows/spell.yml
  .github/workflows/style.yml
  .github/workflows/translations.yml
  .github/workflows/types.yml
  .github/workflows/unit_tests.yml
  docs/changes/5.2.2.md
Labels: QA/CI, improvement

#2849 NXDRIVE-2664: Add custom metrics for features state
  docs/changes/5.2.2.md
  nxdrive/client/remote_client.py
  nxdrive/gui/application.py
  nxdrive/manager.py
  tests/functional/test_remote_client.py
Labels: improvement

#2850 NXDRIVE-2686: Fix backward compatibility checks handling the synchron…
  docs/changes/5.2.2.md
  nxdrive/manager.py
  nxdrive/utils.py
  tests/functional/test_behavior.py
  tests/functional/test_remote_client.py
Labels: bugfix

#2851 NXDRIVE-2505: Fix 'local: can only be used in a function'
  .github/workflows/release.yml
Labels: Release, bugfix

#2853 NXDRIVE-2634: Improve behavior on Add account screen
  docs/changes/5.2.2.md
  nxdrive/data/i18n/i18n.json
  nxdrive/data/qml/NewAccountPopup.qml
Labels: QML, improvement

#2856 NXDRIVE-2678: Sentry enablement as an option
  docs/changes/5.2.2.md
  nxdrive/data/i18n/i18n.json
  nxdrive/data/qml/GeneralTab.qml
  nxdrive/gui/application.py
  nxdrive/manager.py
  tools/skiplist.py
Labels: QML, improvement

#2864 NXDRIVE-2538: Better handle long paths or URLs in the Sync Tab
  nxdrive/data/qml/EngineSyncItem.qml
  nxdrive/data/qml/Link.qml
  nxdrive/data/qml/NuxeoToolTip.qml
Labels: QML, bugfix

#2863 NXDRIVE-2697: [GNU/Linux] Update AppImage tools
  docs/changes/5.2.2.md
  tools/linux/appimage/appdir-lint.sh
  tools/linux/appimage/appimagetool-x86_64.AppImage
  tools/linux/appimage/excludelist
  tools/linux/appimage/get.sh
  tools/linux/deploy_ci_agent.sh
Labels: GNU/Linux, Release, improvement

#2865 NXDRIVE-2698: Specify the UFT-8 encoding when reading/writing text files
  docs/changes/5.2.2.md
  ndrive.spec
  nxdrive/client/proxy.py
  nxdrive/manager.py
  nxdrive/osi/linux/linux.py
  nxdrive/session_csv.py
  nxdrive/utils.py
  tests/functional/test_engine.py
  tests/functional/test_local_client.py
  tests/old_functional/test_direct_transfer.py
  tests/resources/databases/ndrive_with_unicode_session_item.db
  tests/unit/test_health_checker.py
  tests/unit/test_local_client.py
  tests/unit/test_pid_lock_file.py
  tests/unit/test_session_csv.py
  tests/unit/test_utils.py
  tools/scripts/check_update_process.py
  tools/scripts/csv_to_log.py
  tools/scripts/slow_thread_detection.py
  tools/versions.py
Labels: bugfix

#2867 NXDRIVE-2142: Sanitize the filename in Direct Edit
  docs/changes/5.2.2.md
  nxdrive/direct_edit.py
  tests/old_functional/test_direct_edit.py
Labels: bugfix

#2868 NXDRIVE-2700: Prevent 'Comparison between bytes and string' warning
  docs/changes/5.2.2.md
  nxdrive/engine/engine.py
Labels: clean-up

#2869 NXDRIVE-2701: Lower logging level of unknown connection error
  docs/changes/5.2.2.md
  nxdrive/gui/api.py
Labels: clean-up

#2870 NXDRIVE-2672: Release 5.2.2
  docs/changes/5.2.2.md
Labels: Release

#2871 NXDRIVE-2672: Bump the version number to 5.2.3
  docs/changes.md
  docs/changes/5.2.3.md
  nxdrive/__init__.py
Labels: Release

#2878 NXDRIVE-2533: Add migration scripts in PyInstaller conf
  ndrive.spec
Labels: bugfix
