Repository nuxeo/nuxeo-drive, pull requests merged in 2021-01, with the labels that each got.

#2352 NXDRIVE-2468: Fix the deploy script when a release is missing
  docs/changes/4.5.1.md
  tools/deploy.sh
Labels: QA/CI, Release, bugfix

#2353 Revert "Bump idna from 2.10 to 3.1 in /tools/deps"
  docs/changes/4.5.1.md
  tools/deps/requirements.txt
Labels: bug, dependencies

#2348 NXDRIVE-2329: [Direct Transfer] Add a button to create a folder within the upload flow
  docs/changes/4.5.1.md
  nxdrive/client/remote_client.py
  nxdrive/client/uploader/direct_transfer.py
  nxdrive/constants.py
  nxdrive/data/i18n/i18n.json
  nxdrive/engine/engine.py
  nxdrive/gui/folders_dialog.py
  nxdrive/qt/constants.py
  nxdrive/qt/imports.py
  tests/old_functional/test_direct_transfer.py
  tests/unit/test_qt.py
Labels: improvement

#2356 NXDRIVE-2329: Disable new folder creation when operation not avaliable
  nxdrive/gui/folders_dialog.py
Labels: improvement

#2357 NXDRIVE-2329: Fix types
  nxdrive/gui/folders_dialog.py
Labels: clean-up

#2358 NXDRIVE-2453: [Direct Transfer] Missing label on the active sessions list
  docs/changes/4.5.1.md
  nxdrive/data/qml/DirectTransfer.qml
  nxdrive/gui/view.py
  tools/skiplist.py
Labels: QML, bugfix

#2367 NXDRIVE-2472: Fix a security issue when retrieving a SSL certificate
  docs/changes/4.5.1.md
  nxdrive/utils.py
Labels: bugfix

#2368 NXDRIVE-2472: Prefer to not setting the protocol
  nxdrive/utils.py
Labels: improvement

#2366 NXDRIVE-2438: Cancel folder transfer when selecting a folder with the same name
  docs/changes/4.5.1.md
  nxdrive/client/remote_client.py
  nxdrive/client/uploader/direct_transfer.py
  nxdrive/data/i18n/i18n.json
  nxdrive/gui/application.py
  nxdrive/gui/folders_dialog.py
  nxdrive/qt/imports.py
Labels: bugfix

#2373 NXDRIVE-2438: Use a more specific NXQL query with the mixinType
  nxdrive/client/remote_client.py
  nxdrive/client/uploader/direct_transfer.py
  nxdrive/gui/folders_dialog.py
Labels: improvement

#2375 NXDRIVE-2354: Align buttons
  nxdrive/data/qml/AccountsTab.qml
  nxdrive/data/qml/ChannelPopup.qml
  nxdrive/data/qml/ConfirmPopup.qml
  nxdrive/data/qml/DeletionPopup.qml
  nxdrive/data/qml/LogLevelPopup.qml
  nxdrive/data/qml/NewAccountPopup.qml
  nxdrive/data/qml/NuxeoButton.qml
  nxdrive/data/qml/NuxeoInput.qml
  nxdrive/data/qml/ProxyPopup.qml
  nxdrive/gui/application.py
Labels: QML

#2380 NXDRIVE-2400: Enable back GNU/Linux releases
  .travis.yml
  docs/changes/4.5.1.md
Labels: GNU/Linux, QA/CI

#2381 NXDRIVE-2413: Refresh the GUI after a feature state has changed
  docs/changes/4.5.1.md
  nxdrive/data/i18n/i18n.json
  nxdrive/data/qml/GeneralTab.qml
  nxdrive/data/qml/Systray.qml
  nxdrive/gui/application.py
  nxdrive/gui/view.py
  nxdrive/manager.py
Labels: QML, bugfix

#2383 NXDRIVE-2477: Use the Python minor version in GitHub workflows
  .github/workflows/dead_code.yml
  .github/workflows/functional_tests.yml
  .github/workflows/integration_tests.yml
  .github/workflows/lint.yml
  .github/workflows/spell.yml
  .github/workflows/style.yml
  .github/workflows/translations.yml
  .github/workflows/types.yml
  .github/workflows/unit_tests.yml
  docs/changes/4.5.1.md
Labels: QA/CI, bugfix

#2384 NXDRIVE-2409: [Direct Edit] Handle document unlock error when it is already locked by someone else
  docs/changes/4.5.1.md
  nxdrive/direct_edit.py
  tests/old_functional/test_direct_edit.py
Labels: bugfix

#2389 NXDRIVE-2410: Better server URL comparison
  docs/changes/4.5.1.md
  nxdrive/direct_edit.py
Labels: bugfix

#2391 NXDRIVE-2481: [Direct Transfer] Remove the beta label
  docs/changes/4.5.1.md
  nxdrive/feature.py
Labels: improvement

#2392 NXDRIVE-2329: Add a metric
  nxdrive/engine/engine.py
  nxdrive/gui/folders_dialog.py
Labels: improvement

#2390 NXDRIVE-2482: Prevent upgrading from Windows 7
  docs/changes/4.5.1.md
  nxdrive/fatal_error.py
  nxdrive/updater/utils.py
Labels: Windows

#2393 NXDRIVE-2480: [Direct Transfer] Add an information icon in options
  docs/changes/4.5.1.md
  nxdrive/data/i18n/i18n.json
  nxdrive/gui/folders_dialog.py
  nxdrive/qt/constants.py
Labels: improvement

#2394 NXDRIVE-2329: [Direct Transfer] Remove trim spaces in new folder input
  nxdrive/data/i18n/i18n.json
  nxdrive/gui/folders_dialog.py
Labels: bugfix

#2396 NXDRIVE-2438: [Direct Transfer] Display a link to the remote folder
  docs/changes/4.5.1.md
  nxdrive/data/i18n/i18n.json
  nxdrive/engine/engine.py
  nxdrive/gui/application.py
  nxdrive/gui/folders_dialog.py
  nxdrive/gui/folders_treeview.py
  tests/old_functional/test_direct_transfer.py
Labels: improvement

#2398 NXDRIVE-2402: Enable the boto3 integration into Sentry
  docs/changes/4.5.1.md
  nxdrive/__main__.py
Labels: improvement

#2406 NXDRIVE-2485: Use os.path.realpath() instead of abspath()
  docs/changes/4.5.1.md
  nxdrive/client/local/base.py
  nxdrive/utils.py
Labels: bugfix

#2414 NXDRIVE-2329: [Direct Transfer] Give more space to the QTreeView
  nxdrive/gui/folders_dialog.py
Labels: improvement

#2416 NXDRIVE-2489: [Windows] Subfolder content not synced on unfiltering
  nxdrive/engine/dao/sqlite.py
  tests/resources/databases/engine_migration_18.db
  tests/unit/test_engine_dao.py
Labels: Windows, bugfix

#2423 NXDRIVE-2503: Skip errors happening at the end of tests
  docs/changes/4.5.1.md
  tests/old_functional/common.py
Labels: bugfix, tests

#2421 NXDRIVE-2489: [Direct Transfer] Fix folder and sub-folders upload
  nxdrive/client/uploader/direct_transfer.py
  nxdrive/engine/dao/sqlite.py
  nxdrive/engine/engine.py
  tests/functional/test_engine.py
  tests/old_functional/common.py
  tests/old_functional/test_direct_edit.py
  tests/old_functional/test_direct_transfer.py
  tests/old_functional/test_ignored.py
  tests/old_functional/test_local_creations.py
  tests/old_functional/test_readonly.py
  tests/old_functional/test_shared_folders.py
  tests/old_functional/test_synchronization.py
  tests/unit/test_engine_dao.py
Labels: bugfix

#2426 NXDRIVE-2489: Remove useless manual Path -> str calls
  docs/changes/4.5.1.md
  nxdrive/engine/dao/sqlite.py
Labels: clean-up

#2427 NXDRIVE-2474: Release 4.5.1
  docs/changes/4.5.1.md
Labels: Release

#2428 NXDRIVE-2474: Bump the version number to 4.5.2
  docs/changes.md
  docs/changes/4.5.2.md
  nxdrive/__init__.py
Labels: Release
