Repository nuxeo/nuxeo-drive, pull requests merged in 2021-04, with the labels that each got.

#2576 NXDRIVE-2587: Skip conflict resolution on non-standard digest
  docs/changes/5.1.1.md
  nxdrive/engine/engine.py
  tests/functional/test_engine.py
Labels: bugfix

#2577 NXDRIVE-2588: Handle 'parent_remotely_deleted' state in the local watcher
  docs/changes/5.1.1.md
  nxdrive/engine/queue_manager.py
Labels: bugfix

#2578 NXDRIVE-2589: Lower logging level of installer integrity check failure
  docs/changes/5.1.1.md
  nxdrive/updater/__init__.py
  nxdrive/updater/base.py
  tests/functional/test_updater.py
Labels: improvement

#2580 NXDRIVE-2463: Add support for idempotent requests
  docs/changes/5.1.1.md
  docs/configuration.md
  nxdrive/client/uploader/__init__.py
  nxdrive/engine/dao/sqlite.py
  nxdrive/engine/processor.py
  nxdrive/engine/queue_manager.py
  nxdrive/objects.py
  nxdrive/options.py
  tests/old_functional/test_synchronization.py
  tests/old_functional/test_transfer.py
  tests/unit/test_engine_dao.py
Labels: improvement

#2581 NXDRIVE-2590: Restart upload on still outdated refreshed AWS credentials
  docs/changes/5.1.1.md
  nxdrive/engine/processor.py
Labels: bugfix

#2586 NXDRIVE-2594: Upgrade from Python 3.9.2 to 3.9.4
  docs/changes/5.1.1.md
  docs/deployment.md
  docs/support.md
  tools/linux/travis.sh
  tools/posix/deploy_ci_agent.sh
  tools/windows/deploy_ci_agent.ps1
Labels: improvement

#2579 NXDRIVE-2560: Add a code coverage GitHub Action on PRs
  .github/workflows/functional_tests.yml
  .github/workflows/integration_tests.yml
  .github/workflows/unit_tests.yml
  docs/changes/5.1.1.md
  setup.cfg
Labels: QA/CI, new-feature

#2588 NXDRIVE-2163: [macOS] Move the application to $HOME/Applications on a…
  docs/changes/5.1.1.md
  nxdrive/updater/darwin.py
Labels: bugfix, macOS

#2589 NXDRIVE-2560: Run coverage on master
  .github/workflows/functional_tests.yml
  .github/workflows/integration_tests.yml
  .github/workflows/unit_tests.yml
Labels: tests

#2590 NXDRIVE-2597: Use a LRU cache for translation strings
  docs/changes/5.1.1.md
  nxdrive/translator.py
  tests/unit/test_translator.py
Labels: improvement

#2591 NXDRIVE-2595: Restart transfer from the ground when resuming with an …
  docs/changes/5.1.1.md
  nxdrive/client/uploader/__init__.py
Labels: bugfix

#2592 NXDRIVE-2585: Rename the file size label in the monitoring
  docs/changes/5.1.1.md
  nxdrive/data/i18n/i18n.json
Labels: improvement

#2594 NXDRIVE-2597: Take into account values in the key name of the LRU cache
  nxdrive/translator.py
  tests/unit/test_translator.py
Labels: bugfix

#2593 NXDRIVE-2598: Retry S3 non-chunked uploads on expired credentials
  docs/changes/5.1.1.md
  nxdrive/client/uploader/__init__.py
  nxdrive/engine/engine.py
  nxdrive/engine/processor.py
  nxdrive/engine/workers.py
Labels: bugfix

#2597 NXDRIVE-2579: Rename systray menu labels
  docs/changes/5.1.1.md
  nxdrive/data/i18n/i18n.json
Labels: improvement

#2600 NXDRIVE-2591: [Direct Transfer] Hide the CSV export icon when no documents were uploaded
  docs/changes/5.1.1.md
  nxdrive/data/qml/SessionItem.qml
Labels: improvement

#2601 NXDRIVE-2586: Reword Advanced Settings
  docs/changes/5.1.1.md
  nxdrive/data/i18n/i18n.json
  nxdrive/data/qml/DeletionPopup.qml
  nxdrive/data/qml/GeneralTab.qml
Labels: improvement

#2609 NXDRIVE-2599: Enhance the auto-update check script
  docs/changes/5.1.1.md
  tools/scripts/check_update_process.py
Labels: QA/CI, improvement

#2610 NXDRIVE-2600: Improve options.py coverage
  docs/changes/5.1.1.md
  nxdrive/options.py
  tests/unit/test_options.py
  tools/windows/deploy_ci_agent.ps1
Labels: clean-up, improvement

#2611 NXDRIVE-2601: [Windows] Fix test_valid_argument_value() integration test
  docs/changes/5.1.1.md
  tests/integration/windows/test_cli.py
Labels: Windows, bugfix, tests

#2614 NXDRIVE-2592: Release 5.1.1
  docs/changes.md
  docs/changes/5.1.1.md
Labels: Release

#2616 NXDRIVE-2592: Bump the version to 5.1.2
  docs/changes.md
  docs/changes/5.1.2.md
  nxdrive/__init__.py
Labels: Release

#2617 NXDRIVE-2602: Remove unnecessary Codecov token usage
  .github/workflows/functional_tests.yml
  .github/workflows/integration_tests.yml
  .github/workflows/unit_tests.yml
  docs/changes/5.1.2.md
Labels: QA/CI, clean-up

#2618 NXDRIVE-2603: Fix test_flooding_prevention() when run from tox
  docs/changes/5.1.2.md
  tests/unit/test_tracing.py
  tox.ini
Labels: bugfix, tests

#2605 NXDRIVE-2581: Add the synchronization feature
  .gitignore
  docs/changes/5.1.2.md
  docs/configuration.md
  nxdrive/data/i18n/i18n.json
  nxdrive/data/qml/AccountsTab.qml
  nxdrive/data/qml/Systray.qml
  nxdrive/data/qml/SystrayMenu.qml
  nxdrive/engine/engine.py
  nxdrive/engine/watcher/local_watcher.py
  nxdrive/engine/watcher/remote_watcher.py
  nxdrive/feature.py
  nxdrive/gui/api.py
  nxdrive/gui/application.py
  nxdrive/manager.py
  nxdrive/options.py
  nxdrive/poll_workers.py
  tests/functional/test_server_options.py
  tests/functional/test_updater.py
Labels: improvement

#2628 NXDRIVE-2605: Declare early the remote attribute in Engine
  nxdrive/engine/engine.py
Labels: bugfix

#2629 NXDRIVE-2606: Catch TypeError in RemoteFileInfo.from_dict()
  docs/changes/5.1.2.md
  nxdrive/objects.py
Labels: bug

#2630 NXDRIVE-2607: Handle invalid data returned by the server when asking for a batchId
  docs/changes/5.1.2.md
  nxdrive/client/uploader/__init__.py
  tests/old_functional/test_transfer.py
  tools/deps/requirements-tests.txt
Labels: bugfix

#2631 NXDRIVE-2581: Enable back synchronization in old functional tests
  tests/old_functional/common.py
Labels: bugfix, tests

#2635 NXDRIVE-2610: Remove the TRACE logging level, obsolete since 4.1.0
  docs/changes/5.1.2.md
  docs/configuration.md
  nxdrive/commandline.py
  nxdrive/logging_config.py
Labels: clean-up

#2636 NXDRIVE-2581: Ask for restart when the synchronization feature state is updated
  docs/changes/5.1.2.md
  nxdrive/data/i18n/i18n.json
  nxdrive/feature.py
  nxdrive/gui/application.py
  nxdrive/gui/view.py
  nxdrive/poll_workers.py
Labels: improvement

#2642 NXDRIVE-826: Add OAuth2 capabilities
  docs/changes/5.1.2.md
  docs/configuration.md
  nxdrive/auth/__init__.py
  nxdrive/auth/base.py
  nxdrive/auth/oauth2.py
  nxdrive/auth/token.py
  nxdrive/client/remote_client.py
  nxdrive/commandline.py
  nxdrive/data/i18n/i18n.json
  nxdrive/data/qml/NewAccountPopup.qml
  nxdrive/engine/engine.py
  nxdrive/gui/api.py
  nxdrive/gui/application.py
  nxdrive/manager.py
  nxdrive/objects.py
  nxdrive/options.py
  nxdrive/utils.py
  tests/unit/test_utils.py
  tools/deps/requirements.txt
Labels: new-feature

#2644 NXDRIVE-2617: Move to cryptography module for cryptography stuff
  docs/changes/5.1.2.md
  nxdrive/utils.py
  tests/unit/test_utils.py
  tools/deps/requirements.txt
Labels: dependencies, improvement

#2647 NXDRIVE-2581: Fix old functional tests when the sync feature is local…
  tests/old_functional/common.py
Labels: bugfix, tests

#2648 NXDRIVE-2371: Secure storage of the token in the database
  docs/changes/5.1.2.md
  nxdrive/engine/engine.py
  nxdrive/utils.py
Labels: bugfix

#2649 NXDRIVE-2371: Prevent error on empty token and add tests
  nxdrive/engine/engine.py
  tests/functional/test_engine.py
Labels: bugfix, tests

#2650 NXDRIVE-2619: Remove Engine databases on failed account addition
  docs/changes/5.1.2.md
  nxdrive/engine/engine.py
  nxdrive/manager.py
  tests/functional/test_bind_server.py
Labels: improvement

#2654 NXDRIVE-2620: Ignore RuntimeError: wrapped C/C++ object of type Linki…
  docs/changes/5.1.2.md
  nxdrive/engine/activity.py
Labels: bugfix, tests

#2655 NXDRIVE-2621: Handle HTTPError 404 (Not Found) errors
  docs/changes/5.1.2.md
  nxdrive/data/i18n/i18n.json
  nxdrive/direct_edit.py
  nxdrive/gui/application.py
  tests/functional/conftest.py
  tests/functional/test_direct_edit.py
Labels: bugfix

#2657 NXDRIVE-2622: Fix parsing of paths in local configuration file
  docs/changes/5.1.2.md
  nxdrive/options.py
  tests/unit/test_commandline.py
Labels: bugfix

#2658 NXDRIVE-2623: Ignore RuntimeError: wrapped C/C++ object of type Queue…
  docs/changes/5.1.2.md
  nxdrive/engine/queue_manager.py
Labels: bugfix, tests

#2659 NXDRIVE-2624: Handle HTTP 408 errors (Request Timeout)
  docs/changes/5.1.2.md
  nxdrive/engine/processor.py
Labels: bugfix

#2661 NXDRIVE-2625: [Direct Transfer] Prevent constraint error when pausing…
  docs/changes/5.1.2.md
  nxdrive/client/remote_client.py
  nxdrive/client/uploader/__init__.py
  nxdrive/engine/dao/sqlite.py
  nxdrive/engine/processor.py
Labels: bugfix

#2651 NXDRIVE-2583: Add a new settings tab when the synchronization is enabled
  docs/changes/5.1.2.md
  nxdrive/data/i18n/i18n.json
  nxdrive/data/qml/AccountsTab.qml
  nxdrive/data/qml/EngineSyncItem.qml
  nxdrive/data/qml/GeneralTab.qml
  nxdrive/data/qml/Settings.qml
  nxdrive/data/qml/SynchronizationTab.qml
  nxdrive/gui/application.py
Labels: QML, improvement
