Repository nuxeo/nuxeo-drive, pull requests merged in 2021-03, with the labels that each got.

#2511 NXDRIVE-2539: Fix endless synchronization on permission error when se…
  docs/changes/5.0.1.md
  nxdrive/engine/watcher/local_watcher.py
Labels: bugfix

#2512 NXDRIVE-2530: Add logs for the deletion behavior state
  docs/changes/5.0.1.md
  nxdrive/gui/api.py
  nxdrive/manager.py
  nxdrive/options.py
  tools/skiplist.py
Labels: bugfix

#2514 NXDRIVE-2543: Fix test_file_action_with_values() to finish the action
  docs/changes/5.0.1.md
  tests/unit/test_action.py
Labels: bugfix, tests

#2516 NXDRIVE-2551: Reword the auto-update option on the Settings screen
  docs/changes/5.0.1.md
  nxdrive/data/i18n/i18n.json
Labels: improvement

#2518 NXDRIVE-2549: Fix test number display
  docs/changes/5.0.1.md
  tools/posix/deploy_ci_agent.sh
Labels: improvement, tests

#2519 NXDRIVE-2550: Prevent Sentry flooding
  docs/changes/5.0.1.md
  nxdrive/__main__.py
  nxdrive/tracing.py
  tests/unit/test_tracing.py
Labels: improvement

#2528 NXDRIVE-2555: Use a temporary folder for database storage in engine_d…
  tests/unit/conftest.py
Labels: improvement, tests

#2532 NXDRIVE-2553: Fix tests no more passing because of __slots__ constraints
  nxdrive/direct_edit.py
  tests/old_functional/test_direct_edit.py
  tests/old_functional/test_remote_move_and_rename.py
  tests/old_functional/test_transfer.py
Labels: bugfix, tests

#2533 NXDRIVE-2557: Add a Google Analytics metric for the machine type
  docs/changes/5.0.1.md
  nxdrive/engine/tracker.py
Labels: improvement

#2534 NXDRIVE-2553: Fix test_chunk_upload_error() no more passing because o…
  tests/old_functional/test_direct_transfer.py
Labels: bugfix, tests

#2498 NXDRIVE-2476: Add usage metrics in HTTP headers
  docs/changes/5.0.1.md
  docs/configuration.md
  nxdrive/__main__.py
  nxdrive/client/local/darwin.py
  nxdrive/client/proxy.py
  nxdrive/client/remote_client.py
  nxdrive/client/uploader/__init__.py
  nxdrive/client/uploader/direct_transfer.py
  nxdrive/constants.py
  nxdrive/direct_edit.py
  nxdrive/engine/engine.py
  nxdrive/engine/processor.py
  nxdrive/engine/tracker.py
  nxdrive/engine/workers.py
  nxdrive/gui/api.py
  nxdrive/gui/application.py
  nxdrive/manager.py
  nxdrive/metrics/__init__.py
  nxdrive/metrics/constants.py
  nxdrive/metrics/poll_metrics.py
  nxdrive/metrics/utils.py
  nxdrive/options.py
  nxdrive/updater/base.py
  nxdrive/utils.py
  tests/functional/test_tracker.py
  tests/old_functional/test_direct_edit.py
  tests/old_functional/test_local_filter.py
  tests/old_functional/test_readonly.py
  tests/unit/test_custom_metrics.py
  tests/unit/test_utils.py
Labels: new-feature

#2538 NXDRIVE-2476: Update doc
  docs/configuration.md
Labels: bugfix, doc

#2540 NXDRIVE-2476: [Direct Transfer] Fix session status metric
  nxdrive/engine/engine.py
  nxdrive/engine/processor.py
Labels: bugfix

#2541 NXDRIVE-2568: Add the Python client version in the About tab
  docs/changes/5.0.1.md
  nxdrive/gui/application.py
  nxdrive/manager.py
Labels: improvement

#2542 NXDRIVE-2562: Always bring the account window after being redirected …
  docs/changes/5.0.1.md
  nxdrive/gui/api.py
Labels: improvement

#2543 NXDRIVE-2504: Focus on the filters warning message box
  docs/changes/5.0.1.md
  nxdrive/gui/application.py
Labels: improvement

#2544 NXDRIVE-2570: Fix window focus that sometimes is lost
  docs/changes/5.0.1.md
  nxdrive/gui/application.py
Labels: improvement

#2545 NXDRIVE-2559: CSV filename should be elided when too long
  docs/changes/5.0.1.md
  nxdrive/data/qml/SessionItem.qml
Labels: bugfix

#2546 NXDRIVE-2569: Fix error notification when the upload is paused
  docs/changes/5.0.1.md
  nxdrive/engine/processor.py
Labels: bugfix

#2547 NXDRIVE-2521: Release 5.1.0
  docs/changes.md
  docs/changes/5.1.0.md
  nxdrive/__init__.py
Labels: Release

#2548 NXDRIVE-2521: Bump the version number to 5.1.1
  docs/changes.md
  docs/changes/5.1.1.md
  nxdrive/__init__.py
Labels: Release

#2570 NXDRIVE-2572: [Direct Transfer] Use "AddChildren" permission instead of "ReadWrite" for entitlement of places where one can upload into
  docs/changes/5.1.1.md
  nxdrive/gui/folders_model.py
Labels: improvement

#2571 NXDRIVE-2575: Fix error message when get_metadata_infos() would likel…
  docs/changes/5.1.1.md
  nxdrive/manager.py
Labels: bugfix

#2572 NXDRIVE-2574: Handle pair state deleted-moved as a remotely created
  docs/changes/5.1.1.md
  nxdrive/engine/dao/sqlite.py
Labels: bugfix

#2566 NXDRIVE-2333: Functional tests should be retried with only one process
  docs/changes/5.1.1.md
  tools/posix/deploy_ci_agent.sh
  tools/windows/deploy_ci_agent.ps1
Labels: improvement

#2560 NXDRIVE-2558: Add a custom metric for hard crashes
  docs/changes/5.1.1.md
  nxdrive/commandline.py
  nxdrive/fatal_error.py
  nxdrive/gui/application.py
  nxdrive/manager.py
  nxdrive/metrics/constants.py
  nxdrive/state.py
Labels: improvement

#2567 NXDRIVE-2334: Update the translation check script to verify only missing arguments
  docs/changes/5.1.1.md
  tools/check_translations.py
Labels: improvement

#2569 NXDRIVE-2443: Bypass all OS errors in disk_space()
  docs/changes/5.1.1.md
  nxdrive/utils.py
Labels: bugfix

#2568 NXDRIVE-2427: Make the end of session notification clickable
  docs/changes/5.1.1.md
  nxdrive/engine/engine.py
  nxdrive/gui/application.py
  nxdrive/notification.py
Labels: improvement
